import { Fragment, useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";
import { ChevronDown, ChevronRight, Copy, Pencil, Plus } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/api";
import { HeartbeatIndicator } from "@/components/heartbeat-indicator";
import { KeyValueEditor, pairsToRecord, validatePairs, type Pair } from "@/components/key-value-editor";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { formatBytes } from "@/lib/utils";
import type { Node, User } from "@/types";

const labelRows = (node: Node): Pair[] => Object.entries(node.labels).map(([key, value], index) => ({ id: `${node.id}-${index}`, key, value }));
export function Nodes({ user }: { user: User }) {
  const [params] = useSearchParams(), [expanded, setExpanded] = useState<string>(), [token, setToken] = useState(""), [editing, setEditing] = useState<Node>(), [editName, setEditName] = useState(""), [editLabels, setEditLabels] = useState<Pair[]>([]);
  const query = useQuery({ queryKey: ["nodes"], queryFn: api.nodes, refetchInterval: 2000 }), qc = useQueryClient();
  useEffect(() => { const requested = params.get("node"); if (requested) setExpanded(requested); }, [params]);
  const action = useMutation({ mutationFn: ({ id, action }: { id: string; action: "drain" | "resume" }) => api.setNode(id, action), onSuccess: (_, value) => { toast.success(`Node ${value.action === "drain" ? "drained" : "resumed"}`); qc.invalidateQueries({ queryKey: ["nodes"] }); }, onError: (error: Error) => toast.error(error.message) });
  const update = useMutation({ mutationFn: () => api.updateNode(editing!.id, editName.trim(), pairsToRecord(editLabels)), onSuccess: () => { toast.success("Node metadata updated"); setEditing(undefined); qc.invalidateQueries({ queryKey: ["nodes"] }); }, onError: (error: Error) => toast.error(error.message) });
  const openEdit = (node: Node) => { setEditing(node); setEditName(node.name); setEditLabels(labelRows(node)); };
  const save = () => { if (!editName.trim()) return toast.error("Node name is required"); if (Object.keys(validatePairs(editLabels, "labels")).length) return toast.error("Fix the label errors"); update.mutate(); };
  return <div className="space-y-4"><div className="flex items-center justify-between"><h1 className="text-xl font-semibold">Nodes</h1>{user.role === "admin" && <Dialog><DialogTrigger asChild><Button size="sm" onClick={() => api.enrollmentToken().then((value) => setToken(value.token)).catch((error) => toast.error(error.message))}><Plus className="size-4"/>Enroll node</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Enrollment token</DialogTitle><DialogDescription>Use this one-time token within 15 minutes.</DialogDescription></DialogHeader><div className="flex gap-2"><code className="min-w-0 flex-1 break-all rounded bg-muted p-3 text-xs">{token || "Generating…"}</code><Button variant="outline" size="icon" onClick={() => navigator.clipboard.writeText(token)}><Copy className="size-4"/></Button></div></DialogContent></Dialog>}</div>
    <div className="overflow-hidden rounded-md border"><Table><TableHeader><TableRow><TableHead/><TableHead>Node</TableHead><TableHead>Health</TableHead><TableHead>CPU</TableHead><TableHead>Memory</TableHead><TableHead>GPUs</TableHead><TableHead>Workspace</TableHead>{user.role === "admin" && <TableHead/>}</TableRow></TableHeader><TableBody>{(query.data ?? []).map((node) => <Fragment key={node.id}><TableRow><TableCell><Button variant="ghost" size="icon" onClick={() => setExpanded(expanded === node.id ? undefined : node.id)}>{expanded === node.id ? <ChevronDown className="size-4"/> : <ChevronRight className="size-4"/>}</Button></TableCell><TableCell className="font-medium">{node.name}<div className="font-mono text-[10px] text-muted-foreground">{node.id.slice(0, 12)}</div></TableCell><TableCell><HeartbeatIndicator status={node.status} lastHeartbeat={node.last_heartbeat}/></TableCell><TableCell>{(node.cpu_allocated_millis / 1000).toFixed(1)} / {(node.cpu_total_millis / 1000).toFixed(1)}</TableCell><TableCell>{formatBytes(node.memory_allocated_bytes)} / {formatBytes(node.memory_total_bytes)}</TableCell><TableCell>{node.gpus.filter((gpu) => gpu.allocated).length} / {node.gpus.length}</TableCell><TableCell>{formatBytes(node.workspace_free_bytes)}</TableCell>{user.role === "admin" && <TableCell><div className="flex justify-end gap-1"><Button size="sm" variant="ghost" onClick={() => openEdit(node)}><Pencil className="size-4"/>Edit</Button><Button size="sm" variant="outline" onClick={() => action.mutate({ id: node.id, action: node.status === "DRAINING" ? "resume" : "drain" })}>{node.status === "DRAINING" ? "Resume" : "Drain"}</Button></div></TableCell>}</TableRow>{expanded === node.id && <TableRow><TableCell/><TableCell colSpan={user.role === "admin" ? 7 : 6}><div className="grid gap-4 py-2 text-xs md:grid-cols-3"><div><p className="font-medium">Labels</p>{Object.entries(node.labels).map(([key, value]) => <code key={key} className="mr-2 inline-block">{key}={value}</code>)}</div><div><p className="font-medium">GPU discovery</p><p>{node.gpu_discovery.status} {node.gpu_discovery.error_code && `· ${node.gpu_discovery.error_code}`}</p><p className="text-muted-foreground">{node.gpu_discovery.message}</p></div><div><p className="font-medium">Inventory</p>{node.gpus.map((gpu) => <p key={gpu.uuid}>{gpu.model} · {formatBytes(gpu.vram_bytes)} · {gpu.uuid}</p>)}</div></div></TableCell></TableRow>}</Fragment>)}</TableBody></Table></div>
    <Dialog open={Boolean(editing)} onOpenChange={(open) => !open && setEditing(undefined)}><DialogContent><DialogHeader><DialogTitle>Edit node metadata</DialogTitle><DialogDescription>The effective name and labels override values reported by the agent.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-1.5"><Label htmlFor="node-name">Name</Label><Input id="node-name" maxLength={128} value={editName} onChange={(event) => setEditName(event.target.value)}/></div><div><Label className="mb-2 block">Labels</Label><KeyValueEditor rows={editLabels} onChange={setEditLabels} mode="labels"/></div></div><DialogFooter><Button variant="outline" onClick={() => setEditing(undefined)}>Cancel</Button><Button onClick={save} disabled={update.isPending}>{update.isPending ? "Saving…" : "Save changes"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
