import { useState } from "react";
import { KeyRound, ShieldCheck } from "lucide-react";
import { api } from "@/api";
import type { SetupStatus } from "@/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export function Setup({status,onComplete}:{status:SetupStatus;onComplete:()=>void}) {
  const [token,setToken]=useState(""),[username,setUsername]=useState(status.suggested_username||"admin"),[password,setPassword]=useState(""),[confirmation,setConfirmation]=useState(""),[error,setError]=useState(""),[submitting,setSubmitting]=useState(false);
  if(!status.enabled)return <main className="grid min-h-screen place-items-center bg-muted/30 p-4"><section className="w-full max-w-md space-y-3 rounded-lg border bg-background p-6 shadow-sm"><div className="flex items-center gap-2"><KeyRound className="size-5 text-destructive"/><h1 className="text-lg font-semibold">Setup credential unavailable</h1></div><p className="text-sm text-muted-foreground">This instance has no administrator and no setup token. Repair the installation before continuing.</p></section></main>;
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");if(password!==confirmation){setError("Passwords do not match.");return}setSubmitting(true);try{await api.setup(token,username,password);onComplete()}catch(err){setError(err instanceof Error?err.message:"Setup failed")}finally{setSubmitting(false)}};
  return <main className="grid min-h-screen place-items-center bg-muted/30 p-4"><form onSubmit={submit} className="w-full max-w-md space-y-5 rounded-lg border bg-background p-6 shadow-sm"><div className="space-y-2"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-primary"/><h1 className="text-lg font-semibold">Set up JobDock</h1></div><p className="text-sm text-muted-foreground">Create the permanent administrator account. The one-time setup token becomes unusable after this step.</p></div><div className="space-y-1.5"><Label htmlFor="setup-token">Setup token</Label><Input id="setup-token" autoFocus autoComplete="off" type="password" value={token} onChange={e=>setToken(e.target.value)} required/></div><div className="space-y-1.5"><Label htmlFor="setup-username">Administrator username</Label><Input id="setup-username" autoComplete="username" value={username} minLength={3} maxLength={64} onChange={e=>setUsername(e.target.value)} required/></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label htmlFor="setup-password">Password</Label><Input id="setup-password" type="password" autoComplete="new-password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} required/></div><div className="space-y-1.5"><Label htmlFor="setup-confirmation">Confirm password</Label><Input id="setup-confirmation" type="password" autoComplete="new-password" minLength={12} value={confirmation} onChange={e=>setConfirmation(e.target.value)} required/></div></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button className="w-full" disabled={submitting}>{submitting?"Creating administrator…":"Create administrator"}</Button></form></main>;
}
