import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import "./report.css";

type Point={captured_at:string;value:number;step?:number;sample_count?:number};
type Source={kind:string;name:string;role?:string};
type Widget={id:string;type:string;title?:string;size:{columns:number;rows:number};position:{x:number;y:number};sources:Source[];x_axis?:string;gauge_max_mode?:string;gauge_max_value?:number;scalar_aggregation?:string;appearance?:Record<string,unknown>};
type Dashboard={id:string;name:string;schema_version:number;updated_at:string;config:{widgets:Widget[];appearance?:{palette?:{id:string}}}};
type Metric={name:string;unit?:string;points:Point[];last:number;min:number;max:number;avg:number};
type Resource={captured_at:string;cpu_millis:number;memory_bytes:number;gpu_utilization_basis_points?:number;gpu_memory_bytes?:number};
type Matrix={name:string;values:(number|null)[][];row_labels?:string[];column_labels?:string[];labels?:string[];unit?:string;resolution?:{mode:string;original_rows:number;original_columns:number}};
type TablePage={name:string;subtype:string;columns:{name:string;unit?:string}[];items:{cursor:number;values:Record<string,unknown>}[];total:number};
type Distribution={name:string;group:string;unit?:string;samples:number[];bins:{lower:number;upper:number;count:number}[];summary:Record<string,number>};
type Manifest={schema_version:number;jobdock_version:string;generated_at:string;job:{id:string;name:string;status:string;created_at:string;started_at?:string;finished_at?:string};attempt:{id:string;attempt_number:number;status:string;created_at:string;started_at?:string;finished_at?:string};dashboards:Dashboard[];sources:{metrics:Metric[];resources:Resource[];matrices:Record<string,Matrix>;distributions:Record<string,Distribution[]>;tables:Record<string,TablePage>;logs:Record<string,string>;progress?:{global_progress?:number;current?:{value:number;milestone?:string}};checkpoints:unknown[]};warnings:{code:string;message:string;source?:string}[]};

const colors=["#60a5fa","#a78bfa","#f59e0b","#34d399","#fb7185","#22d3ee","#f472b6","#a3e635"];
const palettes:Record<string,{surface:[string,string,string];colors:string[]}>={
  jobdock:{surface:["#f8fafc","#0f172a","#2563eb"],colors:["#2563eb","#7c3aed","#0891b2","#16a34a","#f59e0b","#dc2626"]},
  midnight:{surface:["#090f1d","#f8fafc","#60a5fa"],colors:["#60a5fa","#a78bfa","#22d3ee","#34d399","#fbbf24","#fb7185"]},
  accessible:{surface:["#f8fafc","#0f172a","#0072b2"],colors:["#0072b2","#e69f00","#009e73","#cc79a7","#d55e00","#56b4e9"]},
  default:{surface:["#090f1d","#f8fafc","#60a5fa"],colors},
};

function decodeManifest():Manifest{const raw=document.getElementById("jobdock-report-data")?.textContent||"";const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes)) as Manifest}
const manifest=decodeManifest();

function App(){const[active,setActive]=useState(manifest.dashboards[0]?.id??"");const dashboard=manifest.dashboards.find(item=>item.id===active)??manifest.dashboards[0];return <main className="report"><header className="report-header"><div><h1>{manifest.job.name}</h1><div className="meta"><span>Job {manifest.job.id}</span><span>Attempt {manifest.attempt.attempt_number} · {manifest.attempt.id}</span><span>Generated {formatDate(manifest.generated_at)}</span>{!manifest.attempt.finished_at&&<span>Snapshot of data available at generation time</span>}</div></div><span className="status">{manifest.attempt.status}</span></header><nav className="tabs" aria-label="Dashboards">{manifest.dashboards.map(item=><button key={item.id} className={`tab ${item.id===dashboard?.id?"active":""}`} onClick={()=>setActive(item.id)}>{item.name}</button>)}</nav>{dashboard&&<DashboardView dashboard={dashboard}/>} {manifest.warnings.length>0&&<section className="notes"><h2>Export notes</h2><ul>{manifest.warnings.map((warning,index)=><li key={index}>{warning.message}{warning.source?` · ${warning.source}`:""}</li>)}</ul></section>}<footer className="trace">JobDock {manifest.jobdock_version} · report schema {manifest.schema_version} · dashboard IDs {manifest.dashboards.map(item=>item.id).join(", ")}</footer></main>}

function DashboardView({dashboard}:{dashboard:Dashboard}){const palette=palettes[dashboard.config.appearance?.palette?.id??""]??palettes.default;const style={"--dashboard-bg":palette.surface[0],"--dashboard-fg":palette.surface[1],"--dashboard-accent":palette.surface[2],...Object.fromEntries(palette.colors.map((color,index)=>[`--series-${index}`,color]))} as React.CSSProperties;return <section className="dashboard" style={style} aria-label={dashboard.name}><div className="grid">{dashboard.config.widgets.map(widget=><WidgetView key={widget.id} widget={widget}/>)}</div></section>}

function WidgetView({widget}:{widget:Widget}){const appearance=widget.appearance??{};const style:React.CSSProperties={gridColumn:`${widget.position.x+1}/span ${widget.size.columns}`,gridRow:`${widget.position.y+1}/span ${widget.size.rows}`,background:typeof appearance.background_color==="string"?appearance.background_color:undefined,color:typeof appearance.text_color==="string"?appearance.text_color:undefined,borderColor:typeof appearance.border_color==="string"?appearance.border_color:undefined};const warning=manifest.warnings.find(item=>item.source&&widget.sources.some(source=>item.source===`${source.kind}:${source.name}`));return <article className={`widget ${appearance.border_style==="subtle"?"subtle":""}`} style={style}><div className="widget-title">{widget.title||widget.type.replaceAll("_"," ")}{warning&&<span title={warning.message}> · limited</span>}</div><div className="widget-body"><WidgetContent widget={widget}/></div></article>}

function WidgetContent({widget}:{widget:Widget}){if(widget.type==="logs")return <Logs widget={widget}/>;if(["confusion_matrix","heatmap","correlation_heatmap"].includes(widget.type))return <MatrixView widget={widget}/>;if(widget.type==="data_grid")return <TableView widget={widget}/>;if(widget.type==="progress")return <ProgressView/>;if(widget.type==="checkpoint_timeline")return <div className="kpi"><div><strong>{manifest.sources.checkpoints.length}</strong><div>checkpoints</div></div></div>;if(["kpi","gauge"].includes(widget.type))return <ScalarView widget={widget}/>;const table=widget.sources.find(item=>item.kind==="table");if(table)return <TableChart widget={widget} page={manifest.sources.tables[table.name]}/>;const distribution=widget.sources.find(item=>item.kind==="distribution");if(distribution)return <DistributionChart widget={widget} items={manifest.sources.distributions[distribution.name]??[]}/>;const series=numericSeries(widget);return series.length?<Plot widget={widget} series={series}/>:<div className="empty">Data was not available at export time.</div>}

function numericSeries(widget:Widget){return widget.sources.flatMap((source,index)=>{if(source.kind==="metric"){const metric=manifest.sources.metrics.find(item=>item.name===source.name);return metric?[{name:metric.name,unit:metric.unit,points:metric.points,color:seriesColor(widget,source,index)}]:[]}if(source.kind==="resource"){const selectors:Record<string,(item:Resource)=>number|undefined>={cpu:item=>item.cpu_millis/1000,memory:item=>item.memory_bytes/1073741824,"gpu-utilization":item=>(item.gpu_utilization_basis_points??0)/100,"gpu-memory":item=>(item.gpu_memory_bytes??0)/1073741824};const units:Record<string,string>={cpu:"cores",memory:"GiB","gpu-utilization":"%","gpu-memory":"GiB"};const select=selectors[source.name];return select?[{name:source.name,unit:units[source.name],points:manifest.sources.resources.map(item=>({captured_at:item.captured_at,value:select(item)??0})),color:seriesColor(widget,source,index)}]:[]}return[]})}
function seriesColor(widget:Widget,source:Source,index:number){const custom=(widget.appearance?.series as Record<string,{color?:string}>|undefined)?.[`${source.kind}:${source.name}`]?.color;return custom||colorAt(index)}
function colorAt(index:number){return `var(--series-${index%6},${colors[index%colors.length]})`}

function Plot({widget,series}:{widget:Widget;series:{name:string;unit?:string;points:Point[];color:string}[]}){const[zoom,setZoom]=useState(1);const points=series.flatMap(item=>item.points.map(point=>point.value));const min=Math.min(...points),max=Math.max(...points),span=max-min||1;const shown=series.map(item=>({...item,points:item.points.slice(Math.max(0,item.points.length-Math.ceil(item.points.length/zoom)))}));const bar=widget.type.includes("bar")||widget.type==="feature_importance";const scatter=widget.type.includes("scatter")||widget.type==="prediction_vs_actual"||widget.type==="residual_plot";return <div style={{height:"100%",position:"relative"}}><svg className="chart" viewBox="0 0 800 320" preserveAspectRatio="none" role="img" aria-label={widget.title||widget.type}><line className="axis" x1="54" y1="282" x2="786" y2="282"/><line className="axis" x1="54" y1="16" x2="54" y2="282"/>{[0,.25,.5,.75,1].map(t=><React.Fragment key={t}><line className="gridline" x1="54" y1={282-t*266} x2="786" y2={282-t*266}/><text className="tick" x="48" y={285-t*266} textAnchor="end">{compact(min+t*span)}</text></React.Fragment>)}<text className="tick" x="420" y="310" textAnchor="middle">{widget.x_axis==="step"?"Step":"Time"}</text>{shown.map((item,seriesIndex)=>{const coords=item.points.map((point,index)=>({x:54+(index/Math.max(1,item.points.length-1))*732,y:282-((point.value-min)/span)*266,value:point.value}));if(bar)return coords.map((point,index)=><rect key={index} x={point.x-3} y={point.y} width={Math.max(5,700/Math.max(1,coords.length)-2)} height={282-point.y} fill={item.color} opacity={.82}><title>{item.name}: {compact(point.value)} {item.unit}</title></rect>);if(scatter)return coords.map((point,index)=><circle key={index} cx={point.x} cy={point.y} r="4" fill={item.color}><title>{item.name}: {compact(point.value)} {item.unit}</title></circle>);return <polyline key={seriesIndex} points={coords.map(point=>`${point.x},${point.y}`).join(" ")} fill="none" stroke={item.color} strokeWidth="2.5" vectorEffect="non-scaling-stroke"/>})}</svg><div className="legend">{series.map(item=><span key={item.name}><i style={{background:item.color}}/>{item.name}{item.unit?` (${item.unit})`:""}</span>)}<button onClick={()=>setZoom(value=>Math.min(8,value*2))}>+</button><button onClick={()=>setZoom(value=>Math.max(1,value/2))}>−</button></div></div>}

function MatrixView({widget}:{widget:Widget}){const source=widget.sources.find(item=>item.kind==="matrix");const matrix=source?manifest.sources.matrices[source.name]:undefined;if(!matrix?.values.length)return <div className="empty">Matrix data was not available at export time.</div>;const rows=matrix.values.length,columns=matrix.values[0]?.length??0,values=matrix.values.flat().filter((value):value is number=>value!==null),min=Math.min(...values),max=Math.max(...values),span=max-min||1;return <div className="matrix" style={{gridTemplateColumns:`repeat(${columns},minmax(10px,1fr))`,gridTemplateRows:`repeat(${rows},minmax(10px,1fr))`,aspectRatio:`${columns}/${rows}`,maxHeight:"100%",maxWidth:"100%",margin:"auto"}}>{matrix.values.flatMap((row,rowIndex)=>row.map((value,columnIndex)=><div key={`${rowIndex}-${columnIndex}`} className="matrix-cell" style={{background:value==null?"#334155":heat((value-min)/span)}}><span>{value==null?"":compact(value)}</span><title>{matrix.row_labels?.[rowIndex]??rowIndex} × {matrix.column_labels?.[columnIndex]??columnIndex}: {value??"N/A"}</title></div>))}</div>}
function heat(value:number){const hue=220-value*210;return `hsl(${hue} 72% ${32+value*18}%)`}

function TableView({widget}:{widget:Widget}){const source=widget.sources.find(item=>item.kind==="table");const page=source?manifest.sources.tables[source.name]:undefined;if(!page)return <div className="empty">Table data was not available at export time.</div>;return <div className="table-wrap"><table className="table"><thead><tr>{page.columns.map(column=><th key={column.name}>{column.name}{column.unit?` (${column.unit})`:""}</th>)}</tr></thead><tbody>{page.items.map(item=><tr key={item.cursor}>{page.columns.map(column=><td key={column.name}>{String(item.values[column.name]??"")}</td>)}</tr>)}</tbody></table></div>}

function TableChart({widget,page}:{widget:Widget;page?:TablePage}){if(!page?.items.length)return <div className="empty">Table data was not available at export time.</div>;const numeric=page.columns.filter(column=>page.items.some(item=>typeof item.values[column.name]==="number"));const labels=page.items.map((item,index)=>String(item.values[page.columns[0]?.name]??index));const values=page.items.map(item=>Number(item.values[numeric.at(-1)?.name??""]??0));const max=Math.max(...values.map(Math.abs),1);if(widget.type==="pie_chart"||widget.type==="donut_chart"){let start=0;const total=values.reduce((sum,value)=>sum+Math.max(0,value),0)||1;return <div style={{display:"grid",gridTemplateColumns:"minmax(100px,1fr) minmax(100px,.7fr)",height:"100%",alignItems:"center"}}><svg viewBox="0 0 200 200" className="chart">{values.map((value,index)=>{const fraction=Math.max(0,value)/total,end=start+fraction,large=fraction>.5?1:0,p1=polar(start),p2=polar(end),path=`M100 100 L${p1.x} ${p1.y} A80 80 0 ${large} 1 ${p2.x} ${p2.y} Z`;start=end;return <path key={index} d={path} fill={colorAt(index)} stroke="var(--dashboard-bg)"><title>{labels[index]}: {compact(value)}</title></path>})}{widget.type==="donut_chart"&&<circle cx="100" cy="100" r="42" fill="var(--dashboard-bg)"/>}</svg><div style={{fontSize:9}}>{labels.slice(0,16).map((label,index)=><div key={index}><i style={{display:"inline-block",width:7,height:7,background:colorAt(index),marginRight:4}}/>{label}</div>)}</div></div>};return <svg className="chart" viewBox="0 0 800 320" preserveAspectRatio="none"><line className="axis" x1="54" y1="282" x2="786" y2="282"/><line className="axis" x1="54" y1="16" x2="54" y2="282"/>{values.map((value,index)=>{const width=700/values.length;return <rect key={index} x={60+index*width} y={282-Math.abs(value)/max*250} width={Math.max(2,width-3)} height={Math.abs(value)/max*250} fill={colorAt(index)}><title>{labels[index]}: {compact(value)}</title></rect>})}</svg>}
function polar(fraction:number){const angle=fraction*Math.PI*2-Math.PI/2;return{x:100+80*Math.cos(angle),y:100+80*Math.sin(angle)}}

function DistributionChart({widget,items}:{widget:Widget;items:Distribution[]}){if(!items.length)return <div className="empty">Distribution data was not available at export time.</div>;const series=items.map((item,index)=>({name:item.group||item.name,unit:item.unit,color:colorAt(index),points:item.bins.map((bin,binIndex)=>({captured_at:String(binIndex),value:bin.count}))}));return <Plot widget={widget} series={series}/>}
function Logs({widget}:{widget:Widget}){const stdout=widget.sources.some(item=>item.kind==="log"&&item.name==="stdout")?manifest.sources.logs.stdout:"",stderr=widget.sources.some(item=>item.kind==="log"&&item.name==="stderr")?manifest.sources.logs.stderr:"";if(!stdout&&!stderr)return <div className="empty">Logs were not available at export time.</div>;return <pre className="logs">{stdout}{stderr&&<span className="stderr">{stdout&&"\n"}{stderr}</span>}</pre>}
function ProgressView(){const value=manifest.sources.progress?.global_progress??manifest.sources.progress?.current?.value;if(value==null)return <div className="empty">Progress was not available at export time.</div>;return <div className="gauge"><div style={{width:"80%",textAlign:"center"}}><strong>{Math.round(value*100)}%</strong><div className="gauge-meter"><div className="gauge-fill" style={{width:`${Math.max(0,Math.min(100,value*100))}%`}}/></div></div></div>}
function ScalarView({widget}:{widget:Widget}){const series=numericSeries(widget)[0];if(!series?.points.length)return <div className="empty">Data was not available at export time.</div>;const values=series.points.map(point=>point.value),mode=widget.scalar_aggregation||"last",value=mode==="min"?Math.min(...values):mode==="max"?Math.max(...values):mode==="avg"?values.reduce((a,b)=>a+b,0)/values.length:values.at(-1)!;if(widget.type==="kpi")return <div className="kpi"><div><strong>{compact(value)}</strong><div>{series.name}{series.unit?` · ${series.unit}`:""}</div></div></div>;const maximum=widget.gauge_max_mode==="fixed"&&widget.gauge_max_value?widget.gauge_max_value:Math.max(...values,Math.abs(value),1);return <div className="gauge"><div style={{width:"80%",textAlign:"center"}}><strong>{compact(value)} {series.unit}</strong><div className="gauge-meter"><div className="gauge-fill" style={{width:`${Math.max(0,Math.min(100,value/maximum*100))}%`}}/></div><small>0 — {compact(maximum)}</small></div></div>}
function compact(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3,notation:Math.abs(value)>=10000?"compact":"standard"}).format(value)}
function formatDate(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"medium"}).format(new Date(value))}

createRoot(document.getElementById("root")!).render(<App/>);
