import { useState } from "react";
import { NavLink, Outlet, useLocation } from "react-router-dom";
import { Activity, Boxes, ChevronDown, KeyRound, LayoutDashboard, Menu, Moon, ScrollText, Server, Sun, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { useTheme } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import type { User } from "@/types";
const nav = [{ to: "/", label: "Overview", icon: LayoutDashboard }, { to: "/jobs", label: "Jobs", icon: Boxes }, { to: "/nodes", label: "Nodes", icon: Server }, { to: "/secrets", label: "Secrets", icon: KeyRound }, { to: "/users", label: "Users", icon: Users, admin: true }, { to: "/audit", label: "Audit", icon: ScrollText, admin: true }];
function Navigation({ user, close, collapsed = false }: { user: User; close?: () => void; collapsed?: boolean }) { return <nav className="space-y-1 px-2">{nav.filter((item) => !item.admin || user.role === "admin").map(({ to, label, icon: Icon }) => <NavLink key={to} end={to === "/"} onClick={close} to={to} aria-label={collapsed ? label : undefined} title={collapsed ? label : undefined} className={({ isActive }) => cn("flex h-9 items-center gap-3 overflow-hidden rounded-md px-3 text-sm text-muted-foreground transition-colors hover:bg-accent hover:text-foreground", collapsed && "justify-center group-hover:justify-start", isActive && "bg-accent font-medium text-foreground")}><Icon className="size-4 shrink-0"/><span className={cn(collapsed && "w-0 -translate-x-2 whitespace-nowrap opacity-0 transition-all duration-200 group-hover:w-auto group-hover:translate-x-0 group-hover:opacity-100")}>{label}</span></NavLink>)}</nav>; }
export function AppShell({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [mobile, setMobile] = useState(false), { setTheme } = useTheme(), location = useLocation(), overview = location.pathname === "/";
  return <div className="min-h-screen bg-background"><aside className="group fixed inset-y-0 left-0 z-30 hidden w-16 overflow-hidden border-r bg-background/95 shadow-sm backdrop-blur transition-[width,box-shadow] duration-200 hover:w-56 hover:shadow-xl lg:block"><div className="flex h-14 items-center justify-center overflow-hidden px-3 group-hover:justify-start"><img src="/jobdock-mark.svg" alt="JobDock" className="size-8 shrink-0 dark:hidden"/><img src="/jobdock-mark-dark.svg" alt="" aria-hidden="true" className="hidden size-8 shrink-0 dark:block"/></div><Navigation user={user} collapsed/><div className="absolute inset-x-0 bottom-0 border-t p-2"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" aria-label={`${user.username} account menu`} title={user.username} className="w-full justify-center gap-3 overflow-hidden px-3 group-hover:justify-start"><Users className="size-4 shrink-0"/><span className="w-0 -translate-x-2 truncate opacity-0 transition-all duration-200 group-hover:w-auto group-hover:translate-x-0 group-hover:opacity-100">{user.username}</span><ChevronDown className="ml-auto hidden size-4 shrink-0 group-hover:block"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-48"><DropdownMenuItem onClick={() => setTheme("system")}><Activity className="size-4"/>System theme</DropdownMenuItem><DropdownMenuItem onClick={() => setTheme("light")}><Sun className="size-4"/>Light theme</DropdownMenuItem><DropdownMenuItem onClick={() => setTheme("dark")}><Moon className="size-4"/>Dark theme</DropdownMenuItem><Separator/><DropdownMenuItem onClick={onLogout}>Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></aside>
    <Dialog open={mobile} onOpenChange={setMobile}><DialogContent className="left-0 top-0 h-full max-w-64 translate-x-0 translate-y-0 rounded-none p-2"><DialogTitle className="flex h-12 items-center gap-2 px-3"><Activity className="size-5"/>JobDock</DialogTitle><Navigation user={user} close={() => setMobile(false)}/></DialogContent></Dialog>
    <Button variant="outline" size="icon" className="fixed left-3 top-3 z-40 rounded-full bg-background/90 shadow-md backdrop-blur lg:hidden" onClick={() => setMobile(true)}><Menu className="size-5"/><span className="sr-only">Open navigation</span></Button>
    <div className="lg:pl-16"><main className={cn(overview ? "h-dvh max-w-none overflow-hidden p-0" : "mx-auto max-w-[1500px] p-4 pt-16 lg:p-6")}><Outlet/></main></div></div>;
}
