import {useEffect,useMemo,useState,type ReactNode} from "react";
import {Button} from "@/components/ui/button";
import type {MatrixObservation} from "@/types";

export function ConfusionMatrixWidget({matrix,actions,initialMode="absolute"}:{matrix:MatrixObservation;actions?:ReactNode;initialMode?:"absolute"|"normalized"}){
  const [normalized,setNormalized]=useState(initialMode==="normalized");
  useEffect(()=>setNormalized(initialMode==="normalized"),[initialMode,matrix.name]);
  const values=useMemo(()=>normalized?matrix.values.map(row=>{const total=row.reduce((sum,value)=>sum+value,0);return row.map(value=>total?value/total:0)}):matrix.values,[matrix.values,normalized]);
  const maximum=Math.max(1,...values.flat());
  return <section className="flex h-full min-h-0 min-w-0 flex-col overflow-hidden rounded-md border bg-card p-3"><div className="mb-2 flex h-7 items-center"><div><h3 className="text-sm font-medium">{matrix.name}</h3><p className="text-[10px] text-muted-foreground">{matrix.labels.length} classes{matrix.step!=null?` · step ${matrix.step}`:""}</p></div><div className="ml-auto flex items-center"><div className="flex rounded border p-px"><Button size="sm" variant={!normalized?"secondary":"ghost"} className="h-5 px-2 text-[10px]" onClick={()=>setNormalized(false)}>Absolute</Button><Button size="sm" variant={normalized?"secondary":"ghost"} className="h-5 px-2 text-[10px]" onClick={()=>setNormalized(true)}>Normalized</Button></div>{actions}</div></div><div className="min-h-0 flex-1 overflow-auto"><table className="border-separate border-spacing-0 text-[10px]"><thead><tr><th className="sticky left-0 top-0 z-20 bg-card p-1">Actual \ Predicted</th>{matrix.labels.map(label=><th key={label} title={label} className="sticky top-0 z-10 max-w-20 truncate bg-card p-1 font-normal text-muted-foreground">{label}</th>)}</tr></thead><tbody>{values.map((row,rowIndex)=><tr key={matrix.labels[rowIndex]}><th title={matrix.labels[rowIndex]} className="sticky left-0 max-w-24 truncate bg-card p-1 text-right font-normal text-muted-foreground">{matrix.labels[rowIndex]}</th>{row.map((value,columnIndex)=><td key={columnIndex} title={`${matrix.labels[rowIndex]} → ${matrix.labels[columnIndex]}: ${normalized?(value*100).toFixed(2)+"%":value}`} className="h-7 min-w-8 border border-background/30 text-center" style={{backgroundColor:`color-mix(in srgb, var(--primary) ${Math.max(4,value/maximum*100)}%, transparent)`,color:value/maximum>.55?"var(--primary-foreground)":"var(--foreground)"}}>{normalized?(value*100).toFixed(0)+"%":new Intl.NumberFormat().format(value)}</td>)}</tr>)}</tbody></table></div></section>;
}
