import {useEffect,useMemo,useRef,useState,type ReactNode} from "react";
import {Button} from "@/components/ui/button";
import type {MatrixObservation} from "@/types";

export function ConfusionMatrixWidget({matrix,actions,initialMode="absolute"}:{matrix:MatrixObservation;actions?:ReactNode;initialMode?:"absolute"|"normalized"}){
  const [normalized,setNormalized]=useState(initialMode==="normalized"),host=useRef<HTMLDivElement>(null),[viewport,setViewport]=useState({width:640,height:320});
  useEffect(()=>setNormalized(initialMode==="normalized"),[initialMode,matrix.name]);
  useEffect(()=>{const element=host.current;if(!element||typeof ResizeObserver==="undefined")return;const resize=()=>{const bounds=element.getBoundingClientRect();setViewport({width:bounds.width,height:bounds.height})};resize();const observer=new ResizeObserver(resize);observer.observe(element);return()=>observer.disconnect()},[]);
  const labels=matrix.labels??matrix.row_labels??[],absolute=useMemo(()=>matrix.values.map(row=>row.map(value=>value??0)),[matrix.values]),values=useMemo(()=>normalized?absolute.map(row=>{const total=row.reduce((sum,value)=>sum+value,0);return row.map(value=>total?value/total:0)}):absolute,[absolute,normalized]),maximum=Math.max(1,...values.flat()),labelWidth=Math.min(150,Math.max(70,...labels.map(label=>label.length*7))),headerHeight=32,cell=Math.max(30,Math.min(120,(viewport.width-labelWidth-12)/Math.max(1,labels.length),(viewport.height-headerHeight-12)/Math.max(1,labels.length))),matrixWidth=labelWidth+cell*labels.length,matrixHeight=headerHeight+cell*labels.length;
  return <section className="flex h-full min-h-0 min-w-0 flex-col overflow-hidden rounded-md border bg-card p-3"><div className="mb-2 flex h-7 shrink-0 items-center"><div className="min-w-0"><h3 className="truncate text-sm font-medium">{matrix.name}</h3><p className="text-[10px] text-muted-foreground">{labels.length} classes{matrix.step!=null?` · step ${matrix.step}`:""}</p></div><div className="ml-auto flex items-center"><div className="flex rounded border p-px"><Button size="sm" variant={!normalized?"secondary":"ghost"} className="h-5 px-2 text-[10px]" onClick={()=>setNormalized(false)}>Absolute</Button><Button size="sm" variant={normalized?"secondary":"ghost"} className="h-5 px-2 text-[10px]" onClick={()=>setNormalized(true)}>Normalized</Button></div>{actions}</div></div><div ref={host} className="grid min-h-0 flex-1 place-items-center overflow-auto"><div role="grid" aria-label={`${matrix.name} confusion matrix`} className="grid" style={{width:matrixWidth,height:matrixHeight,gridTemplateColumns:`${labelWidth}px repeat(${labels.length}, ${cell}px)`,gridTemplateRows:`${headerHeight}px repeat(${labels.length}, ${cell}px)`}}><div className="grid place-items-center px-2 text-[10px] font-semibold">Actual ↓ · Predicted →</div>{labels.map(label=><div key={`column-${label}`} role="columnheader" title={label} className="grid place-items-center truncate px-1 text-[10px] text-muted-foreground">{label}</div>)}{values.flatMap((row,rowIndex)=>[<div key={`row-${rowIndex}`} role="rowheader" title={labels[rowIndex]} className="grid place-items-center truncate px-2 text-right text-[10px] text-muted-foreground">{labels[rowIndex]}</div>,...row.map((value,columnIndex)=><div key={`${rowIndex}-${columnIndex}`} role="gridcell" aria-label={`${labels[rowIndex]} predicted as ${labels[columnIndex]}: ${normalized?(value*100).toFixed(2)+"%":value}`} title={`${labels[rowIndex]} → ${labels[columnIndex]}: ${normalized?(value*100).toFixed(2)+"%":value}`} className="grid place-items-center border border-background/40 text-xs tabular-nums" style={{backgroundColor:`color-mix(in srgb, var(--primary) ${Math.max(4,value/maximum*100)}%, transparent)`,color:value/maximum>.55?"var(--primary-foreground)":"var(--foreground)"}}>{normalized?(value*100).toFixed(cell<48?0:1)+"%":new Intl.NumberFormat().format(value)}</div>)])}</div></div></section>;
}
