import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Check, CheckCircle2, CircleAlert, LayoutTemplate, RotateCcw, Search, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/api";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { cn } from "@/lib/utils";
import type { DashboardCompatibility, DashboardTemplate, DashboardTemplateCategory, DashboardTemplateMaterialization, DashboardTemplateMatch, DashboardTemplateOverride, DashboardTemplateReference, DashboardTemplateResolution, DashboardTemplateSlot, DashboardWidget, DashboardWidgetSource } from "@/lib/dashboard-widgets";

type Props={open:boolean;onOpenChange:(open:boolean)=>void;jobID:string;attemptID:string;mode?:"apply"|"create";currentWidgets?:DashboardWidget[];currentMaterialization?:DashboardTemplateMaterialization|null;onApply?:(widgets:DashboardWidget[],materializedFrom:DashboardTemplateReference|null)=>Promise<void>;onCreate?:(name:string,widgets:DashboardWidget[],materializedFrom:DashboardTemplateReference)=>Promise<void>};

export function DashboardTemplatePicker({open,onOpenChange,jobID,attemptID,mode="apply",currentWidgets=[],currentMaterialization=null,onApply,onCreate}:Props){
  const [templateID,setTemplateID]=useState(""),[overrides,setOverrides]=useState<DashboardTemplateOverride[]>([]),[confirming,setConfirming]=useState(false),[applying,setApplying]=useState(false),[search,setSearch]=useState(""),[category,setCategory]=useState<"all"|DashboardTemplateCategory>("all"),[applicableOnly,setApplicableOnly]=useState(false),[previousDashboard,setPreviousDashboard]=useState<{widgets:DashboardWidget[];materializedFrom:DashboardTemplateReference|null}|null>(null),[dashboardName,setDashboardName]=useState("");
  const catalog=useQuery({queryKey:["dashboard-templates"],queryFn:api.dashboardTemplates,enabled:open,staleTime:Infinity});
  const matches=useQuery({queryKey:["dashboard-template-matches",jobID,attemptID],queryFn:()=>api.dashboardTemplateMatches(jobID,attemptID),enabled:open&&!!attemptID,retry:false}),matchByID=useMemo(()=>new Map((matches.data??[]).map(item=>[item.template_id,item])),[matches.data]);
  const visible=useMemo(()=>{const query=search.trim().toLowerCase();return(catalog.data??[]).filter(item=>(category==="all"||(item.category??"general")===category)&&(!applicableOnly||matchByID.get(item.id)?.applicable===true)&&(!query||`${item.name??item.id} ${item.description??""}`.toLowerCase().includes(query))).sort((a,b)=>Number(matchByID.get(b.id)?.applicable??false)-Number(matchByID.get(a.id)?.applicable??false)||(a.name??a.id).localeCompare(b.name??b.id))},[catalog.data,category,applicableOnly,matchByID,search]);
  useEffect(()=>{if(!open||!catalog.data?.length)return;if(!visible.some(item=>item.id===templateID)){const firstApplicable=visible.find(item=>matchByID.get(item.id)?.applicable);setTemplateID((firstApplicable??visible[0]??catalog.data[0]).id)}},[open,catalog.data,visible,templateID,matchByID]);
  const template=catalog.data?.find(item=>item.id===templateID);
  useEffect(()=>setOverrides([]),[templateID,attemptID]);
  useEffect(()=>{if(mode==="create"&&template)setDashboardName((template.name??template.id).slice(0,128))},[mode,templateID,template]);
  const resolution=useQuery({queryKey:["dashboard-template-resolution",jobID,attemptID,templateID,overrides],queryFn:()=>api.resolveDashboardTemplate(jobID,template!,attemptID,overrides),enabled:open&&!!template&&!!attemptID,retry:false});
  const slots=useMemo(()=>new Map((template?.widgets??[]).flatMap(widget=>widget.slots.map(slot=>[`${widget.id}:${slot.id}`,slot] as const))),[template]);
  const blocking=!resolution.data||resolution.data.compatibility==="incompatible"||resolution.data.widget_results.some(item=>item.status==="unresolved");
  const restore=async(dashboard=previousDashboard)=>{if(!dashboard||!onApply)return;setApplying(true);try{await onApply(dashboard.widgets,dashboard.materializedFrom);setPreviousDashboard(null);toast.success("Previous dashboard restored")}catch(error){toast.error("Dashboard could not be restored",{description:(error as Error).message})}finally{setApplying(false)}};
  const apply=async()=>{if(!resolution.data||blocking||!template)return;const reference={template_id:template.id,template_version:template.version,schema_version:template.schema_version};setApplying(true);try{if(mode==="create"){if(!onCreate||!dashboardName.trim())return;await onCreate(dashboardName.trim(),resolution.data.widgets,reference);onOpenChange(false);toast.success("Dashboard created",{description:`Created from ${template.name??template.id} v${template.version}.`})}else{if(!onApply)return;const backup={widgets:structuredClone(currentWidgets),materializedFrom:currentMaterialization?{template_id:currentMaterialization.template_id,template_version:currentMaterialization.template_version,schema_version:currentMaterialization.schema_version}:null};await onApply(resolution.data.widgets,reference);setPreviousDashboard(backup);setConfirming(false);onOpenChange(false);toast.success("Dashboard template applied",{description:`${template.name??template.id} v${template.version} was materialized as an editable dashboard.`,action:{label:"Restore",onClick:()=>void restore(backup)}})}}catch(error){toast.error(mode==="create"?"Dashboard could not be created":"Template could not be applied",{description:(error as Error).message})}finally{setApplying(false)}};
  const choose=(widgetID:string,slotID:string,source:DashboardWidgetSource)=>setOverrides(current=>[...current.filter(item=>item.widget_id!==widgetID||item.slot_id!==slotID),{widget_id:widgetID,slot_id:slotID,sources:[{kind:source.kind,name:source.name}]}]);
  return <><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="flex h-[92dvh] max-h-[92dvh] w-[96vw] max-w-[96vw] flex-col overflow-hidden"><DialogHeader className="sr-only"><DialogTitle>{mode==="create"?"Create dashboard from template":"Dashboard templates"}</DialogTitle><DialogDescription>Choose a semantic dashboard template.</DialogDescription></DialogHeader>
    {catalog.isError?<TemplateError message="The template catalog could not be loaded."/>:<div className="grid min-h-0 flex-1 grid-rows-[minmax(12rem,35%)_minmax(0,1fr)] gap-4 overflow-hidden lg:grid-cols-[22rem_minmax(0,1fr)] lg:grid-rows-1"><TemplateSidebar templates={visible} selected={templateID} matches={matchByID} search={search} category={category} applicableOnly={applicableOnly} loadingMatches={matches.isLoading} onSearch={setSearch} onCategory={setCategory} onApplicable={setApplicableOnly} onSelect={setTemplateID}/>
      <main className="min-h-0 overflow-auto pr-1">{template&&<div className="mb-4 border-b pb-3"><div className="flex items-center gap-2"><LayoutTemplate className="size-4 text-primary"/><h2 className="text-base font-semibold">{template.name??template.id}</h2><CompatibilityBadge status={resolution.data?.compatibility??matchByID.get(template.id)?.compatibility??"incompatible"}/></div><p className="mt-1 text-sm text-muted-foreground">{template.description}</p><p className="mt-2 font-mono text-[10px] text-muted-foreground">Template v{template.version} · schema v{template.schema_version}</p>{mode==="create"&&<label className="mt-3 grid max-w-md gap-1 text-xs font-medium text-muted-foreground">Dashboard name<Input aria-label="Dashboard name" maxLength={128} value={dashboardName} onChange={event=>setDashboardName(event.target.value)}/></label>}{currentMaterialization&&<p className="mt-2 text-xs text-muted-foreground">Current origin: {currentMaterialization.template_id} v{currentMaterialization.template_version}</p>}</div>}{resolution.isLoading?<div className="h-64 animate-pulse rounded-md border bg-muted/30"/>:resolution.isError?<TemplateError message={(resolution.error as Error).message}/>:resolution.data&&template?<TemplatePreview template={template} resolution={resolution.data} slots={slots} overrides={overrides} onChoose={choose}/>:null}</main></div>}
    <DialogFooter>{mode==="apply"&&previousDashboard&&<Button variant="outline" className="mr-auto" disabled={applying} onClick={()=>void restore()}><RotateCcw className="size-4"/>Restore previous dashboard</Button>}<Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={!resolution.data||blocking||applying||(mode==="create"&&!dashboardName.trim())} onClick={()=>mode==="apply"&&currentWidgets.length?setConfirming(true):void apply()}><Sparkles className="size-4"/>{mode==="create"?"Create dashboard":"Apply template"}</Button></DialogFooter>
  </DialogContent></Dialog><AlertDialog open={confirming} onOpenChange={setConfirming}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Replace the current dashboard?</AlertDialogTitle><AlertDialogDescription>The current layout will be kept as a restorable backup for this session. The resolved template will become a normal editable dashboard.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep current dashboard</AlertDialogCancel><AlertDialogAction disabled={applying} onClick={event=>{event.preventDefault();void apply()}}>Replace dashboard</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

const categoryLabels:Record<DashboardTemplateCategory,string>={general:"General",classification:"Classification",regression:"Regression","clustering-representation":"Clustering & representation","computer-vision":"Computer vision","nlp-speech":"NLP & speech","generative-ai":"Generative AI","ranking-recommendation":"Ranking & recommendation","time-series-anomaly":"Time series & anomaly detection","reinforcement-learning":"Reinforcement learning","hpo-model-selection":"HPO & model selection"};
function TemplateSidebar({templates,selected,matches,search,category,applicableOnly,loadingMatches,onSearch,onCategory,onApplicable,onSelect}:{templates:DashboardTemplate[];selected:string;matches:Map<string,DashboardTemplateMatch>;search:string;category:"all"|DashboardTemplateCategory;applicableOnly:boolean;loadingMatches:boolean;onSearch:(value:string)=>void;onCategory:(value:"all"|DashboardTemplateCategory)=>void;onApplicable:(value:boolean)=>void;onSelect:(value:string)=>void}){
  const groups=Object.entries(categoryLabels).map(([id,label])=>({id:id as DashboardTemplateCategory,label,items:templates.filter(item=>(item.category??"general")===id)})).filter(group=>group.items.length);
  return <aside className="flex min-h-0 flex-col overflow-hidden rounded-md border bg-muted/10"><div className="space-y-2 border-b p-3"><div className="relative"><Search className="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={event=>onSearch(event.target.value)} placeholder="Search templates" aria-label="Search templates" className="pl-8"/></div><div className="grid grid-cols-[1fr_auto] gap-2"><Select value={category} onValueChange={value=>onCategory(value as "all"|DashboardTemplateCategory)}><SelectTrigger aria-label="Template category"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All types</SelectItem>{Object.entries(categoryLabels).map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select><Button variant={applicableOnly?"secondary":"outline"} aria-pressed={applicableOnly} disabled={loadingMatches} onClick={()=>onApplicable(!applicableOnly)}><CheckCircle2 className="size-4"/>Applicable</Button></div></div><div className="min-h-0 flex-1 overflow-auto p-2">{groups.length?groups.map(group=><section key={group.id} className="mb-4 last:mb-0"><h3 className="mb-1 px-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{group.label}</h3><div className="space-y-1">{group.items.map(item=>{const match=matches.get(item.id);return <button key={item.id} type="button" aria-current={selected===item.id?"true":undefined} onClick={()=>onSelect(item.id)} className={cn("flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-sm transition-colors hover:bg-accent",selected===item.id&&"bg-accent font-medium")}><span className="min-w-0 flex-1 truncate">{item.name??item.id}</span>{match&&<span className={cn("size-2 shrink-0 rounded-full",match.applicable?"bg-emerald-500":match.ambiguous_sources?"bg-amber-500":"bg-muted-foreground/40")} title={match.applicable?"Applicable":match.ambiguous_sources?"Needs source selection":"Unavailable"}/>}</button>})}</div></section>):<p className="p-6 text-center text-sm text-muted-foreground">No templates match these filters.</p>}</div></aside>
}

function TemplatePreview({template,resolution,slots,overrides,onChoose}:{template:DashboardTemplate;resolution:DashboardTemplateResolution;slots:Map<string,DashboardTemplateSlot>;overrides:DashboardTemplateOverride[];onChoose:(widgetID:string,slotID:string,source:DashboardWidgetSource)=>void}){
  const maxRow=Math.max(1,...template.widgets.map(widget=>widget.position.y+widget.size.rows)),statuses=new Map(resolution.widget_results.map(item=>[item.widget_id,item.status]));
  return <div className="space-y-4"><section><div className="mb-2 flex items-center"><h3 className="text-sm font-medium">Layout preview</h3></div>{resolution.fallback_reason&&<p role="alert" className="mb-2 rounded-md border border-destructive/30 bg-destructive/5 p-2 text-xs text-destructive">This template cannot be applied safely: {resolution.fallback_reason.replaceAll("_"," ")}.</p>}<div className="grid min-h-44 grid-cols-12 gap-1 rounded-md border bg-muted/20 p-2" style={{gridTemplateRows:`repeat(${maxRow}, minmax(14px, 1fr))`}}>{template.widgets.map(widget=>{const available=statuses.get(widget.id)!=="unresolved"&&statuses.get(widget.id)!=="omitted";return <div key={widget.id} className={cn("grid min-h-8 place-items-center overflow-hidden rounded border px-1 text-center text-[10px] font-medium",available?"border-primary/30 bg-primary/10":"border-dashed border-muted-foreground/30 bg-muted/40 text-muted-foreground")} style={{gridColumn:`${widget.position.x+1} / span ${widget.size.columns}`,gridRow:`${widget.position.y+1} / span ${widget.size.rows}`}}>{widget.title||widget.id}</div>})}</div></section>
    <section><h3 className="mb-2 text-sm font-medium">Source resolution</h3><div className="divide-y rounded-md border">{resolution.slot_results.map(item=>{const slot=slots.get(`${item.widget_id}:${item.slot_id}`),required=(slot?.cardinality.min??0)>0,override=overrides.find(value=>value.widget_id===item.widget_id&&value.slot_id===item.slot_id),canChoose=item.status==="ambiguous"||!!override;return <div key={`${item.widget_id}:${item.slot_id}`} className="grid gap-2 p-3 sm:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{item.slot_id}</span><Badge variant="outline" className="text-[10px]">{required?"Required":"Optional"}</Badge><ResolutionBadge status={item.status}/></div><p className="mt-1 truncate text-xs text-muted-foreground">{item.selected.length?item.selected.map(source=>source.name).join(", "):item.status==="ambiguous"?`${item.candidates.length} matching sources require a choice`:item.status==="incompatible"?"Matching semantics were found with an incompatible source type":"No matching source reported"}</p></div>{canChoose&&<Select value={override?.sources[0]?sourceKey(override.sources[0]):""} onValueChange={value=>{const source=item.candidates.find(candidate=>sourceKey(candidate)===value);if(source)onChoose(item.widget_id,item.slot_id,source)}}><SelectTrigger className="w-full sm:w-56" aria-label={`Resolve ${item.slot_id}`}><SelectValue placeholder="Choose source"/></SelectTrigger><SelectContent>{item.candidates.map(source=><SelectItem key={sourceKey(source)} value={sourceKey(source)}>{source.name}</SelectItem>)}</SelectContent></Select>}</div>})}</div></section>
  </div>;
}

function ResolutionBadge({status}:{status:DashboardTemplateResolution["slot_results"][number]["status"]}){const resolved=status==="resolved";return <Badge variant="outline" className={cn("gap-1 text-[10px]",resolved?"border-emerald-500/40 text-emerald-600":status==="ambiguous"?"border-amber-500/40 text-amber-600":"border-destructive/40 text-destructive")}>{resolved?<Check className="size-3"/>:<CircleAlert className="size-3"/>}{status}</Badge>}
function CompatibilityBadge({status}:{status:DashboardCompatibility}){return <Badge variant="outline" className={cn("text-[10px]",status==="compatible"?"border-emerald-500/40 text-emerald-600":status==="partially_compatible"?"border-amber-500/40 text-amber-600":"border-destructive/40 text-destructive")}>{status.replaceAll("_"," ")}</Badge>}
function TemplateError({message}:{message:string}){return <div role="alert" className="grid min-h-44 place-items-center rounded-md border border-destructive/30 p-6 text-center text-sm text-destructive">{message}</div>}
function sourceKey(source:{kind:string;name:string}){return `${source.kind}:${source.name}`}
