import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, CircleAlert, LayoutTemplate, RotateCcw, Search, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/api";
import { ObservabilityDashboard, type NumericWidgetSource } from "@/components/observability-dashboard";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { metricPoints, numericSummary, resourcePoints } from "@/lib/series";
import { cn } from "@/lib/utils";
import type { DashboardCompatibility, DashboardTemplate, DashboardTemplateCategory, DashboardTemplateMaterialization, DashboardTemplateMatch, DashboardTemplateOverride, DashboardTemplateReference, DashboardTemplateResolution, DashboardTemplateSlot, DashboardWidget, DashboardWidgetSource } from "@/lib/dashboard-widgets";
import type { DistributionObservation, MatrixObservation, ObservableSourceDescriptor, ProgressState, ResourcePoint } from "@/types";

type Props={open:boolean;onOpenChange:(open:boolean)=>void;jobID:string;attemptID:string;mode?:"apply"|"create";currentWidgets?:DashboardWidget[];currentMaterialization?:DashboardTemplateMaterialization|null;onApply?:(widgets:DashboardWidget[],materializedFrom:DashboardTemplateReference|null)=>Promise<void>;onCreate?:(name:string,widgets:DashboardWidget[],materializedFrom:DashboardTemplateReference)=>Promise<void>};

export function DashboardTemplatePicker({open,onOpenChange,jobID,attemptID,mode="apply",currentWidgets=[],currentMaterialization=null,onApply,onCreate}:Props){
  const [templateID,setTemplateID]=useState(""),[overrides,setOverrides]=useState<DashboardTemplateOverride[]>([]),[confirming,setConfirming]=useState(false),[applying,setApplying]=useState(false),[search,setSearch]=useState(""),[category,setCategory]=useState<"all"|DashboardTemplateCategory>("all"),[applicableOnly,setApplicableOnly]=useState(false),[previousDashboard,setPreviousDashboard]=useState<{widgets:DashboardWidget[];materializedFrom:DashboardTemplateReference|null}|null>(null),[dashboardName,setDashboardName]=useState("");
  const catalog=useQuery({queryKey:["dashboard-templates"],queryFn:api.dashboardTemplates,enabled:open,staleTime:Infinity});
  const matches=useQuery({queryKey:["dashboard-template-matches",jobID,attemptID],queryFn:()=>api.dashboardTemplateMatches(jobID,attemptID),enabled:open&&!!attemptID,retry:false}),matchByID=useMemo(()=>new Map((matches.data??[]).map(item=>[item.template_id,item])),[matches.data]);
  const visible=useMemo(()=>{const query=search.trim().toLowerCase();return(catalog.data??[]).filter(item=>(category==="all"||(item.category??"general")===category)&&(!applicableOnly||matchByID.get(item.id)?.applicable===true)&&(!query||`${item.name??item.id} ${item.description??""}`.toLowerCase().includes(query))).sort((a,b)=>Number(matchByID.get(b.id)?.applicable??false)-Number(matchByID.get(a.id)?.applicable??false)||(a.name??a.id).localeCompare(b.name??b.id))},[catalog.data,category,applicableOnly,matchByID,search]);
  useEffect(()=>{if(!open||!catalog.data?.length)return;if(!visible.some(item=>item.id===templateID)){const firstApplicable=visible.find(item=>matchByID.get(item.id)?.applicable);setTemplateID((firstApplicable??visible[0]??catalog.data[0]).id)}},[open,catalog.data,visible,templateID,matchByID]);
  const template=catalog.data?.find(item=>item.id===templateID);
  useEffect(()=>setOverrides([]),[templateID,attemptID]);
  useEffect(()=>{if(mode==="create"&&template)setDashboardName((template.name??template.id).slice(0,128))},[mode,templateID,template]);
  const resolution=useQuery({queryKey:["dashboard-template-resolution",jobID,attemptID,templateID,overrides],queryFn:()=>api.resolveDashboardTemplate(jobID,template!,attemptID,overrides),enabled:open&&!!template&&!!attemptID,retry:false});
  const slots=useMemo(()=>new Map((template?.widgets??[]).flatMap(widget=>widget.slots.map(slot=>[`${widget.id}:${slot.id}`,slot] as const))),[template]);
  const blocking=!resolution.data||resolution.data.compatibility==="incompatible"||(resolution.data.widgets??[]).length===0||(resolution.data.widget_results??[]).some(item=>item.status==="unresolved");
  const restore=async(dashboard=previousDashboard)=>{if(!dashboard||!onApply)return;setApplying(true);try{await onApply(dashboard.widgets,dashboard.materializedFrom);setPreviousDashboard(null);toast.success("Previous dashboard restored")}catch(error){toast.error("Dashboard could not be restored",{description:(error as Error).message})}finally{setApplying(false)}};
  const apply=async()=>{if(!resolution.data||blocking||!template)return;const widgets=resolution.data.widgets??[],reference={template_id:template.id,template_version:template.version,schema_version:template.schema_version};setApplying(true);try{if(mode==="create"){if(!onCreate||!dashboardName.trim())return;await onCreate(dashboardName.trim(),widgets,reference);onOpenChange(false);toast.success("Dashboard created",{description:`Created from ${template.name??template.id} v${template.version}.`})}else{if(!onApply)return;const backup={widgets:structuredClone(currentWidgets),materializedFrom:currentMaterialization?{template_id:currentMaterialization.template_id,template_version:currentMaterialization.template_version,schema_version:currentMaterialization.schema_version}:null};await onApply(widgets,reference);setPreviousDashboard(backup);setConfirming(false);onOpenChange(false);toast.success("Dashboard template applied",{description:`${template.name??template.id} v${template.version} was materialized as an editable dashboard.`,action:{label:"Restore",onClick:()=>void restore(backup)}})}}catch(error){toast.error(mode==="create"?"Dashboard could not be created":"Template could not be applied",{description:(error as Error).message})}finally{setApplying(false)}};
  const choose=(widgetID:string,slotID:string,source:DashboardWidgetSource)=>setOverrides(current=>[...current.filter(item=>item.widget_id!==widgetID||item.slot_id!==slotID),{widget_id:widgetID,slot_id:slotID,sources:[{kind:source.kind,name:source.name}]}]);
  return <><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="flex h-[92dvh] max-h-[92dvh] w-[96vw] max-w-[96vw] flex-col overflow-hidden"><DialogHeader className="sr-only"><DialogTitle>{mode==="create"?"Create dashboard from template":"Dashboard templates"}</DialogTitle><DialogDescription>Choose a semantic dashboard template.</DialogDescription></DialogHeader>
    {catalog.isError?<TemplateError message="The template catalog could not be loaded."/>:<div className="grid min-h-0 flex-1 grid-rows-[minmax(12rem,35%)_minmax(0,1fr)] gap-4 overflow-hidden lg:grid-cols-[22rem_minmax(0,1fr)] lg:grid-rows-1"><TemplateSidebar templates={visible} selected={templateID} matches={matchByID} search={search} category={category} applicableOnly={applicableOnly} loadingMatches={matches.isLoading} onSearch={setSearch} onCategory={setCategory} onApplicable={setApplicableOnly} onSelect={setTemplateID}/>
      <main className="flex min-h-0 flex-col overflow-hidden pr-1">{template&&<div className="mb-3 shrink-0 border-b pb-3"><div className="flex items-center gap-2"><LayoutTemplate className="size-4 text-primary"/><h2 className="text-base font-semibold">{template.name??template.id}</h2><CompatibilityBadge status={resolution.data?.compatibility??matchByID.get(template.id)?.compatibility??"incompatible"}/></div><p className="mt-1 text-sm text-muted-foreground">{template.description}</p><p className="mt-2 font-mono text-[10px] text-muted-foreground">Template v{template.version} · schema v{template.schema_version}</p>{mode==="create"&&<label className="mt-3 grid max-w-md gap-1 text-xs font-medium text-muted-foreground">Dashboard name<Input aria-label="Dashboard name" maxLength={128} value={dashboardName} onChange={event=>setDashboardName(event.target.value)}/></label>}{currentMaterialization&&<p className="mt-2 text-xs text-muted-foreground">Current origin: {currentMaterialization.template_id} v{currentMaterialization.template_version}</p>}</div>}{resolution.isLoading?<div className="min-h-0 flex-1 animate-pulse rounded-md border bg-muted/30"/>:resolution.isError?<TemplateError message={(resolution.error as Error).message}/>:resolution.data&&template?<TemplatePreview jobID={jobID} attemptID={attemptID} template={template} resolution={resolution.data} slots={slots} overrides={overrides} onChoose={choose}/>:null}</main></div>}
    <DialogFooter>{mode==="apply"&&previousDashboard&&<Button variant="outline" className="mr-auto" disabled={applying} onClick={()=>void restore()}><RotateCcw className="size-4"/>Restore previous dashboard</Button>}<Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={!resolution.data||blocking||applying||(mode==="create"&&!dashboardName.trim())} onClick={()=>mode==="apply"&&currentWidgets.length?setConfirming(true):void apply()}><Sparkles className="size-4"/>{mode==="create"?"Create dashboard":"Apply template"}</Button></DialogFooter>
  </DialogContent></Dialog><AlertDialog open={confirming} onOpenChange={setConfirming}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Replace the current dashboard?</AlertDialogTitle><AlertDialogDescription>The current layout will be kept as a restorable backup for this session. The resolved template will become a normal editable dashboard.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep current dashboard</AlertDialogCancel><AlertDialogAction disabled={applying} onClick={event=>{event.preventDefault();void apply()}}>Replace dashboard</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

const categoryLabels:Record<DashboardTemplateCategory,string>={general:"General",classification:"Classification",regression:"Regression","clustering-representation":"Clustering & representation","computer-vision":"Computer vision","nlp-speech":"NLP & speech","generative-ai":"Generative AI","ranking-recommendation":"Ranking & recommendation","time-series-anomaly":"Time series & anomaly detection","reinforcement-learning":"Reinforcement learning","hpo-model-selection":"HPO & model selection"};
function TemplateSidebar({templates,selected,matches,search,category,applicableOnly,loadingMatches,onSearch,onCategory,onApplicable,onSelect}:{templates:DashboardTemplate[];selected:string;matches:Map<string,DashboardTemplateMatch>;search:string;category:"all"|DashboardTemplateCategory;applicableOnly:boolean;loadingMatches:boolean;onSearch:(value:string)=>void;onCategory:(value:"all"|DashboardTemplateCategory)=>void;onApplicable:(value:boolean)=>void;onSelect:(value:string)=>void}){
  const groups=Object.entries(categoryLabels).map(([id,label])=>({id:id as DashboardTemplateCategory,label,items:templates.filter(item=>(item.category??"general")===id)})).filter(group=>group.items.length);
  return <aside className="flex min-h-0 flex-col overflow-hidden rounded-md border bg-muted/10"><div className="space-y-2 border-b p-3"><div className="relative"><Search className="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={event=>onSearch(event.target.value)} placeholder="Search templates" aria-label="Search templates" className="pl-8"/></div><div className="grid grid-cols-[1fr_auto] gap-2"><Select value={category} onValueChange={value=>onCategory(value as "all"|DashboardTemplateCategory)}><SelectTrigger aria-label="Template category"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All types</SelectItem>{Object.entries(categoryLabels).map(([id,label])=><SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select><Button variant={applicableOnly?"secondary":"outline"} aria-pressed={applicableOnly} disabled={loadingMatches} onClick={()=>onApplicable(!applicableOnly)}><CheckCircle2 className="size-4"/>Applicable</Button></div></div><div className="min-h-0 flex-1 overflow-auto p-2">{groups.length?groups.map(group=><section key={group.id} className="mb-4 last:mb-0"><h3 className="mb-1 px-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{group.label}</h3><div className="space-y-1">{group.items.map(item=>{const match=matches.get(item.id);return <button key={item.id} type="button" aria-current={selected===item.id?"true":undefined} onClick={()=>onSelect(item.id)} className={cn("flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-sm transition-colors hover:bg-accent",selected===item.id&&"bg-accent font-medium")}><span className="min-w-0 flex-1 truncate">{item.name??item.id}</span>{match&&<span className={cn("size-2 shrink-0 rounded-full",match.applicable?"bg-emerald-500":match.ambiguous_sources?"bg-amber-500":"bg-muted-foreground/40")} title={match.applicable?"Applicable":match.ambiguous_sources?"Needs source selection":"Unavailable"}/>}</button>})}</div></section>):<p className="p-6 text-center text-sm text-muted-foreground">No templates match these filters.</p>}</div></aside>
}

function TemplatePreview({jobID,attemptID,template,resolution,slots,overrides,onChoose}:{jobID:string;attemptID:string;template:DashboardTemplate;resolution:DashboardTemplateResolution;slots:Map<string,DashboardTemplateSlot>;overrides:DashboardTemplateOverride[];onChoose:(widgetID:string,slotID:string,source:DashboardWidgetSource)=>void}){
  const metricCatalog=useQuery({queryKey:["job-metric-catalog",jobID,attemptID],queryFn:()=>api.metricCatalog(jobID,attemptID),staleTime:30_000,retry:false});
  const observableCatalog=useQuery({queryKey:["job-observability-catalog",jobID,attemptID],queryFn:()=>api.observabilityCatalog(jobID,attemptID),staleTime:30_000,retry:false});
  const query=useMemo(()=>new URLSearchParams({attempt_id:attemptID,resolution:"auto",limit:"500"}).toString(),[attemptID]);
  const metrics=useQuery({queryKey:["job-metrics",jobID,query],queryFn:()=>api.metrics(jobID,query),staleTime:30_000,retry:false});
  const resources=useQuery({queryKey:["job-resources",jobID,query],queryFn:()=>api.resources(jobID,query),staleTime:30_000,retry:false});
  const progress=useQuery({queryKey:["job-progress",jobID,attemptID],queryFn:()=>api.progress(jobID,attemptID),staleTime:30_000,retry:false});
  const matrices=useQuery({queryKey:["job-matrices",jobID,attemptID],queryFn:()=>api.matrices(jobID,attemptID),staleTime:30_000,retry:false});
  const distributions=useQuery({queryKey:["job-distributions",jobID,attemptID,0],queryFn:()=>api.distributions(jobID,attemptID),staleTime:30_000,retry:false});
  const previewWidgets=useMemo(()=>materializePreviewWidgets(template,resolution,slots,overrides),[template,resolution,slots,overrides]);
  const telemetry=useMemo(()=>templatePreviewTelemetry(previewWidgets.map(item=>item.widget),metricCatalog.data??[],observableCatalog.data?.items??[],metrics.data,resources.data,progress.data,matrices.data??[],distributions.data??[]),[previewWidgets,metricCatalog.data,observableCatalog.data,metrics.data,resources.data,progress.data,matrices.data,distributions.data]);
  const maxRow=Math.max(1,...template.widgets.map(widget=>widget.position.y+widget.size.rows));
  return <div className="flex min-h-0 flex-1 flex-col">{resolution.fallback_reason&&<p role="alert" className="mb-2 shrink-0 rounded-md border border-destructive/30 bg-destructive/5 p-2 text-xs text-destructive">This template cannot be applied safely: {resolution.fallback_reason.replaceAll("_"," ")}.</p>}<div aria-label="Template dashboard preview" className="grid min-h-0 flex-1 grid-cols-12 gap-1.5 overflow-hidden rounded-md bg-muted/20 p-2" style={{gridTemplateRows:`repeat(${maxRow}, minmax(0, 1fr))`}}>{previewWidgets.map(({definition,widget,issues})=>{
    const sample=widget.sources.some(source=>!hasActualPreviewData(source,metrics.data,resources.data,progress.data,matrices.data??[],distributions.data??[],observableCatalog.data?.items??[])),tableWithoutData=widget.sources.some(source=>source.kind==="table"&&!hasActualPreviewData(source,metrics.data,resources.data,progress.data,matrices.data??[],distributions.data??[],observableCatalog.data?.items??[]));
    return <section key={definition.id} aria-label={`${definition.title||definition.id} preview`} className={cn("relative min-h-0 min-w-0 overflow-hidden rounded-md bg-background/80 shadow-sm",issues.some(item=>item.status==="ambiguous")&&"ring-1 ring-amber-500/50",issues.some(item=>item.status==="missing"||item.status==="incompatible")&&"ring-1 ring-destructive/40")} style={{gridColumn:`${definition.position.x+1} / span ${definition.size.columns}`,gridRow:`${definition.position.y+1} / span ${definition.size.rows}`}}>
      <div className="pointer-events-none h-full min-h-0">{tableWithoutData?<DummyWidgetSurface type={widget.type}/>:<ObservabilityDashboard key={`${template.id}:${widget.id}:${widget.sources.map(sourceKey).join("|")}`} jobID={jobID} attemptID={attemptID} ready numericSources={telemetry.numericSources} observableSources={telemetry.observableSources} progress={telemetry.progress} matrices={telemetry.matrices} distributions={telemetry.distributions} markers={[]} initialWidgets={[widget]}/>}</div>
      <Badge variant="secondary" className={cn("pointer-events-none absolute right-2 top-2 z-20 bg-background/90 text-[9px] shadow-sm",!sample&&"border-emerald-500/30 text-emerald-600")}>{sample?"Sample data":"Live data"}</Badge>
      {issues.length>0&&<TemplateIssuesOverlay definition={definition} issues={issues} slots={slots} overrides={overrides} onChoose={onChoose}/>}
    </section>})}</div></div>;
}

function TemplateIssuesOverlay({definition,issues,slots,overrides,onChoose}:{definition:DashboardTemplate["widgets"][number];issues:DashboardTemplateResolution["slot_results"];slots:Map<string,DashboardTemplateSlot>;overrides:DashboardTemplateOverride[];onChoose:(widgetID:string,slotID:string,source:DashboardWidgetSource)=>void}){
  const ambiguous=issues.filter(item=>item.status==="ambiguous"),unavailable=issues.filter(item=>item.status!=="ambiguous"),required=unavailable.filter(item=>(slots.get(`${item.widget_id}:${item.slot_id}`)?.cardinality.min??0)>0),optional=unavailable.filter(item=>(slots.get(`${item.widget_id}:${item.slot_id}`)?.cardinality.min??0)===0);
  return <div className="absolute inset-x-2 bottom-2 z-30 space-y-1.5">{ambiguous.map(item=>{const slot=slots.get(`${item.widget_id}:${item.slot_id}`),isRequired=(slot?.cardinality.min??0)>0,override=overrides.find(value=>value.widget_id===item.widget_id&&value.slot_id===item.slot_id);return <div key={item.slot_id} className="rounded-md border border-amber-500/40 bg-background/95 p-2 shadow-lg backdrop-blur-md"><div className="flex items-center gap-1.5 text-[10px] font-medium"><CircleAlert className="size-3 text-amber-500"/><span className="truncate">{item.slot_id}</span><span className="text-muted-foreground">· {isRequired?"Required":"Optional"}</span></div><Select value={override?.sources[0]?sourceKey(override.sources[0]):""} onValueChange={value=>{const source=item.candidates.find(candidate=>sourceKey(candidate)===value);if(source)onChoose(item.widget_id,item.slot_id,source)}}><SelectTrigger className="mt-1 h-7 w-full text-[10px]" aria-label={`Choose source for ${definition.title||definition.id}, ${item.slot_id}`}><SelectValue placeholder={`${item.candidates.length} matches · choose source`}/></SelectTrigger><SelectContent>{item.candidates.map(source=><SelectItem key={sourceKey(source)} value={sourceKey(source)}>{source.name}</SelectItem>)}</SelectContent></Select></div>})}{unavailable.length>0&&<div className="flex flex-wrap items-center gap-x-3 gap-y-1 rounded-md border border-destructive/40 bg-background/95 px-2 py-1.5 text-[10px] shadow-lg backdrop-blur-md"><CircleAlert className="size-3 shrink-0 text-destructive"/>{required.length>0&&<span className="font-medium" title={required.map(item=>item.slot_id).join(", ")}>Missing required: {compactSlotNames(required)}</span>}{optional.length>0&&<span className="text-muted-foreground" title={optional.map(item=>item.slot_id).join(", ")}>{optional.length===1?`Optional source unavailable: ${optional[0].slot_id}`:`${optional.length} optional sources unavailable`}</span>}</div>}</div>;
}
function compactSlotNames(items:DashboardTemplateResolution["slot_results"]){const names=items.map(item=>item.slot_id);return names.length<=2?names.join(", "):`${names.slice(0,2).join(", ")} +${names.length-2}`}

type PreviewWidget={definition:DashboardTemplate["widgets"][number];widget:DashboardWidget;issues:DashboardTemplateResolution["slot_results"]};
function materializePreviewWidgets(template:DashboardTemplate,resolution:DashboardTemplateResolution,slots:Map<string,DashboardTemplateSlot>,overrides:DashboardTemplateOverride[]):PreviewWidget[]{
  const resolved=new Map((resolution.widgets??[]).map(widget=>[widget.id,widget])),results=resolution.slot_results??[];
  return template.widgets.map(definition=>{const slotResults=results.filter(item=>item.widget_id===definition.id),issues=slotResults.filter(item=>item.status!=="resolved"),materialized=resolved.get(definition.id),slotSources=slotResults.flatMap(item=>{const override=overrides.find(value=>value.widget_id===item.widget_id&&value.slot_id===item.slot_id);if(override?.sources.length)return override.sources.map(source=>({...source,role:slots.get(`${item.widget_id}:${item.slot_id}`)?.role}));if(item.selected?.length)return item.selected.map(source=>({...source,role:slots.get(`${item.widget_id}:${item.slot_id}`)?.role}));const slot=slots.get(`${item.widget_id}:${item.slot_id}`);return slot?[dummySource(definition.id,slot)]:[]}),sources=[...(materialized?.sources??[])];for(const source of slotSources)if(!sources.some(item=>item.kind===source.kind&&item.name===source.name&&item.role===source.role))sources.push(source);const {slots:_slots,...base}=definition;return{definition,issues,widget:{...base,...materialized,sources,size:{columns:12,rows:12},position:{x:0,y:0}}}});
}

function dummySource(widgetID:string,slot:DashboardTemplateSlot):DashboardWidgetSource{const kind=slot.source_types[0]??"metric";return{kind,name:kind==="log"?"stdout":kind==="progress"?"progress":`__preview_${widgetID}_${slot.id}`,role:slot.role}}
function templatePreviewTelemetry(widgets:DashboardWidget[],metricCatalog:ObservableSourceDescriptor[],observableCatalog:ObservableSourceDescriptor[],metricResponse:Awaited<ReturnType<typeof api.metrics>>|undefined,resourceResponse:Awaited<ReturnType<typeof api.resources>>|undefined,progress:ProgressState|undefined,matrices:MatrixObservation[],distributions:DistributionObservation[]){
  const numericSources:NumericWidgetSource[]=[];
  for(const descriptor of metricCatalog){const series=metricResponse?.series.find(item=>item.name===descriptor.name),points=series?metricPoints(series.points):[];numericSources.push({kind:"metric",name:descriptor.name,title:descriptor.name,unit:series?.unit||descriptor.unit||"unitless",points:points.length?points:dummyPoints(),summary:series?{last:series.last,min:series.min,max:series.max,avg:series.avg??series.last}:numericSummary(dummyPoints())??undefined,tags:series?.tags??descriptor.tags,metadata:(series?.metadata??descriptor.metadata) as Record<string,unknown>|undefined,declared:descriptor.declared,observed:true})}
  if(resourceResponse){const definitions:Array<[string,string,string,(point:ResourcePoint)=>number|undefined,number]>=[["cpu","CPU","cores",point=>point.cpu_millis,1000],["memory","Memory","GiB",point=>point.memory_bytes,1073741824],["gpu-utilization","GPU utilization","%",point=>point.gpu_utilization_basis_points,100],["gpu-memory","GPU memory","GiB",point=>point.gpu_memory_bytes,1073741824]];for(const[name,title,unit,selector,scale]of definitions){const points=resourcePoints(resourceResponse.points,selector,scale);numericSources.push({kind:"resource",name,title,unit,points:points.length?points:dummyPoints(),summary:numericSummary(points.length?points:dummyPoints())??undefined,observed:true})}}
  const sources=widgets.flatMap(widget=>widget.sources);for(const source of sources)if((source.kind==="metric"||source.kind==="resource")&&!numericSources.some(item=>item.kind===source.kind&&item.name===source.name)){const series=source.kind==="metric"?metricResponse?.series.find(item=>item.name===source.name):undefined,points=series?.points.length?metricPoints(series.points):dummyPoints();numericSources.push({kind:source.kind,name:source.name,title:humanize(source.name),unit:series?.unit??(source.kind==="resource"?"%":"unitless"),points,summary:series?{last:series.last,min:series.min,max:series.max,avg:series.avg??series.last}:numericSummary(points)??undefined,tags:series?.tags,metadata:series?.metadata as Record<string,unknown>|undefined,declared:true,observed:true})}
  const previewMatrices=[...matrices],previewDistributions=[...distributions],descriptors=[...observableCatalog];for(const source of sources){if(source.kind==="matrix"&&!previewMatrices.some(item=>item.name===source.name))previewMatrices.push(dummyMatrix(source.name));if(source.kind==="distribution"&&!previewDistributions.some(item=>item.name===source.name))previewDistributions.push(dummyDistribution(source.name));if(!descriptors.some(item=>item.type===source.kind&&item.name===source.name))descriptors.push({name:source.name,type:source.kind,subtype:source.kind==="matrix"?"heatmap":undefined,declared:true,observed:true})}
  return{numericSources,observableSources:descriptors.map(item=>({...item,observed:true})),progress:progressHasData(progress)?progress:dummyProgress(),matrices:previewMatrices,distributions:previewDistributions};
}
function hasActualPreviewData(source:DashboardWidgetSource,metricResponse:Awaited<ReturnType<typeof api.metrics>>|undefined,resourceResponse:Awaited<ReturnType<typeof api.resources>>|undefined,progress:ProgressState|undefined,matrices:MatrixObservation[],distributions:DistributionObservation[],catalog:ObservableSourceDescriptor[]){switch(source.kind){case"metric":return!!metricResponse?.series.find(item=>item.name===source.name)?.points.length;case"resource":return!!resourceResponse?.points.length;case"matrix":return matrices.some(item=>item.name===source.name);case"distribution":return distributions.some(item=>item.name===source.name);case"progress":return progressHasData(progress);case"table":return catalog.some(item=>item.type==="table"&&item.name===source.name&&item.observed);case"log":return true;default:return false}}
function progressHasData(progress?:ProgressState){return progress?.global_progress!=null||progress?.simple?.value!=null||progress?.current?.value!=null}
function dummyPoints(){const now=Date.now();return[18,25,22,39,35,52,48,64,61,76,72,84].map((value,index)=>({timestamp:now-(11-index)*60_000,value,step:index+1}))}
function dummyMatrix(name:string):MatrixObservation{return{id:-1,attempt_id:"preview",name,matrix_type:"heatmap",values:[[0.9,0.3,0.15],[0.35,0.72,0.24],[0.12,0.28,0.83]],row_labels:["A","B","C"],column_labels:["A","B","C"],resolution:{mode:"full",original_rows:3,original_columns:3,rows:3,columns:3}}}
function dummyDistribution(name:string):DistributionObservation{return{id:-1,name,group:"preview",samples:[1,1.4,1.8,2,2.1,2.2,2.5,2.9,3.2,3.8],bins:[{lower:1,upper:2,count:3},{lower:2,upper:3,count:5},{lower:3,upper:4,count:2}],density:[{x:1,density:.1},{x:2,density:.45},{x:3,density:.25},{x:4,density:.05}],summary:{count:10,min:1,q1:1.8,median:2.15,q3:2.9,max:3.8,mean:2.29,whisker_low:1,whisker_high:3.8,outliers:[]}}}
function dummyProgress():ProgressState{return{attempt_id:"preview",simple:{value:.64},milestones:[],reached:[],global_progress:.64}}
function humanize(value:string){return value.replace(/^__preview_/,"").replaceAll("_"," ").replaceAll("-"," ")}
function DummyWidgetSurface({type}:{type:DashboardWidget["type"]}){return <div className="relative h-full overflow-hidden bg-background p-3"><div className="absolute inset-x-3 bottom-3 top-8 flex items-end gap-2 opacity-55">{[35,62,48,78,56,88].map((height,index)=><span key={index} className="flex-1 rounded-t bg-primary/60" style={{height:`${height}%`}}/>)}</div><span className="relative text-[10px] font-medium text-muted-foreground">{humanize(type)}</span></div>}
function CompatibilityBadge({status}:{status:DashboardCompatibility}){return <Badge variant="outline" className={cn("text-[10px]",status==="compatible"?"border-emerald-500/40 text-emerald-600":status==="partially_compatible"?"border-amber-500/40 text-amber-600":"border-destructive/40 text-destructive")}>{status.replaceAll("_"," ")}</Badge>}
function TemplateError({message}:{message:string}){return <div role="alert" className="grid min-h-44 place-items-center rounded-md border border-destructive/30 p-6 text-center text-sm text-destructive">{message}</div>}
function sourceKey(source:{kind:string;name:string}){return `${source.kind}:${source.name}`}
