import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Check, CircleAlert, LayoutTemplate, RotateCcw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/api";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { cn } from "@/lib/utils";
import type { DashboardTemplate, DashboardTemplateOverride, DashboardTemplateResolution, DashboardTemplateSlot, DashboardWidget, DashboardWidgetSource } from "@/lib/dashboard-widgets";

type Props={open:boolean;onOpenChange:(open:boolean)=>void;jobID:string;attemptID:string;currentWidgets:DashboardWidget[];onApply:(widgets:DashboardWidget[])=>Promise<void>};

export function DashboardTemplatePicker({open,onOpenChange,jobID,attemptID,currentWidgets,onApply}:Props){
  const [templateID,setTemplateID]=useState(""),[overrides,setOverrides]=useState<DashboardTemplateOverride[]>([]),[confirming,setConfirming]=useState(false),[applying,setApplying]=useState(false),[previousWidgets,setPreviousWidgets]=useState<DashboardWidget[]|null>(null);
  const catalog=useQuery({queryKey:["dashboard-templates"],queryFn:api.dashboardTemplates,enabled:open,staleTime:Infinity});
  useEffect(()=>{if(open&&catalog.data?.length&&!catalog.data.some(item=>item.id===templateID))setTemplateID(catalog.data[0].id)},[open,catalog.data,templateID]);
  const template=catalog.data?.find(item=>item.id===templateID);
  useEffect(()=>setOverrides([]),[templateID,attemptID]);
  const resolution=useQuery({queryKey:["dashboard-template-resolution",jobID,attemptID,templateID,overrides],queryFn:()=>api.resolveDashboardTemplate(jobID,template!,attemptID,overrides),enabled:open&&!!template&&!!attemptID,retry:false});
  const slots=useMemo(()=>new Map((template?.widgets??[]).flatMap(widget=>widget.slots.map(slot=>[`${widget.id}:${slot.id}`,slot] as const))),[template]);
  const blocking=resolution.data?.widget_results.some(item=>item.status==="unresolved")??true;
  const apply=async()=>{if(!resolution.data||blocking)return;setApplying(true);const backup=structuredClone(currentWidgets);try{await onApply(resolution.data.widgets);setPreviousWidgets(backup);setConfirming(false);onOpenChange(false);toast.success("Dashboard template applied",{description:"The widgets are now an ordinary editable dashboard.",action:{label:"Restore",onClick:()=>void restore(backup)}})}catch(error){toast.error("Template could not be applied",{description:(error as Error).message})}finally{setApplying(false)}};
  const restore=async(widgets=previousWidgets)=>{if(!widgets)return;setApplying(true);try{await onApply(widgets);setPreviousWidgets(null);toast.success("Previous dashboard restored")}catch(error){toast.error("Dashboard could not be restored",{description:(error as Error).message})}finally{setApplying(false)}};
  const choose=(widgetID:string,slotID:string,source:DashboardWidgetSource)=>setOverrides(current=>[...current.filter(item=>item.widget_id!==widgetID||item.slot_id!==slotID),{widget_id:widgetID,slot_id:slotID,sources:[{kind:source.kind,name:source.name}]}]);
  return <><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="flex max-h-[88dvh] max-w-6xl flex-col overflow-hidden"><DialogHeader><DialogTitle>Apply dashboard template</DialogTitle><DialogDescription>Preview semantic matches before replacing the current editable layout.</DialogDescription></DialogHeader>
    {catalog.isError?<TemplateError message="The template catalog could not be loaded."/>:<div className="grid min-h-0 flex-1 gap-4 overflow-hidden lg:grid-cols-[18rem_minmax(0,1fr)]"><aside className="min-h-0 overflow-auto rounded-md border p-2"><Select value={templateID} onValueChange={setTemplateID}><SelectTrigger aria-label="Dashboard template"><SelectValue placeholder="Select a template"/></SelectTrigger><SelectContent>{catalog.data?.map(item=><SelectItem key={item.id} value={item.id}>{item.name??item.id}</SelectItem>)}</SelectContent></Select>{template&&<div className="p-2 pt-4"><div className="flex items-center gap-2"><LayoutTemplate className="size-4 text-primary"/><h3 className="text-sm font-medium">{template.name??template.id}</h3></div><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{template.description}</p><p className="mt-3 font-mono text-[10px] text-muted-foreground">Schema v{template.schema_version}</p></div>}{previousWidgets&&<Button variant="outline" size="sm" className="mt-3 w-full" disabled={applying} onClick={()=>void restore()}><RotateCcw className="size-4"/>Restore previous dashboard</Button>}</aside>
      <main className="min-h-0 overflow-auto pr-1">{resolution.isLoading?<div className="h-64 animate-pulse rounded-md border bg-muted/30"/>:resolution.isError?<TemplateError message={(resolution.error as Error).message}/>:resolution.data&&template?<TemplatePreview template={template} resolution={resolution.data} slots={slots} overrides={overrides} onChoose={choose}/>:null}</main></div>}
    <DialogFooter className="items-center sm:justify-between"><p className="mr-auto text-xs text-muted-foreground">Applying materializes regular widgets; it does not link the dashboard to the template.</p><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancel</Button><Button disabled={!resolution.data||blocking||applying} onClick={()=>currentWidgets.length?setConfirming(true):void apply()}><Sparkles className="size-4"/>Apply template</Button></DialogFooter>
  </DialogContent></Dialog><AlertDialog open={confirming} onOpenChange={setConfirming}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Replace the current dashboard?</AlertDialogTitle><AlertDialogDescription>The current layout will be kept as a restorable backup for this session. The resolved template will become a normal editable dashboard.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep current dashboard</AlertDialogCancel><AlertDialogAction disabled={applying} onClick={event=>{event.preventDefault();void apply()}}>Replace dashboard</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

function TemplatePreview({template,resolution,slots,overrides,onChoose}:{template:DashboardTemplate;resolution:DashboardTemplateResolution;slots:Map<string,DashboardTemplateSlot>;overrides:DashboardTemplateOverride[];onChoose:(widgetID:string,slotID:string,source:DashboardWidgetSource)=>void}){
  const maxRow=Math.max(1,...template.widgets.map(widget=>widget.position.y+widget.size.rows)),statuses=new Map(resolution.widget_results.map(item=>[item.widget_id,item.status]));
  return <div className="space-y-4"><section><div className="mb-2 flex items-center justify-between"><h3 className="text-sm font-medium">Layout preview</h3><Badge variant="outline">{template.widgets.length} widgets</Badge></div><div className="grid min-h-44 grid-cols-12 gap-1 rounded-md border bg-muted/20 p-2" style={{gridTemplateRows:`repeat(${maxRow}, minmax(14px, 1fr))`}}>{template.widgets.map(widget=>{const available=statuses.get(widget.id)!=="unresolved"&&statuses.get(widget.id)!=="omitted";return <div key={widget.id} className={cn("grid min-h-8 place-items-center overflow-hidden rounded border px-1 text-center text-[10px] font-medium",available?"border-primary/30 bg-primary/10":"border-dashed border-muted-foreground/30 bg-muted/40 text-muted-foreground")} style={{gridColumn:`${widget.position.x+1} / span ${widget.size.columns}`,gridRow:`${widget.position.y+1} / span ${widget.size.rows}`}}>{widget.title||widget.id}</div>})}</div></section>
    <section><h3 className="mb-2 text-sm font-medium">Source resolution</h3><div className="divide-y rounded-md border">{resolution.slot_results.map(item=>{const slot=slots.get(`${item.widget_id}:${item.slot_id}`),required=(slot?.cardinality.min??0)>0,override=overrides.find(value=>value.widget_id===item.widget_id&&value.slot_id===item.slot_id),canChoose=item.status==="ambiguous"||!!override;return <div key={`${item.widget_id}:${item.slot_id}`} className="grid gap-2 p-3 sm:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{item.slot_id}</span><Badge variant="outline" className="text-[10px]">{required?"Required":"Optional"}</Badge><ResolutionBadge status={item.status}/></div><p className="mt-1 truncate text-xs text-muted-foreground">{item.selected.length?item.selected.map(source=>source.name).join(", "):item.status==="ambiguous"?`${item.candidates.length} matching sources require a choice`:item.status==="incompatible"?"Matching semantics were found with an incompatible source type":"No matching source reported"}</p></div>{canChoose&&<Select value={override?.sources[0]?sourceKey(override.sources[0]):""} onValueChange={value=>{const source=item.candidates.find(candidate=>sourceKey(candidate)===value);if(source)onChoose(item.widget_id,item.slot_id,source)}}><SelectTrigger className="w-full sm:w-56" aria-label={`Resolve ${item.slot_id}`}><SelectValue placeholder="Choose source"/></SelectTrigger><SelectContent>{item.candidates.map(source=><SelectItem key={sourceKey(source)} value={sourceKey(source)}>{source.name}</SelectItem>)}</SelectContent></Select>}</div>})}</div></section>
  </div>;
}

function ResolutionBadge({status}:{status:DashboardTemplateResolution["slot_results"][number]["status"]}){const resolved=status==="resolved";return <Badge variant="outline" className={cn("gap-1 text-[10px]",resolved?"border-emerald-500/40 text-emerald-600":status==="ambiguous"?"border-amber-500/40 text-amber-600":"border-destructive/40 text-destructive")}>{resolved?<Check className="size-3"/>:<CircleAlert className="size-3"/>}{status}</Badge>}
function TemplateError({message}:{message:string}){return <div role="alert" className="grid min-h-44 place-items-center rounded-md border border-destructive/30 p-6 text-center text-sm text-destructive">{message}</div>}
function sourceKey(source:{kind:string;name:string}){return `${source.kind}:${source.name}`}
