import {useMemo} from "react";
import type {DashboardWidgetAppearance} from "@/lib/dashboard-widgets";
import {useElementSize} from "@/lib/use-element-size";
import type {MatrixObservation} from "@/types";

export function HeatmapWidget({matrix,correlation=false,appearance}:{matrix:MatrixObservation;correlation?:boolean;appearance?:DashboardWidgetAppearance}){
  const [host,viewport]=useElementSize<HTMLDivElement>(),rows=matrix.values.length,columns=matrix.values[0]?.length??0,rowLabels=axisLabels(matrix.row_labels,rows),columnLabels=axisLabels(matrix.column_labels,columns),numbers=matrix.values.flatMap(row=>row.filter((value):value is number=>value!=null)),manual=appearance?.heatmap_scale==="manual"&&appearance.heatmap_min!=null&&appearance.heatmap_max!=null,showLabels=appearance?.show_labels??true;
  const wide=viewport.width>viewport.height*1.35&&viewport.width>420,infoWidth=wide?clamp(viewport.width*.2,118,184):0,infoHeight=wide?0:clamp(viewport.height*.17,34,58),matrixAreaWidth=Math.max(1,viewport.width-infoWidth),matrixAreaHeight=Math.max(1,viewport.height-infoHeight),estimatedCell=Math.max(18,Math.min(Math.max(1,matrixAreaWidth-60)/Math.max(1,columns),Math.max(1,matrixAreaHeight-60)/Math.max(1,rows))),estimatedAxisFont=clamp(estimatedCell*.2,8,16),left=showLabels&&rowLabels.length?Math.min(matrixAreaWidth*.3,Math.max(46,...rowLabels.map(label=>label.length*estimatedAxisFont*.62))):8,top=showLabels&&columnLabels.length?Math.min(matrixAreaHeight*.32,Math.max(34,...columnLabels.map(label=>label.length*estimatedAxisFont*.5))):8,availableWidth=Math.max(1,matrixAreaWidth-left-10),availableHeight=Math.max(1,matrixAreaHeight-top-10),cell=Math.max(18,Math.min(availableWidth/Math.max(1,columns),availableHeight/Math.max(1,rows))),width=left+columns*cell+8,height=top+rows*cell+8,gap=appearance?.cell_gap??1,text=heatmapTextSizes(cell,matrixAreaWidth,matrixAreaHeight);
  const [minimum,maximum]=manual?[appearance!.heatmap_min!,appearance!.heatmap_max!]:correlation?[-1,1]:extent(numbers),palette=appearance?.heatmap_palette??(correlation?"diverging":"sequential"),ticks=useMemo(()=>tickIndexes(rows,columns),[rows,columns]),resolution=matrix.resolution;
  const info=<div className={`${wide?"h-full border-l px-3 py-2":"flex items-center gap-3 border-t px-2 py-1"} min-w-0 overflow-hidden`}><div className="min-w-0 flex-1"><h3 className="truncate text-[10px] font-medium">{matrix.name}</h3><p className="truncate text-[9px] text-muted-foreground">{correlation?"Correlation · ":""}{rows}×{columns}{matrix.unit?` · ${matrix.unit}`:""}</p><p className="truncate text-[8px] text-muted-foreground">{resolution?.mode==="aggregated"?`Aggregated from ${resolution.original_rows}×${resolution.original_columns}`:"Full resolution"}</p></div><div className={wide?"mt-3":"w-28 shrink-0"}><div className="h-2 rounded-full" style={{background:`linear-gradient(90deg,${heatColor(minimum,minimum,maximum,palette,appearance?.gradient)},${heatColor(maximum,minimum,maximum,palette,appearance?.gradient)})`}}/><div className="mt-0.5 flex justify-between text-[8px] text-muted-foreground"><span>{format(minimum)}</span><span>{format(maximum)}</span></div></div></div>;
  return <section ref={host} className={`grid size-full min-h-0 min-w-0 overflow-hidden rounded-md border bg-card ${wide?"grid-cols-[minmax(0,1fr)_auto]":"grid-rows-[minmax(0,1fr)_auto]"}`}><div className="grid min-h-0 min-w-0 place-items-center overflow-auto"><svg className="block" role="img" aria-label={`${matrix.name} ${correlation?"correlation ":""}heatmap with ${rows} rows and ${columns} columns`} width={width} height={height} viewBox={`0 0 ${width} ${height}`} data-cell-size={Math.round(cell)} data-value-font-size={text.value}><defs><pattern id={`null-${matrix.id}`} width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="6" height="6" fill="var(--muted)"/><line x1="0" y1="0" x2="0" y2="6" stroke="var(--muted-foreground)" strokeOpacity=".3"/></pattern></defs>{showLabels&&ticks.columns.map(index=><text key={`column-${index}`} x={left+(index+.5)*cell} y={top-5} textAnchor="end" transform={`rotate(-45 ${left+(index+.5)*cell} ${top-5})`} className="fill-muted-foreground" style={{fontSize:text.axis}}>{columnLabels[index]??index+1}</text>)}{showLabels&&ticks.rows.map(index=><text key={`row-${index}`} x={left-5} y={top+(index+.5)*cell} dominantBaseline="middle" textAnchor="end" className="fill-muted-foreground" style={{fontSize:text.axis}}>{rowLabels[index]??index+1}</text>)}{matrix.values.flatMap((row,rowIndex)=>row.map((value,columnIndex)=>{const rowLabel=rowLabels[rowIndex]??`Row ${rowIndex+1}`,columnLabel=columnLabels[columnIndex]??`Column ${columnIndex+1}`,display=value==null?"No value":`${format(value)}${matrix.unit?` · ${matrix.unit}`:""}`;return <g key={`${rowIndex}-${columnIndex}`}><rect data-null={value==null||undefined} x={left+columnIndex*cell} y={top+rowIndex*cell} width={Math.max(1,cell-gap)} height={Math.max(1,cell-gap)} fill={value==null?`url(#null-${matrix.id})`:heatColor(value,minimum,maximum,palette,appearance?.gradient)}><title>{`${rowLabel} × ${columnLabel}: ${display}`}</title></rect>{value!=null&&(appearance?.show_values??true)&&cell>=26&&rows<=24&&columns<=24&&<text data-heatmap-value x={left+(columnIndex+.5)*cell} y={top+(rowIndex+.5)*cell} dominantBaseline="middle" textAnchor="middle" className="pointer-events-none fill-slate-950 font-medium" style={{fontSize:text.value}}>{format(value)}</text>}</g>}))}</svg></div>{info}</section>;
}
export function heatmapTextSizes(cell:number,width:number,height:number){return{axis:Math.round(clamp(cell*.2,8,16)),value:Math.round(clamp(cell*.28,9,24)),scale:Math.round(clamp(Math.min(cell*.16,Math.min(width,height)*.035),8,14))}}
function clamp(value:number,minimum:number,maximum:number){return Math.max(minimum,Math.min(maximum,value))}
function axisLabels(labels:string[]|undefined,size:number){return labels?.length===size?labels:[]}
function extent(values:number[]):[number,number]{if(!values.length)return[0,1];const minimum=Math.min(...values),maximum=Math.max(...values);return minimum===maximum?[minimum,minimum+1]:[minimum,maximum]}
function tickIndexes(rows:number,columns:number){const select=(size:number)=>{const stride=Math.max(1,Math.ceil(size/12));const result:number[]=[];for(let index=0;index<size;index+=stride)result.push(index);return result};return{rows:select(rows),columns:select(columns)}}
function heatColor(value:number,minimum:number,maximum:number,palette:"sequential"|"diverging",gradient?:Array<{offset:number;color:string}>){const ratio=Math.max(0,Math.min(1,(value-minimum)/Math.max(Number.EPSILON,maximum-minimum)));if(gradient?.length){const upper=gradient.findIndex(stop=>stop.offset>=ratio),end=upper<0?gradient.at(-1)!:gradient[upper],start=upper<=0?gradient[0]:gradient[upper-1],local=end.offset===start.offset?0:(ratio-start.offset)/(end.offset-start.offset);return rgb(interpolate(hex(start.color),hex(end.color),local))}if(palette==="sequential")return rgb(interpolate([239,246,255],[29,78,216],ratio));return ratio<.5?rgb(interpolate([37,99,235],[248,250,252],ratio*2)):rgb(interpolate([248,250,252],[220,38,38],(ratio-.5)*2))}
function hex(value:string){return[1,3,5].map(index=>Number.parseInt(value.slice(index,index+2),16))}
function interpolate(start:number[],end:number[],ratio:number){return start.map((value,index)=>Math.round(value+(end[index]-value)*ratio))}
function rgb(values:number[]){return `rgb(${values.join(" ")})`}
function format(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3}).format(value)}
