import {useMemo} from "react";
import type {DashboardWidgetAppearance} from "@/lib/dashboard-widgets";
import {useElementSize} from "@/lib/use-element-size";
import type {MatrixObservation} from "@/types";

export function HeatmapWidget({matrix,correlation=false,appearance}:{matrix:MatrixObservation;correlation?:boolean;appearance?:DashboardWidgetAppearance}){
  const [host,viewport]=useElementSize<HTMLDivElement>(),rows=matrix.values.length,columns=matrix.values[0]?.length??0,rowLabels=axisLabels(matrix.row_labels,rows),columnLabels=axisLabels(matrix.column_labels,columns),numbers=matrix.values.flatMap(row=>row.filter((value):value is number=>value!=null)),manual=appearance?.heatmap_scale==="manual"&&appearance.heatmap_min!=null&&appearance.heatmap_max!=null,showLabels=appearance?.show_labels??true;
  const left=showLabels&&rowLabels.length?Math.min(viewport.width*.28,Math.max(46,...rowLabels.map(label=>label.length*6))):12,top=showLabels&&columnLabels.length?Math.min(viewport.height*.3,Math.max(36,...columnLabels.map(label=>label.length*5))):12,availableWidth=Math.max(1,viewport.width-left-16),availableHeight=Math.max(1,viewport.height-top-24),cell=Math.max(18,Math.min(availableWidth/Math.max(1,columns),availableHeight/Math.max(1,rows))),width=Math.max(viewport.width,left+columns*cell+14),height=Math.max(viewport.height,top+rows*cell+24),gap=appearance?.cell_gap??1;
  const [minimum,maximum]=manual?[appearance!.heatmap_min!,appearance!.heatmap_max!]:correlation?[-1,1]:extent(numbers),palette=appearance?.heatmap_palette??(correlation?"diverging":"sequential"),ticks=useMemo(()=>tickIndexes(rows,columns),[rows,columns]),resolution=matrix.resolution;
  return <section className="flex h-full min-h-0 min-w-0 flex-col overflow-hidden rounded-md border bg-card p-2"><div className="mb-1 flex shrink-0 items-baseline gap-2 px-1"><h3 className="truncate text-xs font-medium">{matrix.name}</h3><span className="text-[9px] text-muted-foreground">{correlation?"Correlation · ":""}{rows}×{columns}{matrix.unit?` · ${matrix.unit}`:""}{resolution?.mode==="aggregated"?` · aggregated from ${resolution.original_rows}×${resolution.original_columns}`:" · full resolution"}</span></div><div ref={host} className="min-h-0 flex-1 overflow-auto"><svg className="block" role="img" aria-label={`${matrix.name} ${correlation?"correlation ":""}heatmap with ${rows} rows and ${columns} columns`} width={width} height={height} viewBox={`0 0 ${width} ${height}`}><defs><pattern id={`null-${matrix.id}`} width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="6" height="6" fill="var(--muted)"/><line x1="0" y1="0" x2="0" y2="6" stroke="var(--muted-foreground)" strokeOpacity=".3"/></pattern></defs>{showLabels&&ticks.columns.map(index=><text key={`column-${index}`} x={left+(index+.5)*cell} y={top-5} textAnchor="end" transform={`rotate(-45 ${left+(index+.5)*cell} ${top-5})`} className="fill-muted-foreground text-[8px]">{columnLabels[index]??index+1}</text>)}{showLabels&&ticks.rows.map(index=><text key={`row-${index}`} x={left-5} y={top+(index+.68)*cell} textAnchor="end" className="fill-muted-foreground text-[8px]">{rowLabels[index]??index+1}</text>)}{matrix.values.flatMap((row,rowIndex)=>row.map((value,columnIndex)=>{const rowLabel=rowLabels[rowIndex]??`Row ${rowIndex+1}`,columnLabel=columnLabels[columnIndex]??`Column ${columnIndex+1}`,display=value==null?"No value":`${format(value)}${matrix.unit?` · ${matrix.unit}`:""}`;return <g key={`${rowIndex}-${columnIndex}`}><rect data-null={value==null||undefined} x={left+columnIndex*cell} y={top+rowIndex*cell} width={Math.max(1,cell-gap)} height={Math.max(1,cell-gap)} fill={value==null?`url(#null-${matrix.id})`:heatColor(value,minimum,maximum,palette,appearance?.gradient)}><title>{`${rowLabel} × ${columnLabel}: ${display}`}</title></rect>{value!=null&&(appearance?.show_values??true)&&cell>=26&&rows<=24&&columns<=24&&<text x={left+(columnIndex+.5)*cell} y={top+(rowIndex+.62)*cell} textAnchor="middle" className="pointer-events-none fill-slate-950 text-[8px]">{format(value)}</text>}</g>}))}<text x={left} y={height-8} className="fill-muted-foreground text-[8px]">{format(minimum)}</text><text x={left+columns*cell} y={height-8} textAnchor="end" className="fill-muted-foreground text-[8px]">{format(maximum)}</text></svg></div></section>;
}
function axisLabels(labels:string[]|undefined,size:number){return labels?.length===size?labels:[]}
function extent(values:number[]):[number,number]{if(!values.length)return[0,1];const minimum=Math.min(...values),maximum=Math.max(...values);return minimum===maximum?[minimum,minimum+1]:[minimum,maximum]}
function tickIndexes(rows:number,columns:number){const select=(size:number)=>{const stride=Math.max(1,Math.ceil(size/12));const result:number[]=[];for(let index=0;index<size;index+=stride)result.push(index);return result};return{rows:select(rows),columns:select(columns)}}
function heatColor(value:number,minimum:number,maximum:number,palette:"sequential"|"diverging",gradient?:Array<{offset:number;color:string}>){const ratio=Math.max(0,Math.min(1,(value-minimum)/Math.max(Number.EPSILON,maximum-minimum)));if(gradient?.length){const upper=gradient.findIndex(stop=>stop.offset>=ratio),end=upper<0?gradient.at(-1)!:gradient[upper],start=upper<=0?gradient[0]:gradient[upper-1],local=end.offset===start.offset?0:(ratio-start.offset)/(end.offset-start.offset);return rgb(interpolate(hex(start.color),hex(end.color),local))}if(palette==="sequential")return rgb(interpolate([239,246,255],[29,78,216],ratio));return ratio<.5?rgb(interpolate([37,99,235],[248,250,252],ratio*2)):rgb(interpolate([248,250,252],[220,38,38],(ratio-.5)*2))}
function hex(value:string){return[1,3,5].map(index=>Number.parseInt(value.slice(index,index+2),16))}
function interpolate(start:number[],end:number[],ratio:number){return start.map((value,index)=>Math.round(value+(end[index]-value)*ratio))}
function rgb(values:number[]){return `rgb(${values.join(" ")})`}
function format(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3}).format(value)}
