import { useEffect, useMemo, useRef, useState, type DragEvent, type PointerEvent, type ReactNode } from "react";
import { Activity, BarChart3, Download, GripVertical, LineChart, Maximize2, Plus, RotateCcw, ScatterChart, Settings2, Target, Trash2, Workflow } from "lucide-react";
import { ConfusionMatrixWidget } from "@/components/confusion-matrix-widget";
import { ObservationPlot } from "@/components/observation-plot";
import { ProgressWidget } from "@/components/progress-widget";
import { TimeSeriesChart, type ChartMarker } from "@/components/time-series-chart";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { createDashboardWidget, defaultDashboardWidgets, layoutDashboardWidgets, moveDashboardWidget, removeDashboardWidget, resizeDashboardWidget, restoreDashboardWidgets, widgetCatalog, type DashboardSourceKind, type DashboardSources, type DashboardWidget, type DashboardWidgetSize, type DashboardWidgetType } from "@/lib/dashboard-widgets";
import type { SeriesPoint } from "@/lib/series";
import type { MatrixObservation, ProgressState } from "@/types";

export type NumericWidgetSource = { kind: "metric" | "resource"; name: string; title: string; unit: string; points: SeriesPoint[]; color?: string; format?: (value:number)=>string; summary?: {last:number;min:number;max:number} };

export function ObservabilityDashboard({ attemptID, ready, numericSources, progress, matrices, markers, metricsDownloadURL, resourcesDownloadURL, initialWidgets=null, onWidgetsChange, live }: { attemptID: string; ready: boolean; numericSources: NumericWidgetSource[]; progress?: ProgressState; matrices: MatrixObservation[]; markers: ChartMarker[]; metricsDownloadURL: string; resourcesDownloadURL: string; initialWidgets?:DashboardWidget[]|null;onWidgetsChange?:(widgets:DashboardWidget[])=>void;live?: ReactNode }) {
  const [widgets,setWidgets]=useState<DashboardWidget[]>([]),[dragging,setDragging]=useState(""),initializedAttempt=useRef(""),hydrating=useRef(false);
  const sources=useMemo<DashboardSources>(()=>({metrics:numericSources.filter(item=>item.kind==="metric").map(item=>item.name),resources:numericSources.filter(item=>item.kind==="resource").map(item=>item.name),matrices:matrices.map(item=>item.name),progress:hasProgress(progress)}),[numericSources,matrices,progress]);
  useEffect(()=>{if(!ready||initializedAttempt.current===attemptID)return;initializedAttempt.current=attemptID;hydrating.current=true;setWidgets(restoreDashboardWidgets(initialWidgets)??defaultDashboardWidgets(sources))},[attemptID,ready,sources,initialWidgets]);
  useEffect(()=>{if(hydrating.current){hydrating.current=false;return}if(initializedAttempt.current===attemptID&&ready)onWidgetsChange?.(widgets)},[widgets,attemptID,ready,onWidgetsChange]);
  const add=(type:DashboardWidgetType)=>setWidgets(current=>layoutDashboardWidgets([...current,createDashboardWidget(type,sources)]));
  const remove=(id:string)=>setWidgets(current=>removeDashboardWidget(current,id));
  const update=(next:DashboardWidget)=>setWidgets(current=>current.map(widget=>widget.id===next.id?next:widget));
  const move=(id:string,target:string|"earlier"|"later")=>setWidgets(current=>moveDashboardWidget(current,id,target));
  const resize=(id:string,size:DashboardWidgetSize)=>setWidgets(current=>resizeDashboardWidget(current,id,size));
  const reset=()=>setWidgets(defaultDashboardWidgets(sources));
  const drop=(event:DragEvent,id:string)=>{event.preventDefault();const source=event.dataTransfer.getData("text/jobdock-widget")||dragging;if(source&&source!==id)move(source,id);setDragging("")};
  const ordered=[...widgets].sort((a,b)=>a.position.y-b.position.y||a.position.x-b.position.x);
  return <section aria-label="Metrics dashboard">
    <div className="mb-2 flex h-8 items-center gap-1.5"><h2 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Dashboard</h2>{live}<DownloadButton href={metricsDownloadURL} label="Download SDK metrics CSV"/><DownloadButton href={resourcesDownloadURL} label="Download resources CSV"/><Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon" className="size-6" aria-label="Restore default layout" onClick={reset}><RotateCcw className="size-3"/></Button></TooltipTrigger><TooltipContent>Restore default layout</TooltipContent></Tooltip><div className="ml-auto"><AddWidgetMenu onAdd={add}/></div></div>
    {!ready?<div className="min-h-[320px] animate-pulse rounded-md border bg-muted/30"/>:ordered.length===0?<EmptyDashboard onAdd={add}/>:<div className="grid grid-cols-1 gap-2 xl:grid-cols-2">{ordered.map((widget,index)=><div key={widget.id} data-widget-id={widget.id} data-widget-type={widget.type} data-position={`${widget.position.x},${widget.position.y}`} data-size={`${widget.size.columns}x${widget.size.rows}`} onDragOver={event=>event.preventDefault()} onDrop={event=>drop(event,widget.id)} className={cn("min-h-[320px] transition-opacity",widget.size.columns===2&&"xl:col-span-2",widget.size.rows===2&&"min-h-[648px]",dragging===widget.id&&"opacity-50")}><DashboardWidgetView widget={widget} numericSources={numericSources} progress={progress} matrices={matrices} markers={markers} onUpdate={update} onMove={direction=>move(widget.id,direction)} onResize={size=>resize(widget.id,size)} onDragStart={event=>{event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/jobdock-widget",widget.id);setDragging(widget.id)}} onDragEnd={()=>setDragging("")} canMoveEarlier={index>0} canMoveLater={index<ordered.length-1} onRemove={()=>remove(widget.id)}/></div>)}</div>}
  </section>;
}

function DashboardWidgetView({widget,numericSources,progress,matrices,markers,onUpdate,onMove,onResize,onDragStart,onDragEnd,canMoveEarlier,canMoveLater,onRemove}:{widget:DashboardWidget;numericSources:NumericWidgetSource[];progress?:ProgressState;matrices:MatrixObservation[];markers:ChartMarker[];onUpdate:(widget:DashboardWidget)=>void;onMove:(direction:"earlier"|"later")=>void;onResize:(size:DashboardWidgetSize)=>void;onDragStart:(event:DragEvent<HTMLElement>)=>void;onDragEnd:()=>void;canMoveEarlier:boolean;canMoveLater:boolean;onRemove:()=>void}){
  const configurable=widget.type==="lineplot"||widget.type==="barplot"||widget.type==="scatterplot";
  const action=<div className="flex"><LayoutControls widget={widget} onMove={onMove} onResize={onResize} onDragStart={onDragStart} onDragEnd={onDragEnd} canMoveEarlier={canMoveEarlier} canMoveLater={canMoveLater}/>{configurable&&<ConfigureWidget widget={widget} sources={numericSources} onUpdate={onUpdate}/>}<RemoveWidgetButton onRemove={onRemove}/></div>;
  const source=widget.sources[0];
  if(widget.type==="progress"&&progress&&hasProgress(progress))return <ProgressWidget state={progress} actions={action}/>;
  if(widget.type==="confusion_matrix"&&source){const matrix=matrices.find(item=>item.name===source.name);if(matrix)return <ConfusionMatrixWidget matrix={matrix} actions={action}/>}
  const numeric=widget.sources.flatMap(reference=>{const item=numericSources.find(candidate=>candidate.kind===reference.kind&&candidate.name===reference.name);return item?[{...item,id:sourceKey(item),role:reference.role}]:[]});
  const widgetMarkers=widget.sources.some(item=>item.kind==="metric")?markers:[];
  if(numeric.length===1&&widget.type==="lineplot"&&widget.x_axis!=="step")return <TimeSeriesChart title={numeric[0].title} points={numeric[0].points} color={numeric[0].color} format={numeric[0].format} summary={numeric[0].summary} markers={widgetMarkers} actions={action}/>;
  if(numeric.length>0&&(widget.type==="lineplot"||widget.type==="barplot"))return <ObservationPlot type={widget.type} title={widget.type==="lineplot"?"Line plot":"Bar plot"} series={numeric} xAxis={widget.x_axis} markers={widgetMarkers} actions={action}/>;
  if(numeric.length>=2&&widget.type==="scatterplot"){const x=numeric.find(item=>item.role==="x")??numeric[0],y=numeric.find(item=>item.role==="y")??numeric[1];return <ObservationPlot type="scatterplot" title={`${y.title} by ${x.title}`} series={[x,y]} markers={widgetMarkers} actions={action}/>}
  return <UnavailableWidget type={widget.type} sourceKind={source?.kind} actions={action}/>;
}

function LayoutControls({widget,onMove,onResize,onDragStart,onDragEnd,canMoveEarlier,canMoveLater}:{widget:DashboardWidget;onMove:(direction:"earlier"|"later")=>void;onResize:(size:DashboardWidgetSize)=>void;onDragStart:(event:DragEvent<HTMLElement>)=>void;onDragEnd:()=>void;canMoveEarlier:boolean;canMoveLater:boolean}){
  const origin=useRef<{x:number;y:number;size:DashboardWidgetSize}|undefined>(undefined);
  const startResize=(event:PointerEvent<HTMLButtonElement>)=>{origin.current={x:event.clientX,y:event.clientY,size:widget.size};event.currentTarget.setPointerCapture(event.pointerId)};
  const resize=(event:PointerEvent<HTMLButtonElement>)=>{if(!origin.current||!event.currentTarget.hasPointerCapture(event.pointerId))return;const columns=clampGrid(origin.current.size.columns+Math.round((event.clientX-origin.current.x)/120)),rows=clampGrid(origin.current.size.rows+Math.round((event.clientY-origin.current.y)/120));if(columns!==widget.size.columns||rows!==widget.size.rows)onResize({columns,rows})};
  return <><DropdownMenu><Tooltip><TooltipTrigger asChild><DropdownMenuTrigger asChild><Button type="button" variant="ghost" size="icon" className="size-6 cursor-grab active:cursor-grabbing" aria-label="Move or resize widget" draggable onDragStart={onDragStart} onDragEnd={onDragEnd}><GripVertical className="size-3"/></Button></DropdownMenuTrigger></TooltipTrigger><TooltipContent>Drag to reorder</TooltipContent></Tooltip><DropdownMenuContent align="end"><DropdownMenuItem disabled={!canMoveEarlier} onSelect={()=>onMove("earlier")}>Move earlier</DropdownMenuItem><DropdownMenuItem disabled={!canMoveLater} onSelect={()=>onMove("later")}>Move later</DropdownMenuItem><DropdownMenuItem onSelect={()=>onResize({...widget.size,columns:widget.size.columns===1?2:1})}>{widget.size.columns===1?"Use full width":"Use half width"}</DropdownMenuItem><DropdownMenuItem onSelect={()=>onResize({...widget.size,rows:widget.size.rows===1?2:1})}>{widget.size.rows===1?"Make taller":"Use standard height"}</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Tooltip><TooltipTrigger asChild><Button type="button" variant="ghost" size="icon" className="size-6 cursor-nwse-resize touch-none" aria-label="Drag to resize widget" onPointerDown={startResize} onPointerMove={resize} onPointerUp={()=>{origin.current=undefined}}><Maximize2 className="size-3"/></Button></TooltipTrigger><TooltipContent>Drag to resize</TooltipContent></Tooltip></>
}

function ConfigureWidget({widget,sources,onUpdate}:{widget:DashboardWidget;sources:NumericWidgetSource[];onUpdate:(widget:DashboardWidget)=>void}){
  const [open,setOpen]=useState(false),[draft,setDraft]=useState(widget);
  useEffect(()=>{if(open)setDraft(widget)},[open,widget]);
  const selectedKeys=new Set(draft.sources.map(sourceKey)),stepCompatible=draft.sources.length>0&&draft.sources.every(reference=>sources.find(item=>sourceKey(item)===sourceKey(reference))?.points.some(point=>point.step!=null));
  const toggle=(candidate:NumericWidgetSource,checked:boolean)=>{const reference={kind:candidate.kind,name:candidate.name};setDraft(current=>({...current,sources:checked?[...current.sources,reference]:current.sources.filter(item=>sourceKey(item)!==sourceKey(reference))}))};
  const setScatter=(role:"x"|"y",key:string)=>{const selected=sources.find(item=>sourceKey(item)===key);if(!selected)return;setDraft(current=>({...current,sources:[...current.sources.filter(item=>item.role!==role),{kind:selected.kind,name:selected.name,role}]}))};
  const xSource=draft.sources.find(item=>item.role==="x"),ySource=draft.sources.find(item=>item.role==="y");
  return <Dialog open={open} onOpenChange={setOpen}><Tooltip><TooltipTrigger asChild><Button type="button" variant="ghost" size="icon" className="size-6" aria-label="Configure widget" onClick={()=>setOpen(true)}><Settings2 className="size-3"/></Button></TooltipTrigger><TooltipContent>Configure widget</TooltipContent></Tooltip><DialogContent><DialogHeader><DialogTitle>Configure {widgetCatalog.find(item=>item.type===widget.type)?.label}</DialogTitle><DialogDescription>Choose compatible sources without changing the underlying observations.</DialogDescription></DialogHeader>
    {widget.type==="scatterplot"?<div className="grid gap-4 sm:grid-cols-2"><SourceSelect label="X series" value={xSource?sourceKey(xSource):""} sources={sources} onChange={value=>setScatter("x",value)}/><SourceSelect label="Y series" value={ySource?sourceKey(ySource):""} sources={sources} onChange={value=>setScatter("y",value)}/></div>:<div className="space-y-4"><fieldset><legend className="mb-2 text-sm font-medium">Series</legend><div className="max-h-56 space-y-1 overflow-auto rounded-md border p-2">{sources.map(candidate=>{const key=sourceKey(candidate),checked=selectedKeys.has(key);return <label key={key} className="flex items-center gap-2 rounded px-2 py-1.5 text-sm hover:bg-muted"><input type="checkbox" aria-label={`${candidate.title} (${candidate.unit})`} checked={checked} disabled={checked&&selectedKeys.size===1} onChange={event=>toggle(candidate,event.target.checked)}/><span className="min-w-0 flex-1 truncate">{candidate.title}</span><span className="text-xs text-muted-foreground">{candidate.unit}</span></label>})}</div></fieldset><div><label className="mb-1.5 block text-sm font-medium">Horizontal axis</label><Select value={draft.x_axis??"time"} onValueChange={value=>setDraft(current=>({...current,x_axis:value as "time"|"step"}))}><SelectTrigger aria-label="Horizontal axis"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="time">Captured time</SelectItem><SelectItem value="step" disabled={!stepCompatible}>Step</SelectItem></SelectContent></Select>{!stepCompatible&&<p className="mt-1 text-xs text-muted-foreground">Step is available when every selected series reports step values.</p>}</div></div>}
    <DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={widget.type==="scatterplot"?draft.sources.filter(item=>item.role==="x"||item.role==="y").length<2:draft.sources.length===0} onClick={()=>{onUpdate(draft);setOpen(false)}}>Apply</Button></DialogFooter>
  </DialogContent></Dialog>
}

function SourceSelect({label,value,sources,onChange}:{label:string;value:string;sources:NumericWidgetSource[];onChange:(value:string)=>void}){return <div><label className="mb-1.5 block text-sm font-medium">{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder="Select a series"/></SelectTrigger><SelectContent>{sources.map(source=><SelectItem key={sourceKey(source)} value={sourceKey(source)}>{source.title} · {source.unit}</SelectItem>)}</SelectContent></Select></div>}
function sourceKey(source:{kind:string;name:string}){return `${source.kind}:${source.name}`}

function AddWidgetMenu({onAdd}:{onAdd:(type:DashboardWidgetType)=>void}){return <DropdownMenu><DropdownMenuTrigger asChild><Button size="sm" className="h-7 gap-1.5"><Plus className="size-3.5"/>Add widget</Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-64">{widgetCatalog.map(item=>{const Icon=widgetIcon(item.type);return <DropdownMenuItem key={item.type} onSelect={()=>onAdd(item.type)} className="items-start"><Icon className="mt-0.5 size-4 shrink-0"/><span><span className="block font-medium">{item.label}</span><span className="block text-xs text-muted-foreground">{item.description}</span></span></DropdownMenuItem>})}</DropdownMenuContent></DropdownMenu>}
function EmptyDashboard({onAdd}:{onAdd:(type:DashboardWidgetType)=>void}){return <div className="grid min-h-[360px] place-items-center rounded-md border border-dashed"><div className="max-w-sm text-center"><Workflow className="mx-auto mb-3 size-8 text-muted-foreground"/><h3 className="text-sm font-medium">Build your metrics dashboard</h3><p className="mt-1 mb-4 text-sm text-muted-foreground">Add a visualization without changing or duplicating the job telemetry.</p><AddWidgetMenu onAdd={onAdd}/></div></div>}
function UnavailableWidget({type,sourceKind,actions}:{type:DashboardWidgetType;sourceKind?:DashboardSourceKind;actions:ReactNode}){const entry=widgetCatalog.find(item=>item.type===type)!;return <section className="flex min-h-[320px] flex-col rounded-md border bg-card p-3"><header className="flex items-center"><h3 className="text-sm font-medium">{entry.label}</h3><div className="ml-auto">{actions}</div></header><div className="grid flex-1 place-items-center px-6 text-center text-sm text-muted-foreground">{sourceKind?"The selected source is no longer available for this attempt.":`No compatible ${type==="confusion_matrix"?"matrix":type==="progress"?"progress":"numeric series"} has been reported yet.`}</div></section>}
function RemoveWidgetButton({onRemove}:{onRemove:()=>void}){return <Tooltip><TooltipTrigger asChild><Button type="button" variant="ghost" size="icon" className="size-6" aria-label="Remove widget" onClick={onRemove}><Trash2 className="size-3"/></Button></TooltipTrigger><TooltipContent>Remove widget</TooltipContent></Tooltip>}
function DownloadButton({href,label}:{href:string;label:string}){return <Tooltip><TooltipTrigger asChild><Button asChild variant="ghost" size="icon" className="size-6"><a href={href} aria-label={label}><Download className="size-3"/></a></Button></TooltipTrigger><TooltipContent>Download CSV</TooltipContent></Tooltip>}
function hasProgress(progress?:ProgressState){return !!progress&&(progress.global_progress!=null||progress.simple!=null||progress.current!=null||(progress.milestones?.length??0)>0)}
function widgetIcon(type:DashboardWidgetType){return type==="lineplot"?LineChart:type==="barplot"?BarChart3:type==="scatterplot"?ScatterChart:type==="confusion_matrix"?Target:Activity}
function clampGrid(value:number):1|2{return value>=2?2:1}
