import {useEffect,useId,useMemo,useRef,useState,type PointerEvent,type WheelEvent} from "react";
import type {ChartMarker} from "@/components/time-series-chart";
import {chartRangePoints} from "@/components/time-series-chart";
import {PlotToolbar} from "@/components/plot-toolbar";
import {zoomDomain,type SeriesPoint,type TimeRange} from "@/lib/series";
import type {DashboardWidgetAppearance} from "@/lib/dashboard-widgets";
import {axisTitle,linearTicks} from "@/lib/chart-geometry";

export type PlotSeries={id:string;title:string;unit:string;points:SeriesPoint[];color?:string};
type PlotType="lineplot"|"barplot"|"area_chart"|"stacked_bar"|"scatterplot";
type ScatterPoint={x:number;y:number;step?:number;timestamp:number};
type HoverPoint={x:number;y:number;label:string;detail:string};
type AlignedCategory={value:number;points:Array<SeriesPoint|undefined>};
const fallbackWidth=720,fallbackHeight=250,baseLeft=58,baseRight=18,top=16,bottom=42,palettes={default:["#3b82f6","#8b5cf6","#f59e0b","#10b981","#ef4444","#06b6d4"],cool:["#2563eb","#7c3aed","#0891b2","#4f46e5","#0d9488","#9333ea"],warm:["#ea580c","#dc2626","#d97706","#db2777","#ca8a04","#e11d48"],monochrome:["#111827","#374151","#6b7280","#9ca3af","#4b5563","#1f2937"]} as const;

export function ObservationPlot({type,title,series,xAxis="time",markers=[],range="all",appearance}:{type:PlotType;title?:string;series:PlotSeries[];xAxis?:"time"|"step";markers?:ChartMarker[];range?:TimeRange;appearance?:DashboardWidgetAppearance}){
  const label=title||plotTypeLabel(type),clipID=useId().replaceAll(":","-"),[plotSize,setPlotSize]=useState({width:fallbackWidth,height:fallbackHeight}),[zoom,setZoom]=useState<[number,number]|null>(null),[hover,setHover]=useState<HoverPoint|null>(null),plotRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const element=plotRef.current;if(!element||typeof ResizeObserver==="undefined")return;const resize=()=>{const bounds=element.getBoundingClientRect(),width=Math.max(80,Math.round(bounds.width)),height=Math.max(48,Math.round(bounds.height));setPlotSize(current=>current.width===width&&current.height===height?current:{width,height})};resize();const observer=new ResizeObserver(resize);observer.observe(element);return()=>observer.disconnect()},[]);
  const styled=useMemo(()=>series.map(item=>{const override=appearance?.series?.[item.id];return{...item,title:override?.label||item.title,unit:override?.unit||item.unit,color:override?.color||item.color}}),[series,appearance?.series]);
  const ranged=useMemo(()=>styled.map(item=>({...item,points:chartRangePoints(item.points,range)})),[styled,range]);
  const xAppearance=appearance?.x_axis,yAppearance=appearance?.y_axis;
  const prepared=ranged.map(item=>({...item,points:item.points.filter(point=>(xAxis==="time"||point.step!=null)&&validAxisValue(xValue(point,xAxis),xAppearance)&&validAxisValue(point.value,yAppearance))})),scatter=type==="scatterplot"?scatterPairs(prepared[0],prepared[1]).filter(point=>validAxisValue(point.x,xAppearance)&&validAxisValue(point.y,yAppearance)):[];
  const aligned=useMemo(()=>alignSeries(prepared,xAxis),[prepared,xAxis]),rawX=type==="scatterplot"?scatter.map(point=>point.x):aligned.map(item=>item.value),fullDomain=type==="barplot"||type==="stacked_bar"?barAxisDomain(rawX,xAppearance):axisDomain(rawX,xAppearance),domain=zoom??fullDomain;
  const domainKey=`${type}:${xAxis}:${range}:${fullDomain[0]}:${fullDomain[1]}`;useEffect(()=>{setZoom(null);setHover(null)},[domainKey]);
  const units=[...new Set((type==="scatterplot"?prepared.slice(1):prepared).map(item=>item.unit||"unitless"))],mixedUnits=units.length>1,{width,height}=plotSize,left=baseLeft,right=baseRight+Math.max(0,units.length-1)*52,plotWidth=Math.max(1,width-left-right),plotHeight=Math.max(1,height-top-bottom),x=(value:number)=>left+(axisTransform(value,xAppearance)-domain[0])/Math.max(1e-9,domain[1]-domain[0])*plotWidth;
  const visibleSeries=prepared.map(item=>({...item,points:item.points.filter(point=>{const value=axisTransform(xValue(point,xAxis),xAppearance);return value>=domain[0]&&value<=domain[1]})})),visibleAligned=aligned.filter(item=>{const value=axisTransform(item.value,xAppearance);return value>=domain[0]&&value<=domain[1]}),visibleScatter=scatter.filter(point=>{const value=axisTransform(point.x,xAppearance);return value>=domain[0]&&value<=domain[1]}),allVisible=visibleSeries.flatMap(item=>item.points),palette=palettes[appearance?.color_scheme??"default"],colors=new Map(prepared.map((item,index)=>[item.id,item.color??palette[index%palette.length]]));
  const stacking=type==="stacked_bar"||type==="area_chart"&&appearance?.stack_mode==="stacked",stackCompatible=!stacking||!mixedUnits;
  const stackedExtent=stackExtent(visibleAligned),scaleFor=(item:PlotSeries)=>{const unit=item.unit||"unitless",values=stacking?stackedExtent:mixedUnits?visibleSeries.filter(candidate=>(candidate.unit||"unitless")===unit).flatMap(candidate=>candidate.points.map(point=>point.value)):allVisible.map(point=>point.value),extent=stacking?axisDomain(values,yAppearance):axisDomain([...values,0],yAppearance);return{domain:extent,y:(value:number)=>{const safe=yAppearance?.scale==="log"&&value<=0?axisInverse(extent[0],yAppearance):value;return top+(extent[1]-axisTransform(safe,yAppearance))/Math.max(1e-9,extent[1]-extent[0])*plotHeight}}};
  const sharedScale=scaleFor(prepared[0]??{id:"",title:"",unit:"",points:[]}),scatterY=axisDomain(visibleScatter.map(point=>point.y),yAppearance),sy=(value:number)=>top+(scatterY[1]-axisTransform(value,yAppearance))/Math.max(1e-9,scatterY[1]-scatterY[0])*plotHeight;
  const yAxes=units.map((unit,index)=>{const candidates=type==="scatterplot"?prepared.slice(1,2):prepared.filter(item=>(item.unit||"unitless")===unit),representative=candidates[0],scale=type==="scatterplot"?{domain:scatterY,y:sy}:scaleFor(representative??prepared[0]),label=yAppearance?.label||(candidates.length===1?candidates[0]?.title:"Value")||"Value",displayUnit=yAppearance?.unit??(unit==="unitless"?"":unit);return{unit,representative,scale,label,displayUnit,color:colors.get(representative?.id??"")??"currentColor",x:index===0?left:width-right+(index-1)*52}}),xTicks=linearTicks(domain,Math.max(2,Math.min(6,Math.floor(plotWidth/90)))),empty=type==="scatterplot"?scatter.length===0:prepared.every(item=>item.points.length===0);
  const applyZoom=(factor:number,anchor=.5)=>{const fullWidth=fullDomain[1]-fullDomain[0],minimumWidth=xAxis==="time"&&type!=="scatterplot"?1000:Math.max(Number.EPSILON,fullWidth/1000),next=zoomDomain(domain,factor,anchor,minimumWidth);if(factor>1&&next[1]-next[0]>=fullWidth)setZoom(null);else setZoom([Math.max(fullDomain[0],next[0]),Math.min(fullDomain[1],next[1])])};
  const onWheel=(event:WheelEvent<SVGSVGElement>)=>{event.preventDefault();const bounds=event.currentTarget.getBoundingClientRect();applyZoom(event.deltaY<0?.7:1.4,clamp((event.clientX-bounds.left)/Math.max(1,bounds.width),0,1))};
  const onPointerMove=(event:PointerEvent<SVGSVGElement>)=>{const bounds=event.currentTarget.getBoundingClientRect(),px=(event.clientX-bounds.left)/Math.max(1,bounds.width)*width,py=(event.clientY-bounds.top)/Math.max(1,bounds.height)*height;if(type==="scatterplot"){if(!visibleScatter.length)return;const point=visibleScatter.reduce((best,item)=>distance(x(item.x),sy(item.y),px,py)<distance(x(best.x),sy(best.y),px,py)?item:best);setHover({x:x(point.x),y:sy(point.y),label:`${prepared[0]?.title}: ${compact(point.x)} ${prepared[0]?.unit}`,detail:`${prepared[1]?.title}: ${compact(point.y)} ${prepared[1]?.unit}${point.step!=null?` · step ${point.step}`:""}`});return}if(stacking||type==="area_chart"){if(!visibleAligned.length)return;const category=visibleAligned.reduce((best,item)=>Math.abs(x(item.value)-px)<Math.abs(x(best.value)-px)?item:best),values=category.points.map((point,index)=>point?`${prepared[index].title}: ${compact(point.value)} ${prepared[index].unit}`:`${prepared[index].title}: ${stacking?"0 (missing)":"missing"}`),total=category.points.reduce((sum,point)=>sum+(point?.value??0),0);setHover({x:x(category.value),y:sharedScale.y(stacking?total:category.points.find(Boolean)?.value??0),label:categoryLabel(category.value,xAxis),detail:values.join(" · ")});return}const candidates=visibleSeries.flatMap(item=>item.points.map(point=>({item,point,value:xValue(point,xAxis)})));if(!candidates.length)return;const nearest=candidates.reduce((best,item)=>Math.abs(x(item.value)-px)<Math.abs(x(best.value)-px)?item:best),scale=scaleFor(nearest.item);setHover({x:x(nearest.value),y:scale.y(nearest.point.value),label:`${nearest.item.title}: ${compact(nearest.point.value)} ${nearest.item.unit}`,detail:axisLabel(nearest.point,xAxis)})};
  if(!stackCompatible)return <section className="grid h-full place-items-center rounded-md border bg-card p-4 text-center"><div><p className="text-sm font-medium">Compatible units required</p><p className="mt-1 text-xs text-muted-foreground">Stacked charts cannot combine series with different units.</p></div></section>;
  return <section className="group group/widget relative h-full min-h-0 min-w-0 overflow-hidden rounded-md border bg-card">
    {(title||appearance?.subtitle)&&<div className="pointer-events-none absolute left-1/2 top-1 z-20 max-w-[55%] -translate-x-1/2 truncate rounded bg-card/75 px-1.5 py-0.5 text-center backdrop-blur-sm transition-opacity group-hover/widget:opacity-0">{title&&<h3 className="truncate text-[9px] font-medium leading-3 transition-opacity group-hover/widget:opacity-0">{title}</h3>}{appearance?.subtitle&&<p className="truncate text-[8px] leading-3 text-muted-foreground">{appearance.subtitle}</p>}</div>}
    {!empty&&<PlotToolbar label={label} series={prepared} colors={colors} mixedUnits={mixedUnits&&type!=="scatterplot"} legend={appearance?.legend} onZoomIn={()=>applyZoom(.6)} onZoomOut={()=>applyZoom(1.6)} onReset={()=>setZoom(null)}/>}
    {empty?<div className="grid size-full place-items-center text-sm text-muted-foreground">No compatible samples available</div>:<div ref={plotRef} className="absolute inset-0 min-h-0 min-w-0 overflow-hidden"><svg role="img" aria-label={`${label} ${type} with ${type==="scatterplot"?scatter.length:prepared.flatMap(item=>item.points).length} points`} data-domain={`${domain[0]}:${domain[1]}`} data-missing-values={stacking?"zero":"gap"} width={width} height={height} viewBox={`0 0 ${width} ${height}`} className="block size-full touch-none" onWheel={onWheel} onPointerMove={onPointerMove} onPointerLeave={()=>setHover(null)}>
      <defs><clipPath id={clipID}><rect x={left} y={top} width={plotWidth} height={plotHeight}/></clipPath></defs>
      {(appearance?.show_grid??true)&&yAxes[0]?.scale.domain&&linearTicks(yAxes[0].scale.domain,5).map(value=><line key={value} x1={left} x2={width-right} y1={yAxes[0].scale.y(axisInverse(value,yAppearance))} y2={yAxes[0].scale.y(axisInverse(value,yAppearance))} className="stroke-border" strokeDasharray="3 4"/>)}
      <g clipPath={`url(#${clipID})`} data-plot-marks>
      {type==="lineplot"&&visibleSeries.map(item=>{const scale=scaleFor(item),path=item.points.map((point,index)=>`${index?"L":"M"}${x(xValue(point,xAxis)).toFixed(2)},${scale.y(point.value).toFixed(2)}`).join(" ");return <g key={item.id} opacity={appearance?.opacity??1}><path d={path} fill="none" stroke={colors.get(item.id)} strokeWidth={appearance?.line_width??2} strokeDasharray={appearance?.line_style==="dashed"?"6 4":appearance?.line_style==="dotted"?"2 3":undefined} vectorEffect="non-scaling-stroke"/>{appearance?.show_points&&item.points.map((point,index)=><circle key={index} cx={x(xValue(point,xAxis))} cy={scale.y(point.value)} r={appearance?.point_size??2.5} fill={colors.get(item.id)}/>)}</g>})}
      {type==="barplot"&&visibleSeries.flatMap((item,seriesIndex)=>{const scale=scaleFor(item),total=Math.max(1,allVisible.length),slot=Math.max(3,plotWidth/total),barWidth=Math.max(2,Math.min(28,slot*.75)),baseline=scale.y(0);return item.points.map((point,index)=>{const center=x(xValue(point,xAxis)),offset=(seriesIndex-(visibleSeries.length-1)/2)*barWidth,valueY=scale.y(point.value);return <rect data-bar-mark key={`${item.id}-${index}`} x={center+offset-barWidth/2} y={Math.min(valueY,baseline)} width={barWidth} height={Math.max(1,Math.abs(baseline-valueY))} rx="1.5" fill={colors.get(item.id)} opacity={appearance?.opacity??1}/>})})}
      {type==="area_chart"&&(stacking?stackedAreas(visibleAligned,prepared,x,sharedScale.y,colors,appearance?.opacity):overlapAreas(visibleAligned,prepared,x,scaleFor,colors,appearance?.opacity))}
      {type==="stacked_bar"&&stackedBars(visibleAligned,prepared,x,sharedScale.y,colors,plotWidth,appearance?.opacity)}
      {type==="scatterplot"&&(appearance?.show_points??true)&&visibleScatter.map((point,index)=><circle key={index} cx={x(point.x)} cy={sy(point.y)} r={appearance?.point_size??4} fill={colors.get(prepared[1]?.id)} opacity={appearance?.opacity??1} className="stroke-background" strokeWidth="1.5"/>)}
      {type!=="scatterplot"&&markers.flatMap(marker=>{const value=xAxis==="step"?marker.step:marker.timestamp;return value==null||axisTransform(value,xAppearance)<domain[0]||axisTransform(value,xAppearance)>domain[1]?[]:[<line key={marker.id} x1={x(value)} x2={x(value)} y1={top} y2={height-bottom} stroke="#f59e0b" strokeWidth="2" strokeDasharray="4 3"/>]})}
      {hover&&<><line x1={hover.x} x2={hover.x} y1={top} y2={height-bottom} className="stroke-muted-foreground" strokeDasharray="3 3"/><circle cx={hover.x} cy={hover.y} r="4" fill="var(--primary)"/></>}
      </g>
      <line x1={left} x2={width-right} y1={height-bottom} y2={height-bottom} className="stroke-muted-foreground"/>{xTicks.map(value=><g key={value}><line x1={x(axisInverse(value,xAppearance))} x2={x(axisInverse(value,xAppearance))} y1={height-bottom} y2={height-bottom+4} className="stroke-muted-foreground"/><text x={x(axisInverse(value,xAppearance))} y={height-bottom+14} textAnchor="middle" className="fill-muted-foreground text-[9px]">{type==="scatterplot"?compact(axisInverse(value,xAppearance)):xAxis==="step"?compact(axisInverse(value,xAppearance)):shortTime(axisInverse(value,xAppearance))}</text></g>)}
      {yAxes.map((axis,index)=><g key={axis.unit} data-y-axis={axis.unit}><line x1={axis.x} x2={axis.x} y1={top} y2={height-bottom} stroke={axis.color} strokeOpacity=".55"/>{linearTicks(axis.scale.domain,5).map(value=><g key={value}><line x1={axis.x+(index===0?-4:0)} x2={axis.x+(index===0?0:4)} y1={axis.scale.y(axisInverse(value,yAppearance))} y2={axis.scale.y(axisInverse(value,yAppearance))} stroke={axis.color}/><text x={axis.x+(index===0?-7:7)} y={axis.scale.y(axisInverse(value,yAppearance))+3} textAnchor={index===0?"end":"start"} fill={axis.color} className="text-[9px]">{compact(axisInverse(value,yAppearance))}</text></g>)}<text x={index===0?11:axis.x+42} y={top+plotHeight/2} textAnchor="middle" transform={`rotate(-90 ${index===0?11:axis.x+42} ${top+plotHeight/2})`} fill={axis.color} className="text-[9px] font-medium">{axisTitle(axis.label,axis.displayUnit)}</text></g>)}
      <text x={left+plotWidth/2} y={height-4} textAnchor="middle" className="fill-muted-foreground text-[9px] font-medium">{axisTitle(xAppearance?.label??(type==="scatterplot"?prepared[0]?.title:xAxis==="step"?"Step":"Time"),xAppearance?.unit??(type==="scatterplot"?prepared[0]?.unit:""))}</text>
    </svg>{hover&&<div className="pointer-events-none absolute left-2 top-2 z-10 max-w-[85%] rounded border bg-popover px-2 py-1 text-xs shadow"><div className="font-medium">{hover.label}</div><div className="text-muted-foreground">{hover.detail}</div></div>}</div>}
  </section>;
}

function alignSeries(series:PlotSeries[],axis:"time"|"step"):AlignedCategory[]{const maps=series.map(item=>new Map(item.points.map(point=>[xValue(point,axis),point]))),values=[...new Set(maps.flatMap(map=>[...map.keys()]))].sort((a,b)=>a-b);return values.map(value=>({value,points:maps.map(map=>map.get(value))}))}
function stackExtent(categories:AlignedCategory[]){let minimum=0,maximum=0;for(const category of categories){let positive=0,negative=0;for(const point of category.points){const value=point?.value??0;if(value>=0)positive+=value;else negative+=value}minimum=Math.min(minimum,negative);maximum=Math.max(maximum,positive)}return[minimum,maximum]}
function stackedLayers(categories:AlignedCategory[],count:number){const positive=Array(categories.length).fill(0),negative=Array(categories.length).fill(0);return Array.from({length:count},(_,seriesIndex)=>categories.map((category,index)=>{const value=category.points[seriesIndex]?.value??0,base=value>=0?positive[index]:negative[index],topValue=base+value;if(value>=0)positive[index]=topValue;else negative[index]=topValue;return{x:category.value,base,top:topValue}}))}
function stackedAreas(categories:AlignedCategory[],series:PlotSeries[],x:(value:number)=>number,y:(value:number)=>number,colors:Map<string,string>,opacity=1){return stackedLayers(categories,series.length).map((layer,index)=><path key={series[index].id} d={areaPath(layer,x,y)} fill={colors.get(series[index].id)} fillOpacity={.58*opacity} stroke={colors.get(series[index].id)} strokeWidth="1"/>)}
function overlapAreas(categories:AlignedCategory[],series:PlotSeries[],x:(value:number)=>number,scaleFor:(series:PlotSeries)=>{y:(value:number)=>number},colors:Map<string,string>,opacity=1){return series.flatMap((item,index)=>{const scale=scaleFor(item),segments:AlignedCategory[][]=[];let current:AlignedCategory[]=[];for(const category of categories){if(category.points[index])current.push(category);else if(current.length){segments.push(current);current=[]}}if(current.length)segments.push(current);return segments.map((segment,part)=>{const layer=segment.map(category=>({x:category.value,base:0,top:category.points[index]!.value}));return <path key={`${item.id}-${part}`} d={areaPath(layer,x,scale.y)} fill={colors.get(item.id)} fillOpacity={.28*opacity} stroke={colors.get(item.id)} strokeWidth="1.5"/>})})}
function areaPath(layer:Array<{x:number;base:number;top:number}>,x:(value:number)=>number,y:(value:number)=>number){if(!layer.length)return"";return layer.map((point,index)=>`${index?"L":"M"}${x(point.x)},${y(point.top)}`).join(" ")+" "+[...layer].reverse().map(point=>`L${x(point.x)},${y(point.base)}`).join(" ")+" Z"}
function stackedBars(categories:AlignedCategory[],series:PlotSeries[],x:(value:number)=>number,y:(value:number)=>number,colors:Map<string,string>,plotWidth:number,opacity=1){const layers=stackedLayers(categories,series.length),width=Math.max(2,Math.min(42,plotWidth/Math.max(1,categories.length)*.72));return layers.flatMap((layer,seriesIndex)=>layer.map((point,index)=>{const y0=y(point.base),y1=y(point.top);return <rect data-bar-mark key={`${series[seriesIndex].id}-${index}`} x={x(point.x)-width/2} y={Math.min(y0,y1)} width={width} height={Math.max(point.base===point.top?0:1,Math.abs(y0-y1))} rx="1.5" fill={colors.get(series[seriesIndex].id)} opacity={opacity}/>}))}
function scatterPairs(xSeries?:PlotSeries,ySeries?:PlotSeries):ScatterPoint[]{if(!xSeries||!ySeries)return[];const byStep=new Map(ySeries.points.flatMap(point=>point.step==null?[]:[[point.step,point] as const]));const matched=xSeries.points.flatMap(point=>point.step!=null&&byStep.has(point.step)?[{x:point.value,y:byStep.get(point.step)!.value,step:point.step,timestamp:Math.max(point.timestamp,byStep.get(point.step)!.timestamp)}]:[]);if(matched.length)return matched;const count=Math.min(xSeries.points.length,ySeries.points.length),xStart=xSeries.points.length-count,yStart=ySeries.points.length-count;return Array.from({length:count},(_,index)=>({x:xSeries.points[xStart+index].value,y:ySeries.points[yStart+index].value,step:undefined,timestamp:Math.max(xSeries.points[xStart+index].timestamp,ySeries.points[yStart+index].timestamp)}))}
function xValue(point:SeriesPoint,axis:"time"|"step"){return axis==="step"?point.step!:point.timestamp}
function axisLabel(point:SeriesPoint,axis:"time"|"step"){return axis==="step"?`step ${point.step}`:new Date(point.timestamp).toLocaleString()}
function categoryLabel(value:number,axis:"time"|"step"){return axis==="step"?`Step ${compact(value)}`:new Date(value).toLocaleString()}
function compact(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3,notation:Math.abs(value)>=10000?"compact":"standard"}).format(value)}
function shortTime(timestamp:number){return new Date(timestamp).toLocaleString(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}
function expandDomain(min:number,max:number):[number,number]{if(min!==max)return[min,max];const padding=Math.max(1,Math.abs(min)*.01);return[min-padding,max+padding]}
function axisDomain(values:number[],axis?:DashboardWidgetAppearance["x_axis"]):[number,number]{if(axis?.range==="manual"&&axis.min!=null&&axis.max!=null)return[axisTransform(axis.min,axis),axisTransform(axis.max,axis)];const transformed=values.filter(value=>validAxisValue(value,axis)).map(value=>axisTransform(value,axis)),min=transformed.length?Math.min(...transformed):0,max=transformed.length?Math.max(...transformed):1;return expandDomain(min,max)}
function barAxisDomain(values:number[],axis?:DashboardWidgetAppearance["x_axis"]):[number,number]{const domain=axisDomain(values,axis);if(axis?.range==="manual")return domain;const ordered=[...new Set(values.filter(value=>validAxisValue(value,axis)).map(value=>axisTransform(value,axis)))].sort((a,b)=>a-b);if(ordered.length<2)return domain;return[ordered[0]-(ordered[1]-ordered[0])/2,ordered.at(-1)!+(ordered.at(-1)!-ordered.at(-2)!)/2]}
function axisTransform(value:number,axis?:DashboardWidgetAppearance["x_axis"]){return axis?.scale==="log"?Math.log10(value):value}
function axisInverse(value:number,axis?:DashboardWidgetAppearance["x_axis"]){return axis?.scale==="log"?10**value:value}
function validAxisValue(value:number,axis?:DashboardWidgetAppearance["x_axis"]){return Number.isFinite(value)&&(axis?.scale!=="log"||value>0)}
function distance(x1:number,y1:number,x2:number,y2:number){return Math.hypot(x1-x2,y1-y2)}
function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value))}
function plotTypeLabel(type:PlotType){return type==="lineplot"?"Line plot":type==="barplot"?"Bar plot":type==="area_chart"?"Area chart":type==="stacked_bar"?"Stacked bar chart":"Scatter plot"}
