import {useEffect,useMemo,useRef,useState,type PointerEvent,type WheelEvent} from "react";
import type {ChartMarker} from "@/components/time-series-chart";
import {chartRangePoints} from "@/components/time-series-chart";
import {PlotToolbar} from "@/components/plot-toolbar";
import {zoomDomain,type SeriesPoint,type TimeRange} from "@/lib/series";
import type {DashboardWidgetAppearance} from "@/lib/dashboard-widgets";

export type PlotSeries={id:string;title:string;unit:string;points:SeriesPoint[];color?:string};
type PlotType="lineplot"|"barplot"|"scatterplot";
type ScatterPoint={x:number;y:number;step?:number;timestamp:number};
type HoverPoint={x:number;y:number;label:string;detail:string};
const fallbackWidth=720,fallbackHeight=250,left=54,right=18,top=18,bottom=34,palettes={default:["#3b82f6","#8b5cf6","#f59e0b","#10b981","#ef4444","#06b6d4"],cool:["#2563eb","#7c3aed","#0891b2","#4f46e5","#0d9488","#9333ea"],warm:["#ea580c","#dc2626","#d97706","#db2777","#ca8a04","#e11d48"],monochrome:["#111827","#374151","#6b7280","#9ca3af","#4b5563","#1f2937"]} as const;

export function ObservationPlot({type,title,series,xAxis="time",markers=[],range="all",appearance}:{type:PlotType;title?:string;series:PlotSeries[];xAxis?:"time"|"step";markers?:ChartMarker[];range?:TimeRange;appearance?:DashboardWidgetAppearance}){
  const label=title||plotTypeLabel(type),[plotSize,setPlotSize]=useState({width:fallbackWidth,height:fallbackHeight}),[zoom,setZoom]=useState<[number,number]|null>(null),[hover,setHover]=useState<HoverPoint|null>(null),plotRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const element=plotRef.current;if(!element||typeof ResizeObserver==="undefined")return;const resize=()=>{const bounds=element.getBoundingClientRect(),width=Math.max(80,Math.round(bounds.width)),height=Math.max(48,Math.round(bounds.height));setPlotSize(current=>current.width===width&&current.height===height?current:{width,height})};resize();const observer=new ResizeObserver(resize);observer.observe(element);return()=>observer.disconnect()},[]);
  const styled=useMemo(()=>series.map(item=>{const override=appearance?.series?.[item.id];return{...item,title:override?.label||item.title,unit:override?.unit||item.unit,color:override?.color||item.color}}),[series,appearance?.series]);
  const ranged=useMemo(()=>styled.map(item=>({...item,points:chartRangePoints(item.points,range)})),[styled,range]);
  const xAppearance=appearance?.x_axis,yAppearance=appearance?.y_axis;
  const prepared=ranged.map(item=>({...item,points:item.points.filter(point=>(xAxis==="time"||point.step!=null)&&validAxisValue(xValue(point,xAxis),xAppearance)&&validAxisValue(point.value,yAppearance))})),scatter=type==="scatterplot"?scatterPairs(prepared[0],prepared[1]).filter(point=>validAxisValue(point.x,xAppearance)&&validAxisValue(point.y,yAppearance)):[];
  const rawX=type==="scatterplot"?scatter.map(point=>point.x):prepared.flatMap(item=>item.points.map(point=>xValue(point,xAxis))),fullDomain=axisDomain(rawX,xAppearance),domain=zoom??fullDomain;
  const domainKey=`${type}:${xAxis}:${range}:${fullDomain[0]}:${fullDomain[1]}`;useEffect(()=>{setZoom(null);setHover(null)},[domainKey]);
  const {width,height}=plotSize,plotWidth=Math.max(1,width-left-right),plotHeight=Math.max(1,height-top-bottom),x=(value:number)=>left+(axisTransform(value,xAppearance)-domain[0])/Math.max(1e-9,domain[1]-domain[0])*plotWidth;
  const visibleSeries=prepared.map(item=>({...item,points:item.points.filter(point=>{const value=axisTransform(xValue(point,xAxis),xAppearance);return value>=domain[0]&&value<=domain[1]})})),visibleScatter=scatter.filter(point=>{const value=axisTransform(point.x,xAppearance);return value>=domain[0]&&value<=domain[1]}),allVisible=visibleSeries.flatMap(item=>item.points),units=[...new Set(prepared.map(item=>item.unit||"unitless"))],mixedUnits=units.length>1,palette=palettes[appearance?.color_scheme??"default"],colors=new Map(prepared.map((item,index)=>[item.id,item.color??palette[index%palette.length]]));
  const scaleFor=(item:PlotSeries)=>{const comparable=mixedUnits?visibleSeries.find(candidate=>candidate.id===item.id)?.points??[]:allVisible,extent=axisDomain(comparable.map(point=>point.value),yAppearance);return{domain:extent,y:(value:number)=>top+(extent[1]-axisTransform(value,yAppearance))/Math.max(1e-9,extent[1]-extent[0])*plotHeight}};
  const scatterY=axisDomain(visibleScatter.map(point=>point.y),yAppearance),sy=(value:number)=>top+(scatterY[1]-axisTransform(value,yAppearance))/Math.max(1e-9,scatterY[1]-scatterY[0])*plotHeight;
  const empty=type==="scatterplot"?scatter.length===0:prepared.every(item=>item.points.length===0);
  const applyZoom=(factor:number,anchor=.5)=>{const fullWidth=fullDomain[1]-fullDomain[0],minimumWidth=xAxis==="time"&&type!=="scatterplot"?1000:Math.max(Number.EPSILON,fullWidth/1000),next=zoomDomain(domain,factor,anchor,minimumWidth);if(factor>1&&next[1]-next[0]>=fullWidth)setZoom(null);else setZoom([Math.max(fullDomain[0],next[0]),Math.min(fullDomain[1],next[1])])};
  const onWheel=(event:WheelEvent<SVGSVGElement>)=>{event.preventDefault();const bounds=event.currentTarget.getBoundingClientRect();applyZoom(event.deltaY<0?.7:1.4,clamp((event.clientX-bounds.left)/Math.max(1,bounds.width),0,1))};
  const onPointerMove=(event:PointerEvent<SVGSVGElement>)=>{const bounds=event.currentTarget.getBoundingClientRect(),px=(event.clientX-bounds.left)/Math.max(1,bounds.width)*width,py=(event.clientY-bounds.top)/Math.max(1,bounds.height)*height;if(type==="scatterplot"){if(!visibleScatter.length)return;const point=visibleScatter.reduce((best,item)=>distance(x(item.x),sy(item.y),px,py)<distance(x(best.x),sy(best.y),px,py)?item:best);setHover({x:x(point.x),y:sy(point.y),label:`${prepared[0]?.title}: ${compact(point.x)} ${prepared[0]?.unit}`,detail:`${prepared[1]?.title}: ${compact(point.y)} ${prepared[1]?.unit}${point.step!=null?` · step ${point.step}`:""}`});return}const candidates=visibleSeries.flatMap(item=>item.points.map(point=>({item,point,value:xValue(point,xAxis)})));if(!candidates.length)return;const nearest=candidates.reduce((best,item)=>Math.abs(x(item.value)-px)<Math.abs(x(best.value)-px)?item:best),scale=scaleFor(nearest.item);setHover({x:x(nearest.value),y:scale.y(nearest.point.value),label:`${nearest.item.title}: ${compact(nearest.point.value)} ${nearest.item.unit}`,detail:axisLabel(nearest.point,xAxis)})};
  return <section className="group group/widget relative h-full min-h-0 min-w-0 overflow-hidden rounded-md border bg-card">
    {(title||appearance?.subtitle)&&<div className="pointer-events-none absolute left-1/2 top-1 z-20 max-w-[55%] -translate-x-1/2 truncate rounded bg-card/75 px-1.5 py-0.5 text-center backdrop-blur-sm transition-opacity group-hover/widget:opacity-0">{title&&<h3 className="truncate text-[9px] font-medium leading-3 transition-opacity group-hover/widget:opacity-0">{title}</h3>}{appearance?.subtitle&&<p className="truncate text-[8px] leading-3 text-muted-foreground">{appearance.subtitle}</p>}</div>}
    {!empty&&<PlotToolbar label={label} series={prepared} colors={colors} mixedUnits={mixedUnits&&type!=="scatterplot"} legend={appearance?.legend} onZoomIn={()=>applyZoom(.6)} onZoomOut={()=>applyZoom(1.6)} onReset={()=>setZoom(null)}/>}
    {empty?<div className="grid size-full place-items-center text-sm text-muted-foreground">No compatible samples available</div>:<div ref={plotRef} className="absolute inset-0 min-h-0 min-w-0 overflow-hidden"><svg role="img" aria-label={`${label} ${type} with ${type==="scatterplot"?scatter.length:prepared.flatMap(item=>item.points).length} points`} data-domain={`${domain[0]}:${domain[1]}`} width={width} height={height} viewBox={`0 0 ${width} ${height}`} className="block size-full touch-none" onWheel={onWheel} onPointerMove={onPointerMove} onPointerLeave={()=>setHover(null)}>
      {(appearance?.show_grid??true)&&[0,.5,1].map(ratio=><line key={ratio} x1={left} x2={width-right} y1={top+ratio*plotHeight} y2={top+ratio*plotHeight} className="stroke-border" strokeDasharray="3 4"/>)}
      {type==="lineplot"&&visibleSeries.map(item=>{const scale=scaleFor(item),path=item.points.map((point,index)=>`${index?"L":"M"}${x(xValue(point,xAxis)).toFixed(2)},${scale.y(point.value).toFixed(2)}`).join(" ");return <g key={item.id} opacity={appearance?.opacity??1}><path d={path} fill="none" stroke={colors.get(item.id)} strokeWidth={appearance?.line_width??2} strokeDasharray={appearance?.line_style==="dashed"?"6 4":appearance?.line_style==="dotted"?"2 3":undefined} vectorEffect="non-scaling-stroke"/>{appearance?.show_points&&item.points.map((point,index)=><circle key={index} cx={x(xValue(point,xAxis))} cy={scale.y(point.value)} r={appearance?.point_size??2.5} fill={colors.get(item.id)}/>)}</g>})}
      {type==="barplot"&&visibleSeries.flatMap((item,seriesIndex)=>{const scale=scaleFor(item),total=Math.max(1,allVisible.length),slot=Math.max(3,plotWidth/total),barWidth=Math.max(2,Math.min(28,slot*.75)),baseline=yAppearance?.scale==="log"?top+plotHeight:scale.y(Math.max(axisInverse(scale.domain[0],yAppearance),Math.min(axisInverse(scale.domain[1],yAppearance),0)));return item.points.map((point,index)=>{const center=x(xValue(point,xAxis)),offset=(seriesIndex-(visibleSeries.length-1)/2)*barWidth,valueY=scale.y(point.value);return <rect key={`${item.id}-${index}`} x={center+offset-barWidth/2} y={Math.min(valueY,baseline)} width={barWidth} height={Math.max(1,Math.abs(baseline-valueY))} rx="1.5" fill={colors.get(item.id)} opacity={appearance?.opacity??1}/>})})}
      {type==="scatterplot"&&(appearance?.show_points??true)&&visibleScatter.map((point,index)=><circle key={index} cx={x(point.x)} cy={sy(point.y)} r={appearance?.point_size??4} fill={colors.get(prepared[1]?.id)} opacity={appearance?.opacity??1} className="stroke-background" strokeWidth="1.5"/>)}
      {type!=="scatterplot"&&markers.flatMap(marker=>{const value=xAxis==="step"?marker.step:marker.timestamp;return value==null||value<domain[0]||value>domain[1]?[]:[<line key={marker.id} x1={x(value)} x2={x(value)} y1={top} y2={height-bottom} stroke="#f59e0b" strokeWidth="2" strokeDasharray="4 3"/>]})}
      {hover&&<><line x1={hover.x} x2={hover.x} y1={top} y2={height-bottom} className="stroke-muted-foreground" strokeDasharray="3 3"/><circle cx={hover.x} cy={hover.y} r="4" fill="var(--primary)"/></>}
      <text x={left} y={height-6} className="fill-muted-foreground text-[10px]">{type==="scatterplot"?compact(axisInverse(domain[0],xAppearance)):xAxis==="step"?`Step ${compact(axisInverse(domain[0],xAppearance))}`:shortTime(axisInverse(domain[0],xAppearance))}</text><text x={width-right} y={height-6} textAnchor="end" className="fill-muted-foreground text-[10px]">{type==="scatterplot"?compact(axisInverse(domain[1],xAppearance)):xAxis==="step"?`Step ${compact(axisInverse(domain[1],xAppearance))}`:shortTime(axisInverse(domain[1],xAppearance))}</text>
      {xAppearance?.label&&<text x={left+plotWidth/2} y={height-6} textAnchor="middle" className="fill-muted-foreground text-[9px]">{axisCaption(xAppearance)}</text>}{yAppearance?.label&&<text x="10" y={top+plotHeight/2} textAnchor="middle" transform={`rotate(-90 10 ${top+plotHeight/2})`} className="fill-muted-foreground text-[9px]">{axisCaption(yAppearance)}</text>}
    </svg>{hover&&<div className="pointer-events-none absolute left-2 top-2 z-10 rounded border bg-popover px-2 py-1 text-xs shadow"><div className="font-medium">{hover.label}</div><div className="text-muted-foreground">{hover.detail}</div></div>}</div>}
  </section>;
}

function scatterPairs(xSeries?:PlotSeries,ySeries?:PlotSeries):ScatterPoint[]{if(!xSeries||!ySeries)return[];const byStep=new Map(ySeries.points.flatMap(point=>point.step==null?[]:[[point.step,point] as const]));const matched=xSeries.points.flatMap(point=>point.step!=null&&byStep.has(point.step)?[{x:point.value,y:byStep.get(point.step)!.value,step:point.step,timestamp:Math.max(point.timestamp,byStep.get(point.step)!.timestamp)}]:[]);if(matched.length)return matched;const count=Math.min(xSeries.points.length,ySeries.points.length),xStart=xSeries.points.length-count,yStart=ySeries.points.length-count;return Array.from({length:count},(_,index)=>({x:xSeries.points[xStart+index].value,y:ySeries.points[yStart+index].value,step:undefined,timestamp:Math.max(xSeries.points[xStart+index].timestamp,ySeries.points[yStart+index].timestamp)}))}
function xValue(point:SeriesPoint,axis:"time"|"step"){return axis==="step"?point.step!:point.timestamp}
function axisLabel(point:SeriesPoint,axis:"time"|"step"){return axis==="step"?`step ${point.step}`:new Date(point.timestamp).toLocaleString()}
function compact(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3,notation:Math.abs(value)>=10000?"compact":"standard"}).format(value)}
function shortTime(timestamp:number){return new Date(timestamp).toLocaleString(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}
function expandDomain(min:number,max:number):[number,number]{if(min!==max)return[min,max];const padding=Math.max(1,Math.abs(min)*.01);return[min-padding,max+padding]}
function axisDomain(values:number[],axis?:DashboardWidgetAppearance["x_axis"]):[number,number]{if(axis?.range==="manual"&&axis.min!=null&&axis.max!=null)return[axisTransform(axis.min,axis),axisTransform(axis.max,axis)];const transformed=values.filter(value=>validAxisValue(value,axis)).map(value=>axisTransform(value,axis)),min=transformed.length?Math.min(...transformed):0,max=transformed.length?Math.max(...transformed):1;return expandDomain(min,max)}
function axisTransform(value:number,axis?:DashboardWidgetAppearance["x_axis"]){return axis?.scale==="log"?Math.log10(value):value}
function axisInverse(value:number,axis?:DashboardWidgetAppearance["x_axis"]){return axis?.scale==="log"?10**value:value}
function validAxisValue(value:number,axis?:DashboardWidgetAppearance["x_axis"]){return Number.isFinite(value)&&(axis?.scale!=="log"||value>0)}
function axisCaption(axis:NonNullable<DashboardWidgetAppearance["x_axis"]>){return axis.unit?`${axis.label} (${axis.unit})`:axis.label!}
function distance(x1:number,y1:number,x2:number,y2:number){return Math.hypot(x1-x2,y1-y2)}
function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value))}
function plotTypeLabel(type:PlotType){return type==="lineplot"?"Line plot":type==="barplot"?"Bar plot":"Scatter plot"}
