import {useEffect,useRef,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {api} from "@/api";
import type {DashboardWidget} from "@/lib/dashboard-widgets";
import {formatAxisValue,linearTicks} from "@/lib/chart-geometry";

type Point={x:number;y:number;lower?:number;upper?:number};

export function PartialDependenceWidget({jobID,attemptID,widget}:{jobID:string;attemptID:string;widget:DashboardWidget}){
  const source=widget.sources.find(item=>item.kind==="table"),query=useQuery({queryKey:["job-table",jobID,attemptID,source?.name,"partial-dependence"],queryFn:()=>api.table(jobID,attemptID,source!.name,"limit=500&sort=feature_value&order=asc"),enabled:!!source,staleTime:10_000}),table=query.data,host=useRef<HTMLDivElement>(null),[size,setSize]=useState({width:640,height:320});
  useEffect(()=>{const element=host.current;if(!element||typeof ResizeObserver==="undefined")return;const resize=()=>{const bounds=element.getBoundingClientRect();setSize({width:Math.max(120,Math.round(bounds.width)),height:Math.max(80,Math.round(bounds.height))})};resize();const observer=new ResizeObserver(resize);observer.observe(element);return()=>observer.disconnect()},[]);
  if(query.isLoading)return <div className="h-full animate-pulse rounded-md border bg-muted/20"/>;
  const points:Point[]=table?.items.flatMap(item=>typeof item.values.feature_value==="number"&&typeof item.values.partial_dependence==="number"?[{x:item.values.feature_value,y:item.values.partial_dependence,lower:typeof item.values.lower==="number"?item.values.lower:undefined,upper:typeof item.values.upper==="number"?item.values.upper:undefined}]:[])??[];
  if(!table||points.length<2)return <div role="status" className="grid h-full place-items-center rounded-md border text-xs text-muted-foreground">No partial dependence curve.</div>;
  const left=52,right=18,top=18,bottom=32,width=size.width,height=size.height,xValues=points.map(point=>point.x),yValues=points.flatMap(point=>[point.y,...(point.lower==null?[]:[point.lower]),...(point.upper==null?[]:[point.upper])]),xDomain=extent(xValues),yDomain=extent(yValues),x=(value:number)=>left+(value-xDomain[0])/(xDomain[1]-xDomain[0])*(width-left-right),y=(value:number)=>top+(yDomain[1]-value)/(yDomain[1]-yDomain[0])*(height-top-bottom),path=points.map((point,index)=>`${index?"L":"M"}${x(point.x)},${y(point.y)}`).join(" "),ranged=points.every(point=>point.lower!=null&&point.upper!=null),band=ranged?[...points.map(point=>`${x(point.x)},${y(point.upper!)}`),...points.slice().reverse().map(point=>`${x(point.x)},${y(point.lower!)}`)].join(" "):"",feature=String(table.metadata?.feature??"Feature"),featureUnit=String(table.metadata?.feature_unit??table.columns.find(column=>column.name==="feature_value")?.unit??""),valueUnit=String(table.metadata?.value_unit??table.columns.find(column=>column.name==="partial_dependence")?.unit??"");
  const color=widget.appearance?.accent_color??"#2563eb";
  return <section className="relative h-full min-h-0 overflow-hidden rounded-md border bg-card" aria-label={`Partial dependence for ${feature}`}><div className="pointer-events-none absolute left-2 top-1 z-10 rounded bg-card/80 px-1.5 py-0.5 text-[9px] text-muted-foreground">{feature}{table.metadata?.output?` → ${String(table.metadata.output)}`:""}</div><div ref={host} className="absolute inset-0"><svg className="block size-full" width={width} height={height} viewBox={`0 0 ${width} ${height}`} role="img">{linearTicks(yDomain,5).map(value=><g key={`y-${value}`}><line x1={left} x2={width-right} y1={y(value)} y2={y(value)} className="stroke-border" strokeDasharray="3 4"/><text x={left-7} y={y(value)+3} textAnchor="end" className="fill-muted-foreground text-[9px]">{formatAxisValue(value)}</text></g>)}{linearTicks(xDomain,5).map(value=><g key={`x-${value}`}><line x1={x(value)} x2={x(value)} y1={height-bottom} y2={height-bottom+4} className="stroke-muted-foreground"/><text x={x(value)} y={height-bottom+14} textAnchor="middle" className="fill-muted-foreground text-[9px]">{formatAxisValue(value)}</text></g>)}<line x1={left} x2={width-right} y1={height-bottom} y2={height-bottom} className="stroke-muted-foreground"/><line x1={left} x2={left} y1={top} y2={height-bottom} className="stroke-muted-foreground"/>{band&&<polygon points={band} fill={color} opacity=".16"/>}<path d={path} fill="none" stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke"/>{points.map((point,index)=><circle key={index} cx={x(point.x)} cy={y(point.y)} r="3" fill={color} tabIndex={0}><title>{`${feature}: ${format(point.x)}${featureUnit?` ${featureUnit}`:""}; partial dependence: ${format(point.y)}${valueUnit?` ${valueUnit}`:""}`}</title></circle>)}<text x={width/2} y={height-4} textAnchor="middle" className="fill-muted-foreground text-[9px] font-medium">{feature}{featureUnit?` (${featureUnit})`:""}</text><text x="10" y={height/2} textAnchor="middle" transform={`rotate(-90 10 ${height/2})`} className="fill-muted-foreground text-[9px] font-medium">Partial dependence{valueUnit?` (${valueUnit})`:""}</text></svg></div></section>;
}

function extent(values:number[]):[number,number]{const min=Math.min(...values),max=Math.max(...values);if(min!==max)return[min,max];const pad=Math.max(1,Math.abs(min)*.01);return[min-pad,max+pad]}
function format(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3,notation:Math.abs(value)>=10000?"compact":"standard"}).format(value)}
