import {useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {api} from "@/api";
import {Button} from "@/components/ui/button";
import type {DashboardWidget} from "@/lib/dashboard-widgets";

const palette=["#2563eb","#dc2626","#16a34a","#9333ea","#ea580c","#0891b2","#ca8a04","#db2777"];
export function ProjectionScatterWidget({jobID,attemptID,widget,onUpdate}:{jobID:string;attemptID:string;widget:DashboardWidget;onUpdate:(widget:DashboardWidget)=>void}){
  const [selected,setSelected]=useState(""),source=widget.sources.find(item=>item.kind==="table"),query=useQuery({queryKey:["job-table",jobID,attemptID,source?.name,"projection"],queryFn:()=>api.table(jobID,attemptID,source!.name,"limit=500&sample=true"),enabled:!!source,staleTime:10_000}),table=query.data,colorBy=widget.projection_color_by??(widget.type==="cluster_scatter"?"cluster":"label");
  if(query.isLoading)return <div className="h-full animate-pulse rounded-md border bg-muted/20"/>;
  const points=table?.items.flatMap(item=>typeof item.values.x==="number"&&typeof item.values.y==="number"?[{id:String(item.values.sample_id??item.cursor),x:item.values.x,y:item.values.y,z:typeof item.values.z==="number"?item.values.z:undefined,label:typeof item.values.label==="string"?item.values.label:undefined,cluster:typeof item.values.cluster==="string"?item.values.cluster:undefined,color:typeof item.values.color==="string"?item.values.color:undefined}]:[])??[];
  if(!table||!points.length)return <div role="status" className="grid h-full place-items-center rounded-md border text-xs text-muted-foreground">No projected points.</div>;
  const xmin=Math.min(...points.map(point=>point.x)),xmax=Math.max(...points.map(point=>point.x)),ymin=Math.min(...points.map(point=>point.y)),ymax=Math.max(...points.map(point=>point.y)),x=(value:number)=>44+(value-xmin)/(xmax-xmin||1)*560,y=(value:number)=>330-(value-ymin)/(ymax-ymin||1)*295,groups=[...new Set(points.map(point=>point[colorBy]??"Unassigned"))],selectedPoint=points.find(point=>point.id===selected);
  const next=colorBy==="label"?"cluster":colorBy==="cluster"?"color":"label";
  return <section className="relative h-full min-h-0 overflow-hidden rounded-md border bg-card" aria-label={widget.type==="cluster_scatter"?"Cluster scatter":"Embedding scatter"}><div className="absolute right-2 top-2 z-10 flex items-center gap-1"><span className="rounded bg-background/85 px-2 py-1 text-[9px] text-muted-foreground">{String(table.metadata?.method??"projection")} · sampled {points.length}/{table.total}</span><Button variant="ghost" className="h-6 bg-background/85 px-2 text-[10px]" onClick={()=>onUpdate({...widget,projection_color_by:next})}>Color: {colorBy}</Button></div><svg className="h-full w-full" viewBox="0 0 640 370" preserveAspectRatio="none" role="img"><line x1="44" y1="330" x2="604" y2="330" className="stroke-border"/><line x1="44" y1="35" x2="44" y2="330" className="stroke-border"/>{points.map(point=>{const group=point[colorBy]??"Unassigned",index=groups.indexOf(group),radius=point.z==null?3.5:Math.max(2.5,Math.min(7,3.5+Math.abs(point.z)*.25));return <circle key={point.id} cx={x(point.x)} cy={y(point.y)} r={selected===point.id?radius+2:radius} fill={palette[index%palette.length]} stroke={selected===point.id?"var(--foreground)":"none"} opacity=".72" tabIndex={0} onClick={()=>setSelected(point.id)}><title>{`${point.id}: (${format(point.x)}, ${format(point.y)})${point.label?`, label ${point.label}`:""}${point.cluster?`, cluster ${point.cluster}`:""}`}</title></circle>})}<text x="325" y="360" textAnchor="middle" className="fill-muted-foreground text-[10px]">Projection X</text><text x="14" y="185" textAnchor="middle" transform="rotate(-90 14 185)" className="fill-muted-foreground text-[10px]">Projection Y</text></svg>{selectedPoint&&<div className="absolute bottom-2 left-2 rounded bg-background/90 px-2 py-1 text-[9px] shadow">{selectedPoint.id} · {format(selectedPoint.x)}, {format(selectedPoint.y)}{selectedPoint.z==null?"":`, ${format(selectedPoint.z)}`}</div>}</section>;
}
function format(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3}).format(value)}
