import {useEffect,useRef,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {api} from "@/api";
import {Button} from "@/components/ui/button";
import type {DashboardWidget} from "@/lib/dashboard-widgets";
import {formatAxisValue,linearTicks} from "@/lib/chart-geometry";

const defaultColors=["#2563eb","#dc2626","#16a34a","#9333ea","#ea580c","#0891b2","#ca8a04","#db2777"];
export function ProjectionScatterWidget({jobID,attemptID,widget,colors=defaultColors,onUpdate}:{jobID:string;attemptID:string;widget:DashboardWidget;colors?:readonly string[];onUpdate:(widget:DashboardWidget)=>void}){
  const [selected,setSelected]=useState(""),host=useRef<HTMLElement>(null),[size,setSize]=useState({width:640,height:370}),source=widget.sources.find(item=>item.kind==="table"),query=useQuery({queryKey:["job-table",jobID,attemptID,source?.name,"projection"],queryFn:()=>api.table(jobID,attemptID,source!.name,"limit=500&sample=true"),enabled:!!source,staleTime:10_000}),table=query.data,colorBy=widget.projection_color_by??(widget.type==="cluster_scatter"?"cluster":"label");
  useEffect(()=>{const element=host.current;if(!element||typeof ResizeObserver==="undefined")return;const resize=()=>{const bounds=element.getBoundingClientRect(),width=Math.max(120,Math.round(bounds.width)),height=Math.max(90,Math.round(bounds.height));setSize(current=>current.width===width&&current.height===height?current:{width,height})};resize();const observer=new ResizeObserver(resize);observer.observe(element);return()=>observer.disconnect()},[query.isLoading]);
  if(query.isLoading)return <div className="h-full animate-pulse rounded-md border bg-muted/20"/>;
  const points=table?.items.flatMap(item=>typeof item.values.x==="number"&&typeof item.values.y==="number"?[{id:String(item.values.sample_id??item.cursor),x:item.values.x,y:item.values.y,z:typeof item.values.z==="number"?item.values.z:undefined,label:typeof item.values.label==="string"?item.values.label:undefined,cluster:typeof item.values.cluster==="string"?item.values.cluster:undefined,color:typeof item.values.color==="string"?item.values.color:undefined}]:[])??[];
  if(!table||!points.length)return <div role="status" className="grid h-full place-items-center rounded-md border text-xs text-muted-foreground">No projected points.</div>;
  const xmin=Math.min(...points.map(point=>point.x)),xmax=Math.max(...points.map(point=>point.x)),ymin=Math.min(...points.map(point=>point.y)),ymax=Math.max(...points.map(point=>point.y)),domainSpan=Math.max(xmax-xmin,ymax-ymin,1e-9),xmid=(xmin+xmax)/2,ymid=(ymin+ymax)/2,xDomain:[number,number]=[xmid-domainSpan/2,xmid+domainSpan/2],yDomain:[number,number]=[ymid-domainSpan/2,ymid+domainSpan/2],left=58,right=16,top=34,bottom=42,availableWidth=Math.max(1,size.width-left-right),availableHeight=Math.max(1,size.height-top-bottom),side=Math.min(availableWidth,availableHeight),plotLeft=left+(availableWidth-side)/2,plotTop=top+(availableHeight-side)/2,plotBottom=plotTop+side,x=(value:number)=>plotLeft+(value-xDomain[0])/domainSpan*side,y=(value:number)=>plotBottom-(value-yDomain[0])/domainSpan*side,groups=[...new Set(points.map(point=>point[colorBy]??"Unassigned"))],selectedPoint=points.find(point=>point.id===selected);
  const next=colorBy==="label"?"cluster":colorBy==="cluster"?"color":"label";
  return <section ref={host} className="relative h-full min-h-0 overflow-hidden rounded-md border bg-card" aria-label={widget.type==="cluster_scatter"?"Cluster scatter":"Embedding scatter"}><div className="absolute right-2 top-2 z-10 flex items-center gap-1"><span className="rounded bg-background/85 px-2 py-1 text-[9px] text-muted-foreground">{String(table.metadata?.method??"projection")} · sampled {points.length}/{table.total}</span><Button variant="ghost" className="h-6 bg-background/85 px-2 text-[10px]" onClick={()=>onUpdate({...widget,projection_color_by:next})}>Color: {colorBy}</Button></div><svg className="block size-full" width={size.width} height={size.height} viewBox={`0 0 ${size.width} ${size.height}`} role="img" aria-label={`${widget.type==="cluster_scatter"?"Cluster":"Embedding"} scatter with ${points.length} points`} data-plot-size={`${Math.round(side)}x${Math.round(side)}`}>{linearTicks(yDomain,5).map(value=><g key={`y-${value}`}><line x1={plotLeft} x2={plotLeft+side} y1={y(value)} y2={y(value)} className="stroke-border" strokeDasharray="3 4"/><text x={plotLeft-7} y={y(value)+3} textAnchor="end" className="fill-muted-foreground text-[9px]">{formatAxisValue(value)}</text></g>)}{linearTicks(xDomain,5).map(value=><g key={`x-${value}`}><line x1={x(value)} x2={x(value)} y1={plotBottom} y2={plotBottom+4} className="stroke-muted-foreground"/><text x={x(value)} y={plotBottom+14} textAnchor="middle" className="fill-muted-foreground text-[9px]">{formatAxisValue(value)}</text></g>)}<line x1={plotLeft} y1={plotBottom} x2={plotLeft+side} y2={plotBottom} className="stroke-muted-foreground"/><line x1={plotLeft} y1={plotTop} x2={plotLeft} y2={plotBottom} className="stroke-muted-foreground"/>{points.map(point=>{const group=point[colorBy]??"Unassigned",index=groups.indexOf(group),radius=point.z==null?3.5:Math.max(2.5,Math.min(7,3.5+Math.abs(point.z)*.25));return <circle key={point.id} cx={x(point.x)} cy={y(point.y)} r={selected===point.id?radius+2:radius} fill={colors[index%colors.length]} stroke={selected===point.id?"var(--foreground)":"none"} opacity=".72" tabIndex={0} onClick={()=>setSelected(point.id)}><title>{`${point.id}: (${format(point.x)}, ${format(point.y)})${point.label?`, label ${point.label}`:""}${point.cluster?`, cluster ${point.cluster}`:""}`}</title></circle>})}<text x={plotLeft+side/2} y={size.height-5} textAnchor="middle" className="fill-muted-foreground text-[9px] font-medium">Projection X</text><text x="11" y={plotTop+side/2} textAnchor="middle" transform={`rotate(-90 11 ${plotTop+side/2})`} className="fill-muted-foreground text-[9px] font-medium">Projection Y</text></svg>{selectedPoint&&<div className="absolute bottom-2 left-2 rounded bg-background/90 px-2 py-1 text-[9px] shadow">{selectedPoint.id} · {format(selectedPoint.x)}, {format(selectedPoint.y)}{selectedPoint.z==null?"":`, ${format(selectedPoint.z)}`}</div>}</section>;
}
function format(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3}).format(value)}
