import {useQuery} from "@tanstack/react-query";
import {api} from "@/api";
import type {DashboardWidget} from "@/lib/dashboard-widgets";

const colors=["#2563eb","#dc2626","#16a34a","#9333ea","#ea580c","#0891b2"];

export function RegressionDiagnosticsWidget({jobID,attemptID,widget}:{jobID:string;attemptID:string;widget:DashboardWidget}){
  const source=widget.sources.find(item=>item.kind==="table"),query=useQuery({queryKey:["job-table",jobID,attemptID,source?.name,"regression-diagnostics"],queryFn:()=>api.table(jobID,attemptID,source!.name,"limit=500"),enabled:!!source,staleTime:10_000}),table=query.data;
  if(query.isLoading)return <div className="h-full animate-pulse rounded-md border bg-muted/20"/>;
  const points=table?.items.flatMap(item=>typeof item.values.actual==="number"&&typeof item.values.prediction==="number"?[{actual:item.values.actual,prediction:item.values.prediction,group:typeof item.values.group==="string"?item.values.group:"All"}]:[])??[];
  if(!table||!points.length)return <div role="status" className="grid h-full place-items-center rounded-md border text-xs text-muted-foreground">No regression observations.</div>;
  const definition=table.metadata?.residual_definition==="prediction_minus_actual"?"prediction_minus_actual":"actual_minus_prediction",residual=widget.type==="residual_plot",basis=widget.residual_x_axis??"prediction",plotted=points.map(point=>({x:residual?point[basis]:point.actual,y:residual?(definition==="actual_minus_prediction"?point.actual-point.prediction:point.prediction-point.actual):point.prediction,group:point.group})),all=[...plotted.flatMap(point=>[point.x,point.y]),0],min=Math.min(...all),max=Math.max(...all),pad=Math.max((max-min)*.08,Math.abs(max)*.01,1e-9),lo=min-pad,hi=max+pad,x=(value:number)=>52+(value-lo)/(hi-lo)*538,y=(value:number)=>312-(value-lo)/(hi-lo)*278,groups=[...new Set(plotted.map(point=>point.group))],unit=table.columns.find(column=>column.name==="actual")?.unit??"",summary=table.metadata?.summary;
  const summaries=summary&&typeof summary==="object"?Object.entries(summary):[];
  return <section className="relative h-full min-h-0 overflow-hidden rounded-md border bg-card" aria-label={residual?"Residual plot":"Prediction versus actual plot"}><svg className="h-full w-full" viewBox="0 0 620 350" preserveAspectRatio="none" role="img"><line x1="52" y1="312" x2="590" y2="312" className="stroke-border"/><line x1="52" y1="34" x2="52" y2="312" className="stroke-border"/>{residual?<line x1="52" y1={y(0)} x2="590" y2={y(0)} stroke="var(--muted-foreground)" strokeDasharray="5 5" opacity=".65"/>:<line x1={x(lo)} y1={y(lo)} x2={x(hi)} y2={y(hi)} stroke="var(--muted-foreground)" strokeDasharray="5 5" opacity=".65"/>}{plotted.map((point,index)=><circle key={index} cx={x(point.x)} cy={y(point.y)} r="4" fill={colors[groups.indexOf(point.group)%colors.length]} opacity=".78"><title>{`${point.group}: x ${format(point.x)}${unit?` ${unit}`:""}, y ${format(point.y)}${unit?` ${unit}`:""}`}</title></circle>)}<text x="321" y="342" textAnchor="middle" className="fill-muted-foreground text-[10px]">{residual?(basis==="prediction"?"Prediction":"Actual"):"Actual"}{unit?` (${unit})`:""}</text><text x="15" y="173" textAnchor="middle" transform="rotate(-90 15 173)" className="fill-muted-foreground text-[10px]">{residual?`Residual (${definition.replaceAll("_"," ")})`:"Prediction"}{unit?` (${unit})`:""}</text></svg><div className="absolute left-2 top-2 flex max-w-[85%] flex-wrap gap-1.5 rounded bg-background/80 px-2 py-1 text-[9px] backdrop-blur">{groups.map((group,index)=><span key={group} className="flex items-center gap-1"><i className="size-2 rounded-full" style={{background:colors[index%colors.length]}}/>{group}</span>)}{summaries.map(([key,value])=><span key={key} className="text-muted-foreground">{key.toUpperCase()} {format(Number(value))}</span>)}</div></section>;
}
function format(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:4}).format(value)}
