import {useEffect,useRef,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {api} from "@/api";
import type {DashboardWidget} from "@/lib/dashboard-widgets";
import {formatAxisValue,linearTicks} from "@/lib/chart-geometry";

const defaultColors=["#2563eb","#dc2626","#16a34a","#9333ea","#ea580c","#0891b2"];

export function RegressionDiagnosticsWidget({jobID,attemptID,widget,colors=defaultColors}:{jobID:string;attemptID:string;widget:DashboardWidget;colors?:readonly string[]}){
  const host=useRef<HTMLElement>(null),[size,setSize]=useState({width:620,height:350}),source=widget.sources.find(item=>item.kind==="table"),query=useQuery({queryKey:["job-table",jobID,attemptID,source?.name,"regression-diagnostics"],queryFn:()=>api.table(jobID,attemptID,source!.name,"limit=500"),enabled:!!source,staleTime:10_000}),table=query.data;
  useEffect(()=>{const element=host.current;if(!element||typeof ResizeObserver==="undefined")return;const resize=()=>{const bounds=element.getBoundingClientRect(),width=Math.max(120,Math.round(bounds.width)),height=Math.max(90,Math.round(bounds.height));setSize(current=>current.width===width&&current.height===height?current:{width,height})};resize();const observer=new ResizeObserver(resize);observer.observe(element);return()=>observer.disconnect()},[query.isLoading]);
  if(query.isLoading)return <div className="h-full animate-pulse rounded-md border bg-muted/20"/>;
  const points=table?.items.flatMap(item=>typeof item.values.actual==="number"&&typeof item.values.prediction==="number"?[{actual:item.values.actual,prediction:item.values.prediction,group:typeof item.values.group==="string"?item.values.group:"All"}]:[])??[];
  if(!table||!points.length)return <div role="status" className="grid h-full place-items-center rounded-md border text-xs text-muted-foreground">No regression observations.</div>;
  const definition=table.metadata?.residual_definition==="prediction_minus_actual"?"prediction_minus_actual":"actual_minus_prediction",residual=widget.type==="residual_plot",basis=widget.residual_x_axis??"prediction",plotted=points.map(point=>({x:residual?point[basis]:point.actual,y:residual?(definition==="actual_minus_prediction"?point.actual-point.prediction:point.prediction-point.actual):point.prediction,group:point.group})),left=52,right=18,top=34,bottom=38,availableWidth=Math.max(1,size.width-left-right),availableHeight=Math.max(1,size.height-top-bottom),plotWidth=residual?availableWidth:Math.min(availableWidth,availableHeight),plotHeight=residual?availableHeight:plotWidth,plotLeft=left+(availableWidth-plotWidth)/2,plotTop=top+(availableHeight-plotHeight)/2,plotBottom=plotTop+plotHeight,common=extent(plotted.flatMap(point=>[point.x,point.y]).concat(0)),xdomain=residual?extent(plotted.map(point=>point.x)):common,ydomain=residual?extent(plotted.map(point=>point.y).concat(0)):common,x=(value:number)=>plotLeft+(value-xdomain[0])/(xdomain[1]-xdomain[0])*plotWidth,y=(value:number)=>plotBottom-(value-ydomain[0])/(ydomain[1]-ydomain[0])*plotHeight,groups=[...new Set(plotted.map(point=>point.group))],unit=table.columns.find(column=>column.name==="actual")?.unit??"",summary=table.metadata?.summary;
  const summaries=summary&&typeof summary==="object"?Object.entries(summary):[];
  return <section ref={host} className="relative h-full min-h-0 overflow-hidden rounded-md border bg-card" aria-label={residual?"Residual plot":"Prediction versus actual plot"}><svg className="block size-full" width={size.width} height={size.height} viewBox={`0 0 ${size.width} ${size.height}`} role="img" aria-label={`${residual?"Residual":"Prediction versus actual"} scatter with ${plotted.length} points`} data-plot-size={`${Math.round(plotWidth)}x${Math.round(plotHeight)}`}>{linearTicks(ydomain,5).map(value=><g key={`y-${value}`}><line x1={plotLeft} x2={plotLeft+plotWidth} y1={y(value)} y2={y(value)} className="stroke-border" strokeDasharray="3 4"/><text x={plotLeft-7} y={y(value)+3} textAnchor="end" className="fill-muted-foreground text-[9px]">{formatAxisValue(value)}</text></g>)}{linearTicks(xdomain,5).map(value=><g key={`x-${value}`}><line x1={x(value)} x2={x(value)} y1={plotBottom} y2={plotBottom+4} className="stroke-muted-foreground"/><text x={x(value)} y={plotBottom+14} textAnchor="middle" className="fill-muted-foreground text-[9px]">{formatAxisValue(value)}</text></g>)}<line x1={plotLeft} y1={plotBottom} x2={plotLeft+plotWidth} y2={plotBottom} className="stroke-muted-foreground"/><line x1={plotLeft} y1={plotTop} x2={plotLeft} y2={plotBottom} className="stroke-muted-foreground"/>{residual?<line x1={plotLeft} y1={y(0)} x2={plotLeft+plotWidth} y2={y(0)} stroke="var(--muted-foreground)" strokeDasharray="5 5" opacity=".65"/>:<line x1={x(common[0])} y1={y(common[0])} x2={x(common[1])} y2={y(common[1])} stroke="var(--muted-foreground)" strokeDasharray="5 5" opacity=".65"/>}{plotted.map((point,index)=><circle key={index} cx={x(point.x)} cy={y(point.y)} r="4" fill={colors[groups.indexOf(point.group)%colors.length]} opacity=".78"><title>{`${point.group}: x ${format(point.x)}${unit?` ${unit}`:""}, y ${format(point.y)}${unit?` ${unit}`:""}`}</title></circle>)}<text x={plotLeft+plotWidth/2} y={size.height-5} textAnchor="middle" className="fill-muted-foreground text-[9px] font-medium">{residual?(basis==="prediction"?"Prediction":"Actual"):"Actual"}{unit?` (${unit})`:""}</text><text x="11" y={plotTop+plotHeight/2} textAnchor="middle" transform={`rotate(-90 11 ${plotTop+plotHeight/2})`} className="fill-muted-foreground text-[9px] font-medium">{residual?`Residual (${definition.replaceAll("_"," ")})`:"Prediction"}{unit?` (${unit})`:""}</text></svg><div className="absolute left-2 top-2 flex max-w-[85%] flex-wrap gap-1.5 rounded bg-background/80 px-2 py-1 text-[9px] backdrop-blur">{groups.map((group,index)=><span key={group} className="flex items-center gap-1"><i className="size-2 rounded-full" style={{background:colors[index%colors.length]}}/>{group}</span>)}{summaries.map(([key,value])=><span key={key} className="text-muted-foreground">{key.toUpperCase()} {format(Number(value))}</span>)}</div></section>;
}
function extent(values:number[]):[number,number]{const minimum=Math.min(...values),maximum=Math.max(...values),padding=Math.max((maximum-minimum)*.08,Math.abs(maximum)*.01,1e-9);return[minimum-padding,maximum+padding]}
function format(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:4}).format(value)}
