import { useId } from "react";
import { cn } from "@/lib/utils";

export function gaugePercent(value: number, total: number) { return total > 0 ? Math.min(100, Math.max(0, value / total * 100)) : null; }
export function gaugeTone(percent: number | null) { if (percent === null) return "text-muted-foreground"; if (percent < 50) return "text-emerald-500"; if (percent < 75) return "text-yellow-500"; if (percent < 90) return "text-orange-500"; return "text-red-500"; }

export function ResourceGauge({ label, value, total, display, icon: Icon, className }: { label: string; value: number; total: number; display: string; icon: React.ComponentType<{ className?: string }>; className?: string }) {
  const percent = gaugePercent(value, total), gradientID = `gauge-${useId().replace(/:/g, "")}`;
  return <div className={cn("relative h-full min-h-0 min-w-0 px-3 py-2 text-center", className)} role="meter" aria-label={`${label} utilization`} aria-valuemin={0} aria-valuemax={total || undefined} aria-valuenow={total ? value : undefined}><svg viewBox="0 0 120 72" className="mx-auto h-full min-h-0 w-full max-w-52 overflow-visible"><defs><linearGradient id={gradientID} x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stopColor="#22c55e"/><stop offset="55%" stopColor="#eab308"/><stop offset="78%" stopColor="#f97316"/><stop offset="100%" stopColor="#ef4444"/></linearGradient></defs><path d="M 15 60 A 45 45 0 1 1 105 60" fill="none" stroke="currentColor" strokeWidth="9" strokeLinecap="round" className="text-muted/70"/><path d="M 15 60 A 45 45 0 1 1 105 60" fill="none" stroke={`url(#${gradientID})`} strokeWidth="9" strokeLinecap="round" pathLength="100" strokeDasharray={`${percent ?? 0} 100`} className="transition-all duration-700"/></svg><div className="absolute inset-x-0 bottom-4"><div className="flex items-center justify-center gap-1.5 text-xs font-medium"><Icon className={cn("size-4", gaugeTone(percent))}/>{label}</div><div className="mt-1 font-mono text-sm font-semibold">{percent === null ? "N/A" : `${Math.round(percent)}%`}</div><div className="mt-0.5 text-[10px] text-muted-foreground">{display}</div></div></div>;
}
