import {useQuery} from "@tanstack/react-query";
import {api} from "@/api";
import {Button} from "@/components/ui/button";
import type {DashboardWidget} from "@/lib/dashboard-widgets";

export function ShapSummaryWidget({jobID,attemptID,widget,onUpdate}:{jobID:string;attemptID:string;widget:DashboardWidget;onUpdate:(widget:DashboardWidget)=>void}){
  const source=widget.sources.find(item=>item.kind==="table"),query=useQuery({queryKey:["job-table",jobID,attemptID,source?.name,"shap-summary"],queryFn:()=>api.table(jobID,attemptID,source!.name,"limit=500"),enabled:!!source,staleTime:10_000}),table=query.data,mode=widget.shap_mode??"beeswarm";
  if(query.isLoading)return <div className="h-full animate-pulse rounded-md border bg-muted/20"/>;
  const rows=table?.items.flatMap(item=>typeof item.values.feature==="string"&&typeof item.values.shap_value==="number"?[{feature:item.values.feature,shap:item.values.shap_value,featureValue:typeof item.values.feature_value==="number"?item.values.feature_value:undefined,sample:String(item.values.sample_id??"")}]:[])??[];
  if(!table||!rows.length)return <div role="status" className="grid h-full place-items-center rounded-md border text-xs text-muted-foreground">No SHAP attributions.</div>;
  const names=Array.isArray(table.metadata?.feature_names)?table.metadata.feature_names.map(String):[...new Set(rows.map(row=>row.feature))],means=Array.isArray(table.metadata?.mean_abs_shap)?table.metadata.mean_abs_shap.map(Number):names.map(name=>{const values=rows.filter(row=>row.feature===name);return values.reduce((sum,row)=>sum+Math.abs(row.shap),0)/Math.max(1,values.length)}),ordered=names.map((name,index)=>({name,mean:means[index]??0})).sort((a,b)=>b.mean-a.mean).slice(0,Math.min(20,names.length)),selected=new Set(ordered.map(item=>item.name)),points=rows.filter(row=>selected.has(row.feature)),max=Math.max(...points.map(row=>Math.abs(row.shap)),...ordered.map(item=>item.mean),1e-12),featureValues=points.flatMap(row=>row.featureValue==null?[]:[row.featureValue]),fmin=featureValues.length?Math.min(...featureValues):0,fmax=featureValues.length?Math.max(...featureValues):1;
  return <section className="relative h-full min-h-0 overflow-hidden rounded-md border bg-card" aria-label="SHAP summary"><Button variant="ghost" className="absolute right-2 top-2 z-10 h-6 px-2 text-[10px]" onClick={()=>onUpdate({...widget,shap_mode:mode==="beeswarm"?"bar":"beeswarm"})}>{mode==="beeswarm"?"Beeswarm":"Global bar"}</Button>{mode==="bar"?<div className="flex h-full flex-col gap-1 overflow-hidden px-3 pb-3 pt-9">{ordered.map(item=><div key={item.name} className="grid min-h-4 flex-1 grid-cols-[minmax(5rem,28%)_1fr_3.5rem] items-center gap-2 text-[10px]"><span className="truncate text-right" title={item.name}>{item.name}</span><div className="h-2.5 rounded bg-muted"><div className="h-full rounded bg-primary" style={{width:`${item.mean/max*100}%`}}/></div><span>{compact(item.mean)}</span></div>)}</div>:<svg className="h-full w-full" viewBox="0 0 640 380" preserveAspectRatio="none" role="img"><line x1="180" x2="610" y1="350" y2="350" className="stroke-border"/><line x1="395" x2="395" y1="28" y2="350" stroke="var(--muted-foreground)" strokeDasharray="4 4" opacity=".5"/>{ordered.map((item,index)=>{const y=35+index*(305/Math.max(1,ordered.length-1));return <g key={item.name}><text x="170" y={y+3} textAnchor="end" className="fill-foreground text-[9px]">{truncate(item.name,26)}</text>{points.filter(point=>point.feature===item.name).map((point,pointIndex)=>{const x=395+point.shap/max*205,jitter=((hash(point.sample)-.5)*Math.min(13,260/ordered.length)),color=point.featureValue==null?"var(--muted-foreground)":featureColor((point.featureValue-fmin)/(fmax-fmin||1));return <circle key={pointIndex} cx={x} cy={y+jitter} r="3.2" fill={color} opacity=".72"><title>{`${item.name}: SHAP ${compact(point.shap)}${point.featureValue==null?"":`, value ${compact(point.featureValue)}`}`}</title></circle>})}</g>})}<text x="395" y="372" textAnchor="middle" className="fill-muted-foreground text-[10px]">SHAP value</text></svg>}</section>;
}
function compact(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3,notation:Math.abs(value)>=10000?"compact":"standard"}).format(value)}
function truncate(value:string,length:number){return value.length>length?`${value.slice(0,length-1)}…`:value}
function hash(value:string){let result=0;for(const char of value)result=(result*31+char.charCodeAt(0))%997;return result/997}
function featureColor(value:number){const t=Math.max(0,Math.min(1,value));return `rgb(${Math.round(40+210*t)},${Math.round(110-50*t)},${Math.round(220-130*t)})`}
