import { useEffect,useMemo,useRef,useState } from "react";
import { chartRangePoints } from "@/components/time-series-chart";
import type { PlotSeries } from "@/components/observation-plot";
import type { DashboardSeriesAppearance,DashboardWidgetAppearance } from "@/lib/dashboard-widgets";
import type { TimeRange } from "@/lib/series";

const palettes={default:["#3b82f6","#8b5cf6","#f59e0b","#10b981","#ef4444","#06b6d4"],cool:["#2563eb","#7c3aed","#0891b2","#4f46e5","#0d9488","#9333ea"],warm:["#ea580c","#dc2626","#d97706","#db2777","#ca8a04","#e11d48"],monochrome:["#111827","#374151","#6b7280","#9ca3af","#4b5563","#1f2937"]} as const;

type Axis={id:string;label:string;unit:string;color:string;value?:number;minimum:number;maximum:number;normalized?:number;mode:"historical"|"manual"|"zero_to_one"};

export function StarPlot({title,series,range="all",appearance}:{title?:string;series:PlotSeries[];range?:TimeRange;appearance?:DashboardWidgetAppearance}){
  const host=useRef<HTMLDivElement>(null),[size,setSize]=useState({width:640,height:320});
  useEffect(()=>{const element=host.current;if(!element||typeof ResizeObserver==="undefined")return;const update=()=>{const bounds=element.getBoundingClientRect();setSize({width:Math.max(160,Math.round(bounds.width)),height:Math.max(120,Math.round(bounds.height))})};update();const observer=new ResizeObserver(update);observer.observe(element);return()=>observer.disconnect()},[]);
  const axes=useMemo(()=>buildStarAxes(series,range,appearance),[series,range,appearance]),available=axes.filter(axis=>axis.normalized!=null),complete=axes.length>=3&&available.length===axes.length;
  if(axes.length<3)return <section className="grid size-full place-items-center rounded-md border bg-card px-6 text-center text-sm text-muted-foreground">Select at least three numeric axes</section>;
  const width=size.width,height=size.height,cx=width/2,cy=height/2+4,radius=Math.max(24,Math.min(width*.32,height*.34)),point=(index:number,scale=1)=>{const angle=-Math.PI/2+index/axes.length*Math.PI*2;return{x:cx+Math.cos(angle)*radius*scale,y:cy+Math.sin(angle)*radius*scale,angle}},polygon=(scale:number)=>axes.map((_,index)=>{const item=point(index,scale);return`${item.x},${item.y}`}).join(" "),valuePolygon=axes.map((axis,index)=>{const item=point(index,axis.normalized??0);return`${item.x},${item.y}`}).join(" "),fill=palettes[appearance?.color_scheme??"default"][0];
  return <section className="group relative size-full min-h-0 overflow-hidden rounded-md border bg-card"><div className="pointer-events-none absolute left-2 top-1 z-10 max-w-[70%] transition-opacity group-hover:opacity-0">{title&&<div className="truncate text-[10px] font-medium">{title}</div>}{appearance?.subtitle&&<div className="truncate text-[9px] text-muted-foreground">{appearance.subtitle}</div>}</div>{!complete&&<div role="status" className="pointer-events-none absolute right-2 top-1 z-10 rounded bg-background/80 px-1.5 py-0.5 text-[9px] text-muted-foreground">{available.length}/{axes.length} axes available</div>}<div ref={host} className="absolute inset-0"><svg role="img" aria-label={`${title||"STAR plot"} with ${available.length} of ${axes.length} axes`} width={width} height={height} viewBox={`0 0 ${width} ${height}`} className="block size-full">
    {appearance?.show_grid!==false&&[.25,.5,.75,1].map(level=><polygon key={level} points={polygon(level)} fill="none" className="stroke-border" strokeWidth={level===1?1.25:.75}/>) }
    {complete&&<polygon points={valuePolygon} fill={fill} fillOpacity={.18*(appearance?.opacity??1)} stroke={fill} strokeOpacity={appearance?.opacity??1} strokeWidth="2"/>}
    {axes.map((axis,index)=>{const outer=point(index),label=point(index,1.14),anchor=Math.abs(Math.cos(label.angle))<.2?"middle":Math.cos(label.angle)>0?"start":"end";return <g key={axis.id}><line x1={cx} y1={cy} x2={outer.x} y2={outer.y} className="stroke-border" strokeWidth="1"/><text x={label.x} y={label.y-2} textAnchor={anchor} className="fill-foreground text-[10px]">{axis.label}</text><text x={label.x} y={label.y+10} textAnchor={anchor} className="fill-muted-foreground text-[8px]">{axis.unit||"unitless"} · {compact(axis.minimum)}–{compact(axis.maximum)}</text>{axis.normalized!=null&&(()=>{const valuePoint=point(index,axis.normalized);return <circle cx={valuePoint.x} cy={valuePoint.y} r="3.5" fill={axis.color} className="stroke-background" strokeWidth="1.5"><title>{axis.label}: {compact(axis.value!)} {axis.unit} · range {compact(axis.minimum)}–{compact(axis.maximum)} ({axis.mode})</title></circle>})()}</g>})}
  </svg></div></section>;
}

export function buildStarAxes(series:PlotSeries[],range:TimeRange,appearance?:DashboardWidgetAppearance):Axis[]{const palette=palettes[appearance?.color_scheme??"default"];return series.slice(0,16).map((item,index)=>{const configured=appearance?.series?.[item.id],points=chartRangePoints(item.points,range).map(point=>point.value).filter(Number.isFinite),value=points.at(-1),bounds=starBounds(points,configured),normalized=value==null?undefined:clamp((value-bounds[0])/(bounds[1]-bounds[0]),0,1);return{id:item.id,label:configured?.label||item.title,unit:configured?.unit||item.unit,color:configured?.color||item.color||palette[index%palette.length],value,minimum:bounds[0],maximum:bounds[1],normalized,mode:configured?.normalization??"historical"}})}
function starBounds(values:number[],appearance?:DashboardSeriesAppearance):[number,number]{if(appearance?.normalization==="manual"&&Number.isFinite(appearance.min)&&Number.isFinite(appearance.max)&&appearance.min!<appearance.max!)return[appearance.min!,appearance.max!];if(appearance?.normalization==="zero_to_one")return[0,1];if(!values.length)return[0,1];const minimum=Math.min(0,...values),maximum=Math.max(0,...values);if(minimum!==maximum)return[minimum,maximum];return minimum===0?[0,1]:[Math.min(0,minimum),Math.max(1,maximum)]}
function compact(value:number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3,notation:Math.abs(value)>=10000?"compact":"standard"}).format(value)}
function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value))}
