import {useQuery} from "@tanstack/react-query";
import {api} from "@/api";
import type {DashboardWidget,DashboardWidgetType} from "@/lib/dashboard-widgets";
import type {TablePage} from "@/types";
import {axisTitle,formatAxisValue,linearTicks} from "@/lib/chart-geometry";

type TabularChartType="bubble_chart"|"parallel_coordinates"|"pie_chart"|"donut_chart"|"treemap"|"waterfall";
const defaultColors=["#2563eb","#16a34a","#f59e0b","#dc2626","#9333ea","#0891b2","#db2777","#65a30d"];

export function TabularChartWidget({jobID,attemptID,widget,colors=defaultColors,onUpdate}:{jobID:string;attemptID:string;widget:DashboardWidget;colors?:readonly string[];onUpdate:(widget:DashboardWidget)=>void}){
  const source=widget.sources[0],table=useQuery({queryKey:["job-table",jobID,attemptID,source?.name,"chart"],queryFn:()=>api.table(jobID,attemptID,source!.name,"limit=500"),enabled:!!source});
  if(table.isLoading)return <div className="h-full animate-pulse rounded-md border bg-muted/20"/>;
  if(!table.data)return <div role="status" className="grid h-full place-items-center rounded-md border text-xs text-muted-foreground">No compatible tabular snapshot.</div>;
  const type=widget.type as TabularChartType,numeric=table.data.columns.filter(column=>column.type==="number"||column.type==="integer").map(column=>column.name),categorical=table.data.columns.filter(column=>column.type==="string"||column.type==="boolean").map(column=>column.name),defaults=defaultColumns(type,numeric,categorical),columns=(widget.table_columns?.filter(name=>table.data!.columns.some(column=>column.name===name)).length?widget.table_columns:defaults)??[];
  return <section className="group relative h-full min-h-0 overflow-hidden rounded-md border bg-card" aria-label={widgetLabel(type)}><ChartOptions widget={widget} type={type} onUpdate={onUpdate}/><ColumnControls type={type} columns={columns} numeric={numeric} categorical={categorical} onChange={table_columns=>onUpdate({...widget,table_columns})}/>{type==="bubble_chart"?<Bubble table={table.data} columns={columns} colors={colors}/>:type==="parallel_coordinates"?<Parallel table={table.data} columns={columns} normalize={widget.normalize_axes!==false} colors={colors}/>:type==="pie_chart"||type==="donut_chart"?<Pie table={table.data} columns={columns} donut={type==="donut_chart"} limit={widget.category_limit??12} other={widget.group_small_categories!==false} colors={colors}/>:type==="treemap"?<Treemap table={table.data} columns={columns} colors={colors}/>:<Waterfall table={table.data} columns={columns} colors={colors}/>}</section>
}

function ChartOptions({widget,type,onUpdate}:{widget:DashboardWidget;type:TabularChartType;onUpdate:(widget:DashboardWidget)=>void}){if(type==="parallel_coordinates")return <label className="absolute bottom-1 left-1 z-20 flex items-center gap-1 rounded border bg-background/90 px-1.5 py-1 text-[9px] opacity-0 shadow transition-opacity group-hover:opacity-100 focus-within:opacity-100"><input type="checkbox" checked={widget.normalize_axes!==false} onChange={event=>onUpdate({...widget,normalize_axes:event.target.checked})}/>Normalize axes</label>;if(type!=="pie_chart"&&type!=="donut_chart")return null;return <div className="absolute bottom-1 left-1 z-20 flex items-center gap-1 rounded border bg-background/90 px-1.5 py-1 text-[9px] opacity-0 shadow transition-opacity group-hover:opacity-100 focus-within:opacity-100"><label>Categories <input aria-label="Category limit" type="number" min="2" max="64" value={widget.category_limit??12} onChange={event=>onUpdate({...widget,category_limit:Math.max(2,Math.min(64,Number(event.target.value)||12))})} className="h-5 w-10 rounded border bg-background px-1"/></label><label className="flex items-center gap-1"><input type="checkbox" checked={widget.group_small_categories!==false} onChange={event=>onUpdate({...widget,group_small_categories:event.target.checked})}/>Other</label></div>}
function ColumnControls({type,columns,numeric,categorical,onChange}:{type:TabularChartType;columns:string[];numeric:string[];categorical:string[];onChange:(columns:string[])=>void}){const all=[...numeric,...categorical],count=type==="bubble_chart"?4:type==="parallel_coordinates"?Math.min(8,Math.max(2,columns.length)):type==="treemap"?3:2;return <div className="absolute right-1 top-1 z-20 flex max-w-[85%] gap-1 opacity-0 transition-opacity group-hover:opacity-100 focus-within:opacity-100">{Array.from({length:count},(_,index)=>{const choices=type==="bubble_chart"&&index<3?numeric:all;return <select key={index} aria-label={type==="bubble_chart"?["X dimension","Y dimension","Size dimension","Color or group"][index]:`Dimension ${index+1}`} value={columns[index]??""} onChange={event=>{const next=[...columns];next[index]=event.target.value;onChange(next.filter(Boolean))}} className="h-6 max-w-28 rounded border bg-background/90 px-1 text-[9px] shadow"><option value="">{type==="bubble_chart"&&index===3?"No group":"Select"}</option>{choices.map(name=><option key={name} value={name}>{name}</option>)}</select>})}</div>}
function Bubble({table,columns,colors}:{table:TablePage;columns:string[];colors:readonly string[]}){const [xName,yName,sizeName,groupName]=columns,rows=table.items.flatMap(item=>[xName,yName,sizeName].every(name=>typeof item.values[name]==="number")?[item.values]:[]),xs=rows.map(row=>row[xName] as number),ys=rows.map(row=>row[yName] as number),sizes=rows.map(row=>row[sizeName] as number),groups=[...new Set(rows.map(row=>String(groupName?row[groupName]:"default")))],xDomain:[number,number]=xs.length?[Math.min(...xs),Math.max(...xs)]:[0,1],yDomain:[number,number]=ys.length?[Math.min(...ys),Math.max(...ys)]:[0,1],scale=(value:number,domain:readonly number[],start:number,length:number)=>start+(value-domain[0])/(domain[1]-domain[0]||1)*length,x=(value:number)=>scale(value,xDomain,58,532),y=(value:number)=>318-scale(value,yDomain,0,288),unit=(name:string)=>table.columns.find(column=>column.name===name)?.unit;return <svg className="h-full w-full" viewBox="0 0 620 360" preserveAspectRatio="xMidYMid meet" role="img">{linearTicks(yDomain,5).map(value=><g key={`y-${value}`}><line x1="58" x2="590" y1={y(value)} y2={y(value)} className="stroke-border" strokeDasharray="3 4"/><text x="51" y={y(value)+3} textAnchor="end" className="fill-muted-foreground text-[9px]">{formatAxisValue(value)}</text></g>)}{linearTicks(xDomain,5).map(value=><g key={`x-${value}`}><line x1={x(value)} x2={x(value)} y1="318" y2="322" className="stroke-muted-foreground"/><text x={x(value)} y="333" textAnchor="middle" className="fill-muted-foreground text-[9px]">{formatAxisValue(value)}</text></g>)}<line x1="58" y1="318" x2="590" y2="318" className="stroke-muted-foreground"/><line x1="58" y1="30" x2="58" y2="318" className="stroke-muted-foreground"/><text x="324" y="350" textAnchor="middle" className="fill-muted-foreground text-[9px] font-medium">{axisTitle(xName,unit(xName))}</text><text x="11" y="174" textAnchor="middle" transform="rotate(-90 11 174)" className="fill-muted-foreground text-[9px] font-medium">{axisTitle(yName,unit(yName))}</text>{rows.map((row,index)=>{const group=String(groupName?row[groupName]:"default");return <circle key={index} cx={x(row[xName] as number)} cy={y(row[yName] as number)} r={4+scale(row[sizeName] as number,[Math.min(...sizes),Math.max(...sizes)],0,14)} fill={colors[groups.indexOf(group)%colors.length]} fillOpacity=".65"><title>{`${xName}: ${row[xName]}, ${yName}: ${row[yName]}, ${sizeName}: ${row[sizeName]}${groupName?`, ${groupName}: ${group}`:""}`}</title></circle>})}</svg>}
function Parallel({table,columns,normalize,colors}:{table:TablePage;columns:string[];normalize:boolean;colors:readonly string[]}){const axes=columns.slice(0,8),rows=table.items.slice(0,500),numericRanges=Object.fromEntries(axes.map(name=>{const values=rows.map(row=>row.values[name]).filter((value):value is number=>typeof value==="number");return[name,values.length?[Math.min(...values),Math.max(...values)]:[0,1]]})),label=(name:string)=>{const unit=table.columns.find(column=>column.name===name)?.unit;return unit?`${name} (${unit})`:name},y=(name:string,value:unknown)=>{if(typeof value==="number"){const [min,max]=numericRanges[name];return 315-(value-min)/(max-min||1)*280}const values=[...new Set(rows.map(row=>String(row.values[name])))];return 315-values.indexOf(String(value))/Math.max(1,values.length-1)*280};return <svg className="h-full w-full" viewBox="0 0 620 350" preserveAspectRatio="xMidYMid meet" role="img">{axes.map((name,index)=>{const x=45+index*530/Math.max(1,axes.length-1),range=numericRanges[name] as [number,number];return <g key={name}><line x1={x} y1="35" x2={x} y2="315" className="stroke-border"/><text x={x} y="28" textAnchor="middle" className="fill-muted-foreground text-[8px]">{formatAxisValue(range[1])}</text><text x={x} y="326" textAnchor="middle" className="fill-muted-foreground text-[8px]">{formatAxisValue(range[0])}</text><text x={x} y="343" textAnchor="middle" className="fill-muted-foreground text-[9px] font-medium">{label(name)}</text></g>})}{rows.map((row,index)=><polyline key={row.cursor} points={axes.map((name,axis)=>`${45+axis*530/Math.max(1,axes.length-1)},${y(name,row.values[name])}`).join(" ")} fill="none" stroke={colors[index%colors.length]} strokeOpacity=".18" strokeWidth="1"><title>{axes.map(name=>`${label(name)}: ${String(row.values[name])}`).join(", ")}{normalize?" · normalized":""}</title></polyline>)}</svg>}
function Pie({table,columns,donut,limit,other,colors}:{table:TablePage;columns:string[];donut:boolean;limit:number;other:boolean;colors:readonly string[]}){const [category,value]=columns,totals=new Map<string,number>();for(const row of table.items){const amount=row.values[value];if(typeof amount==="number"&&amount>=0)totals.set(String(row.values[category]),(totals.get(String(row.values[category]))??0)+amount)}let items=[...totals].sort((a,b)=>b[1]-a[1]),rest=items.slice(limit).reduce((sum,item)=>sum+item[1],0);items=items.slice(0,limit);if(other&&rest>0)items.push(["Other",rest]);const total=items.reduce((sum,item)=>sum+item[1],0),segments:string[]=[];let angle=-Math.PI/2;for(const [,amount] of items){const next=angle+amount/(total||1)*Math.PI*2;segments.push(arc(310,175,120,angle,next));angle=next}return <svg className="h-full w-full" viewBox="0 0 620 350" preserveAspectRatio="xMidYMid meet" role="img">{segments.map((path,index)=><path key={items[index][0]} d={path} fill={colors[index%colors.length]} stroke="var(--background)"><title>{`${items[index][0]}: ${items[index][1]} (${(items[index][1]/(total||1)*100).toFixed(1)}%)`}</title></path>)}{donut&&<circle cx="310" cy="175" r="62" fill="var(--card)"/>}</svg>}
function Treemap({table,columns,colors}:{table:TablePage;columns:string[];colors:readonly string[]}){const [id,parent,value]=columns,rows=table.items.flatMap(row=>typeof row.values[value]==="number"&&row.values[value]>=0?[{id:String(row.values[id]),parent:row.values[parent]==null?"":String(row.values[parent]),value:row.values[value] as number}]:[]),roots=rows.filter(row=>!row.parent),rectangles=layoutTreemap(roots,rows,0,0,620,350,0);return <svg className="h-full w-full" viewBox="0 0 620 350" preserveAspectRatio="xMidYMid meet" role="img">{rectangles.map((item,index)=><g key={item.id}><rect x={item.x} y={item.y} width={item.width} height={item.height} fill={colors[item.depth%colors.length]} fillOpacity={Math.max(.42,.82-item.depth*.08)} stroke="var(--background)"/>{item.width>42&&item.height>20&&<text x={item.x+5} y={item.y+15} className="fill-white text-[9px]">{item.id}</text>}<title>{`${item.id}: ${item.value}`}</title></g>)}</svg>}
type TreemapNode={id:string;parent:string;value:number};
type TreemapRect=TreemapNode&{x:number;y:number;width:number;height:number;depth:number};
function layoutTreemap(nodes:TreemapNode[],all:TreemapNode[],x:number,y:number,width:number,height:number,depth:number):TreemapRect[]{const total=nodes.reduce((sum,node)=>sum+node.value,0)||nodes.length,vertical=depth%2===0,rectangles:TreemapRect[]=[];let offset=0;for(const node of nodes){const share=(node.value||1)/total,span=(vertical?width:height)*share,rect={...node,x:vertical?x+offset:x,y:vertical?y:y+offset,width:vertical?span:width,height:vertical?height:span,depth};rectangles.push(rect);const children=all.filter(candidate=>candidate.parent===node.id);if(children.length&&rect.width>12&&rect.height>12)rectangles.push(...layoutTreemap(children,all,rect.x+3,rect.y+20,Math.max(1,rect.width-6),Math.max(1,rect.height-23),depth+1));offset+=span}return rectangles}
function Waterfall({table,columns,colors}:{table:TablePage;columns:string[];colors:readonly string[]}){const [label,value]=columns,rows=table.items.flatMap(row=>typeof row.values[value]==="number"?[{label:String(row.values[label]),value:row.values[value] as number,kind:String(row.values.kind??"contribution")}]:[]);let running=0;const points=rows.map(row=>{const absolute=row.kind==="initial"||row.kind==="total"||row.kind==="subtotal"||row.kind==="final",start=absolute?0:running;if(absolute)running=row.value;else running+=row.value;return{...row,start,end:running}}),extent=Math.max(1,...points.flatMap(point=>[Math.abs(point.start),Math.abs(point.end)])),zero=175,y=(value:number)=>zero-value/extent*145,width=520/Math.max(1,points.length),unit=table.columns.find(column=>column.name===value)?.unit;return <svg className="h-full w-full" viewBox="0 0 620 350" preserveAspectRatio="xMidYMid meet" role="img">{linearTicks([-extent,extent],5).map(tick=><g key={tick}><line x1="58" x2="590" y1={y(tick)} y2={y(tick)} className="stroke-border" strokeDasharray="3 4"/><text x="51" y={y(tick)+3} textAnchor="end" className="fill-muted-foreground text-[8px]">{formatAxisValue(tick)}</text></g>)}<line x1="58" y1={zero} x2="590" y2={zero} className="stroke-muted-foreground"/><text x="12" y="175" textAnchor="middle" transform="rotate(-90 12 175)" className="fill-muted-foreground text-[9px] font-medium">{axisTitle(value,unit)}</text>{points.map((point,index)=>{const top=Math.min(y(point.start),y(point.end)),height=Math.max(2,Math.abs(y(point.end)-y(point.start))),absolute=point.kind!=="contribution";return <g key={index}><rect x={63+index*width} y={top} width={Math.max(2,width-5)} height={height} fill={absolute?colors[0]:point.value>=0?colors[1%colors.length]:colors[2%colors.length]}><title>{`${point.label}: ${point.value} · ${point.kind}`}</title></rect><text x={63+(index+.5)*width} y="335" textAnchor="middle" className="fill-muted-foreground text-[8px]">{point.label}</text></g>})}</svg>}
function defaultColumns(type:DashboardWidgetType,numeric:string[],categorical:string[]){if(type==="bubble_chart")return[...numeric.slice(0,3),categorical[0]].filter(Boolean);if(type==="parallel_coordinates")return[...numeric,...categorical].slice(0,6);if(type==="treemap")return[categorical[0],categorical[1],numeric[0]].filter(Boolean);return[categorical[0],numeric[0]].filter(Boolean)}
function widgetLabel(type:TabularChartType){return type.split("_").map(value=>value[0].toUpperCase()+value.slice(1)).join(" ")}
function arc(cx:number,cy:number,r:number,start:number,end:number){const x1=cx+r*Math.cos(start),y1=cy+r*Math.sin(start),x2=cx+r*Math.cos(end),y2=cy+r*Math.sin(end),large=end-start>Math.PI?1:0;return`M ${cx} ${cy} L ${x1} ${y1} A ${r} ${r} 0 ${large} 1 ${x2} ${y2} Z`}
