import type { Dispatch, SetStateAction } from "react";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { DashboardAxisAppearance, DashboardSeriesAppearance, DashboardWidget, DashboardWidgetAppearance } from "@/lib/dashboard-widgets";
import {supportsGradient} from "@/lib/dashboard-palettes";

export type AppearanceSourceOption={key:string;label:string;unit?:string;color?:string};

export function WidgetAppearanceEditor({draft,sources,onChange}:{draft:DashboardWidget;sources:AppearanceSourceOption[];onChange:Dispatch<SetStateAction<DashboardWidget>>}){
  const line=draft.type==="lineplot"||draft.type==="loss_curve"||draft.type==="learning_curve"||draft.type==="anomaly_timeline",plot=line||draft.type==="barplot"||draft.type==="area_chart"||draft.type==="stacked_bar"||draft.type==="scatterplot"||draft.type==="starplot";
  const heatmap=draft.type==="heatmap"||draft.type==="correlation_heatmap";
  const scalar=draft.type==="kpi"||draft.type==="gauge";
  const appearance=draft.appearance??{schema_version:1 as const};
  const set=<K extends keyof DashboardWidgetAppearance>(key:K,value:DashboardWidgetAppearance[K])=>onChange(current=>({...current,appearance:{schema_version:1,...current.appearance,[key]:value}}));
  return <div className="space-y-4"><fieldset className="rounded-md border p-3"><legend className="px-1 text-sm font-medium">Common</legend><div className="grid gap-3 sm:grid-cols-2"><Field label="Title"><Input aria-label="Widget title" maxLength={120} value={draft.title??""} onChange={event=>onChange(current=>({...current,title:event.target.value}))} placeholder={scalar?"Automatic from source":"No title"}/></Field><Field label="Subtitle"><Input aria-label="Widget subtitle" maxLength={160} value={appearance.subtitle??""} onChange={event=>set("subtitle",event.target.value||undefined)} placeholder="No subtitle"/></Field></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><Field label="Padding"><Select value={appearance.padding??"normal"} onValueChange={value=>set("padding",value as DashboardWidgetAppearance["padding"])}><SelectTrigger aria-label="Widget padding"><SelectValue/></SelectTrigger><SelectContent>{["none","compact","normal"].map(value=><SelectItem key={value} value={value}>{titleCase(value)}</SelectItem>)}</SelectContent></Select></Field><ColorField label="Background" value={appearance.background_color??"#ffffff"} onChange={value=>set("background_color",value)}/><ColorField label="Accent" value={appearance.accent_color??"#2563eb"} onChange={value=>set("accent_color",value)}/></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><ColorField label="Border" value={appearance.border_color??"#cbd5e1"} onChange={value=>set("border_color",value)}/><ColorField label="Text" value={appearance.text_color??"#0f172a"} onChange={value=>set("text_color",value)}/></div></fieldset>
    {(plot||heatmap||draft.type==="confusion_matrix")&&<fieldset className="rounded-md border p-3"><legend className="px-1 text-sm font-medium">Visualization</legend><div className="space-y-4">
      {heatmap&&<HeatmapAppearance appearance={appearance} correlation={draft.type==="correlation_heatmap"} set={set}/>} {draft.type==="confusion_matrix"&&<Field label="Initial values"><Select value={appearance.matrix_mode??"absolute"} onValueChange={value=>set("matrix_mode",value as DashboardWidgetAppearance["matrix_mode"])}><SelectTrigger aria-label="Matrix mode"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="absolute">Absolute</SelectItem><SelectItem value="normalized">Normalized</SelectItem></SelectContent></Select></Field>}
      {(heatmap||draft.type==="confusion_matrix")&&<div className="grid gap-3 sm:grid-cols-3"><label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={appearance.show_labels??true} onChange={event=>set("show_labels",event.target.checked)}/>Show labels</label><label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={appearance.show_values??true} onChange={event=>set("show_values",event.target.checked)}/>Show values</label><NumberField label="Cell gap" value={appearance.cell_gap??1} min={0} max={8} step={.5} onValue={value=>set("cell_gap",value)}/></div>}
      {plot&&<>
      <div className="grid gap-3 sm:grid-cols-3"><Field label="Color scheme"><Select value={appearance.color_scheme??"default"} onValueChange={value=>set("color_scheme",value as DashboardWidgetAppearance["color_scheme"])}><SelectTrigger aria-label="Color scheme"><SelectValue/></SelectTrigger><SelectContent>{["default","cool","warm","monochrome"].map(value=><SelectItem key={value} value={value}>{titleCase(value)}</SelectItem>)}</SelectContent></Select></Field><Field label="Legend"><Select value={appearance.legend??"auto"} onValueChange={value=>set("legend",value as DashboardWidgetAppearance["legend"])}><SelectTrigger aria-label="Legend"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="auto">Available on demand</SelectItem><SelectItem value="open">Initially open</SelectItem><SelectItem value="hidden">Hidden</SelectItem></SelectContent></Select></Field><Field label="Opacity"><div className="flex h-9 items-center gap-2"><input aria-label="Plot opacity" type="range" min="0.05" max="1" step="0.05" value={appearance.opacity??1} onChange={event=>set("opacity",Number(event.target.value))} className="min-w-0 flex-1"/><span className="w-9 text-right text-xs tabular-nums">{Math.round((appearance.opacity??1)*100)}%</span></div></Field></div>
      <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={appearance.show_grid??true} onChange={event=>set("show_grid",event.target.checked)}/>Show grid</label>
      {draft.type==="area_chart"&&<Field label="Area mode"><Select value={appearance.stack_mode??"overlap"} onValueChange={value=>set("stack_mode",value as DashboardWidgetAppearance["stack_mode"])}><SelectTrigger aria-label="Area mode"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="overlap">Overlap · missing values are gaps</SelectItem><SelectItem value="stacked" disabled={new Set(sources.map(source=>source.unit||"unitless")).size>1}>Stacked · missing values are zero</SelectItem></SelectContent></Select>{new Set(sources.map(source=>source.unit||"unitless")).size>1&&<span className="text-[11px] text-muted-foreground">Stacking requires compatible units.</span>}</Field>}
      {line&&<div className="grid gap-3 sm:grid-cols-3"><Field label="Line style"><Select value={appearance.line_style??"solid"} onValueChange={value=>set("line_style",value as DashboardWidgetAppearance["line_style"])}><SelectTrigger aria-label="Line style"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="solid">Solid</SelectItem><SelectItem value="dashed">Dashed</SelectItem><SelectItem value="dotted">Dotted</SelectItem></SelectContent></Select></Field><NumberField label="Line width" value={appearance.line_width??2} min={.5} max={12} step={.5} onValue={value=>set("line_width",value)}/><PointControls appearance={appearance} set={set}/></div>}
      {draft.type==="scatterplot"&&<div className="grid gap-3 sm:grid-cols-2"><PointControls appearance={appearance} set={set}/></div>}
      {draft.type!=="starplot"&&<div className="grid gap-3 lg:grid-cols-2"><AxisEditor axis="X" value={appearance.x_axis} logDisabled={draft.type!=="scatterplot"&&draft.x_axis!=="step"} onChange={value=>set("x_axis",value)}/><AxisEditor axis="Y" value={appearance.y_axis} onChange={value=>set("y_axis",value)}/></div>}
      {sources.length>0&&<details className="rounded-md border" open={draft.type==="starplot"}><summary className="cursor-pointer px-3 py-2 text-sm font-medium">{draft.type==="starplot"?"Radial axes, units and ranges":"Series labels, units and colors"}</summary><div className="space-y-2 border-t p-3">{sources.map(source=><SeriesEditor key={source.key} source={source} value={appearance.series?.[source.key]} star={draft.type==="starplot"} onChange={value=>set("series",replaceSeries(appearance.series,source.key,value))}/>)}</div></details>}
      </>}</div></fieldset>}
    {supportsGradient(draft.type)&&<fieldset className="rounded-md border p-3"><legend className="px-1 text-sm font-medium">Color gradient</legend><GradientEditor appearance={appearance} set={set}/></fieldset>}
    {draft.type==="logs"&&<fieldset className="grid gap-3 rounded-md border p-3 sm:grid-cols-2"><legend className="px-1 text-sm font-medium">Console</legend><NumberField label="Font size" value={appearance.font_size??12} min={8} max={24} step={1} onValue={value=>set("font_size",value)}/><label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={appearance.wrap_lines??true} onChange={event=>set("wrap_lines",event.target.checked)}/>Wrap lines</label></fieldset>}
    {(draft.type==="data_grid"||draft.type==="progress")&&<fieldset className="grid gap-3 rounded-md border p-3 sm:grid-cols-2"><legend className="px-1 text-sm font-medium">Density</legend><Field label="Spacing"><Select value={appearance.density??"normal"} onValueChange={value=>set("density",value as DashboardWidgetAppearance["density"])}><SelectTrigger aria-label="Widget density"><SelectValue/></SelectTrigger><SelectContent>{["compact","normal","comfortable"].map(value=><SelectItem key={value} value={value}>{titleCase(value)}</SelectItem>)}</SelectContent></Select></Field>{draft.type==="data_grid"&&<label className="flex items-center gap-2 self-end rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={appearance.striped_rows??true} onChange={event=>set("striped_rows",event.target.checked)}/>Striped rows</label>}</fieldset>}
    {!plot&&sources.length>0&&<fieldset className="rounded-md border p-3"><legend className="px-1 text-sm font-medium">Data colors</legend><div className="space-y-2">{sources.map(source=><SeriesEditor key={source.key} source={source} value={appearance.series?.[source.key]} onChange={value=>set("series",replaceSeries(appearance.series,source.key,value))}/>)}</div></fieldset>}
  </div>;
}

function ColorField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="grid gap-1 text-xs text-muted-foreground">{label}<div className="flex h-9 items-center gap-2 rounded-md border px-2"><input aria-label={`${label} color`} type="color" value={value} onChange={event=>onChange(event.target.value)} className="size-6 cursor-pointer border-0 bg-transparent p-0"/><span className="font-mono text-[10px] uppercase">{value}</span></div></label>}
function GradientEditor({appearance,set}:{appearance:DashboardWidgetAppearance;set:<K extends keyof DashboardWidgetAppearance>(key:K,value:DashboardWidgetAppearance[K])=>void}){const stops=appearance.gradient??[{offset:0,color:"#16a34a"},{offset:.5,color:"#f59e0b"},{offset:1,color:"#dc2626"}];return <div className="space-y-2"><div className="h-5 rounded" style={{background:`linear-gradient(90deg,${stops.map(stop=>`${stop.color} ${stop.offset*100}%`).join(",")})`}}/>{stops.map((stop,index)=><div key={index} className="grid grid-cols-[1fr_5rem] gap-2"><ColorField label={`Stop ${index+1}`} value={stop.color} onChange={color=>set("gradient",stops.map((item,i)=>i===index?{...item,color}:item))}/><NumberField label="Position %" value={Math.round(stop.offset*100)} min={0} max={100} step={1} onValue={value=>set("gradient",stops.map((item,i)=>i===index?{...item,offset:value/100}:item).sort((a,b)=>a.offset-b.offset))}/></div>)}</div>}

function HeatmapAppearance({appearance,correlation,set}:{appearance:DashboardWidgetAppearance;correlation:boolean;set:<K extends keyof DashboardWidgetAppearance>(key:K,value:DashboardWidgetAppearance[K])=>void}){const manual=appearance.heatmap_scale==="manual",minimum=appearance.heatmap_min??(correlation?-1:0),maximum=appearance.heatmap_max??1;return <div className="grid gap-3 sm:grid-cols-3"><Field label="Color scale"><Select value={appearance.heatmap_scale??"auto"} onValueChange={value=>{const mode=value as "auto"|"manual";set("heatmap_scale",mode);if(mode==="manual"){set("heatmap_min",minimum);set("heatmap_max",maximum)}else{set("heatmap_min",undefined);set("heatmap_max",undefined)}}}><SelectTrigger aria-label="Heatmap color scale"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="auto">Automatic{correlation?" (-1 to 1)":""}</SelectItem><SelectItem value="manual">Manual</SelectItem></SelectContent></Select></Field><Field label="Palette"><Select value={appearance.heatmap_palette??(correlation?"diverging":"sequential")} onValueChange={value=>set("heatmap_palette",value as "sequential"|"diverging")}><SelectTrigger aria-label="Heatmap palette"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="sequential">Sequential</SelectItem><SelectItem value="diverging">Diverging</SelectItem></SelectContent></Select></Field>{manual&&<div className="grid grid-cols-2 gap-2"><NumberField label="Minimum" value={minimum} step="any" onValue={value=>set("heatmap_min",Math.min(value,maximum-Number.EPSILON))}/><NumberField label="Maximum" value={maximum} step="any" onValue={value=>set("heatmap_max",Math.max(value,minimum+Number.EPSILON))}/></div>}</div>}

function AxisEditor({axis,value,onChange,logDisabled=false}:{axis:"X"|"Y";value?:DashboardAxisAppearance;onChange:(value:DashboardAxisAppearance)=>void;logDisabled?:boolean}){const current=value??{},manual=current.range==="manual",epsilon=current.scale==="log"?.000001:Number.EPSILON;const update=<K extends keyof DashboardAxisAppearance>(key:K,next:DashboardAxisAppearance[K])=>onChange({...current,[key]:next});const scale=(next:"linear"|"log")=>onChange(next==="log"&&manual?{...current,scale:next,min:Math.max(epsilon,current.min??epsilon),max:Math.max(1,current.max??1)}:{...current,scale:next});return <fieldset className="grid gap-3 rounded-md border p-3 sm:grid-cols-2"><legend className="px-1 text-xs font-medium text-muted-foreground">{axis} axis</legend><Field label="Label"><Input aria-label={`${axis} axis label`} maxLength={80} value={current.label??""} onChange={event=>update("label",event.target.value||undefined)} placeholder="Automatic"/></Field><Field label="Unit"><Input aria-label={`${axis} axis unit`} maxLength={64} value={current.unit??""} onChange={event=>update("unit",event.target.value||undefined)} placeholder="Source unit"/></Field><Field label="Scale"><Select value={current.scale??"linear"} onValueChange={next=>scale(next as "linear"|"log")}><SelectTrigger aria-label={`${axis} axis scale`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="linear">Linear</SelectItem><SelectItem value="log" disabled={logDisabled}>Logarithmic</SelectItem></SelectContent></Select></Field><Field label="Range"><Select value={current.range??"auto"} onValueChange={next=>onChange(next==="manual"?{...current,range:"manual",min:current.min??(current.scale==="log"?.01:0),max:current.max??1}:{...current,range:"auto",min:undefined,max:undefined})}><SelectTrigger aria-label={`${axis} axis range`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="auto">Automatic</SelectItem><SelectItem value="manual">Manual</SelectItem></SelectContent></Select></Field>{manual&&<><NumberField label="Minimum" ariaLabel={`${axis} axis minimum`} value={current.min??0} step="any" onValue={next=>onChange({...current,min:current.scale==="log"?Math.max(epsilon,next):next,max:Math.max(current.max??next+1,next+epsilon)})}/><NumberField label="Maximum" ariaLabel={`${axis} axis maximum`} value={current.max??1} step="any" onValue={next=>{const maximum=current.scale==="log"?Math.max(epsilon*2,next):next;onChange({...current,min:Math.min(current.min??maximum-1,maximum-epsilon),max:maximum})}}/></>}</fieldset>}
function SeriesEditor({source,value,onChange,star=false}:{source:AppearanceSourceOption;value?:DashboardSeriesAppearance;onChange:(value?:DashboardSeriesAppearance)=>void;star?:boolean}){const update=<K extends keyof DashboardSeriesAppearance>(key:K,next:DashboardSeriesAppearance[K])=>{const result={...value,[key]:next};onChange(Object.values(result).some(item=>item!==undefined&&item!=="")?result:undefined)},mode=value?.normalization??"historical",minimum=value?.min??0,maximum=value?.max??1;return <div className="space-y-2 rounded-md bg-muted/35 p-2"><div className="grid items-end gap-2 sm:grid-cols-[minmax(8rem,1fr)_minmax(7rem,1fr)_minmax(6rem,.7fr)_2.5rem]"><div className="min-w-0"><p className="truncate text-xs font-medium">{source.label}</p><p className="truncate text-[10px] text-muted-foreground">{source.key}</p></div><Field label="Label"><Input aria-label={`${source.label} display label`} maxLength={120} value={value?.label??""} onChange={event=>update("label",event.target.value||undefined)} placeholder={source.label}/></Field><Field label="Unit"><Input aria-label={`${source.label} display unit`} maxLength={64} value={value?.unit??""} onChange={event=>update("unit",event.target.value||undefined)} placeholder={source.unit||"Unit"}/></Field><label className="grid gap-1 text-[11px] text-muted-foreground">Color<input aria-label={`${source.label} color`} type="color" value={value?.color??source.color??"#3b82f6"} onChange={event=>update("color",event.target.value)} className="h-9 w-10 cursor-pointer rounded border bg-background p-1"/></label></div>{star&&<div className="grid gap-2 sm:grid-cols-3"><Field label="Normalization"><Select value={mode} onValueChange={next=>onChange({...value,normalization:next as DashboardSeriesAppearance["normalization"],min:next==="manual"?minimum:undefined,max:next==="manual"?maximum:undefined})}><SelectTrigger aria-label={`${source.label} normalization`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="historical">Historical range</SelectItem><SelectItem value="zero_to_one">Fixed 0–1</SelectItem><SelectItem value="manual">Manual limits</SelectItem></SelectContent></Select></Field>{mode==="manual"&&<><NumberField label="Minimum" ariaLabel={`${source.label} minimum`} value={minimum} step="any" onValue={next=>onChange({...value,normalization:"manual",min:next,max:Math.max(maximum,next+Number.EPSILON)})}/><NumberField label="Maximum" ariaLabel={`${source.label} maximum`} value={maximum} step="any" onValue={next=>onChange({...value,normalization:"manual",min:Math.min(minimum,next-Number.EPSILON),max:next})}/></>}</div>}</div>}
function PointControls({appearance,set}:{appearance:DashboardWidgetAppearance;set:<K extends keyof DashboardWidgetAppearance>(key:K,value:DashboardWidgetAppearance[K])=>void}){return <><label className="flex items-center gap-2 self-end rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={appearance.show_points??false} onChange={event=>set("show_points",event.target.checked)}/>Show points</label><NumberField label="Marker size" value={appearance.point_size??(appearance.show_points?3:4)} min={1} max={16} step={1} onValue={value=>set("point_size",value)}/></>}
function NumberField({label,ariaLabel=label,value,min,max,step,onValue}:{label:string;ariaLabel?:string;value:number;min?:number;max?:number;step:number|"any";onValue:(value:number)=>void}){return <Field label={label}><Input aria-label={ariaLabel} type="number" value={value} min={min} max={max} step={step} onChange={event=>{const next=Number(event.target.value);if(Number.isFinite(next))onValue(next)}}/></Field>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1 text-xs text-muted-foreground">{label}{children}</label>}
function replaceSeries(series:Record<string,DashboardSeriesAppearance>|undefined,key:string,value?:DashboardSeriesAppearance){const next={...series};if(value)next[key]=value;else delete next[key];return Object.keys(next).length?next:undefined}
function titleCase(value:string){return value[0].toUpperCase()+value.slice(1)}
