import type { Dispatch, SetStateAction } from "react";
import { RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { DashboardAxisAppearance, DashboardSeriesAppearance, DashboardWidget, DashboardWidgetAppearance } from "@/lib/dashboard-widgets";

export type AppearanceSourceOption={key:string;label:string;unit?:string;color?:string};

export function WidgetAppearanceEditor({draft,sources,onChange}:{draft:DashboardWidget;sources:AppearanceSourceOption[];onChange:Dispatch<SetStateAction<DashboardWidget>>}){
  const plot=draft.type==="lineplot"||draft.type==="barplot"||draft.type==="scatterplot";
  if(!plot&&draft.type!=="confusion_matrix")return null;
  const appearance=draft.appearance??{schema_version:1 as const};
  const set=<K extends keyof DashboardWidgetAppearance>(key:K,value:DashboardWidgetAppearance[K])=>onChange(current=>({...current,appearance:{schema_version:1,...current.appearance,[key]:value}}));
  const reset=()=>onChange(current=>({...current,title:undefined,appearance:undefined}));
  return <fieldset className="rounded-md border p-3"><legend className="px-1 text-sm font-medium">Appearance</legend><div className="mb-3 flex justify-end"><Button type="button" variant="ghost" size="sm" className="h-7 gap-1.5 text-xs" onClick={reset}><RotateCcw className="size-3"/>Reset to defaults</Button></div>
    {draft.type==="confusion_matrix"?<Field label="Initial values"><Select value={appearance.matrix_mode??"absolute"} onValueChange={value=>set("matrix_mode",value as DashboardWidgetAppearance["matrix_mode"])}><SelectTrigger aria-label="Matrix mode"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="absolute">Absolute</SelectItem><SelectItem value="normalized">Normalized</SelectItem></SelectContent></Select></Field>:
    <div className="space-y-4">
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Title"><Input aria-label="Widget title" maxLength={120} value={draft.title??""} onChange={event=>onChange(current=>({...current,title:event.target.value}))} placeholder="No title"/></Field><Field label="Subtitle"><Input aria-label="Widget subtitle" maxLength={160} value={appearance.subtitle??""} onChange={event=>set("subtitle",event.target.value||undefined)} placeholder="No subtitle"/></Field></div>
      <div className="grid gap-3 sm:grid-cols-3"><Field label="Color scheme"><Select value={appearance.color_scheme??"default"} onValueChange={value=>set("color_scheme",value as DashboardWidgetAppearance["color_scheme"])}><SelectTrigger aria-label="Color scheme"><SelectValue/></SelectTrigger><SelectContent>{["default","cool","warm","monochrome"].map(value=><SelectItem key={value} value={value}>{titleCase(value)}</SelectItem>)}</SelectContent></Select></Field><Field label="Legend"><Select value={appearance.legend??"auto"} onValueChange={value=>set("legend",value as DashboardWidgetAppearance["legend"])}><SelectTrigger aria-label="Legend"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="auto">Available on demand</SelectItem><SelectItem value="open">Initially open</SelectItem><SelectItem value="hidden">Hidden</SelectItem></SelectContent></Select></Field><Field label="Opacity"><div className="flex h-9 items-center gap-2"><input aria-label="Plot opacity" type="range" min="0.05" max="1" step="0.05" value={appearance.opacity??1} onChange={event=>set("opacity",Number(event.target.value))} className="min-w-0 flex-1"/><span className="w-9 text-right text-xs tabular-nums">{Math.round((appearance.opacity??1)*100)}%</span></div></Field></div>
      <label className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={appearance.show_grid??true} onChange={event=>set("show_grid",event.target.checked)}/>Show grid</label>
      {draft.type==="lineplot"&&<div className="grid gap-3 sm:grid-cols-3"><Field label="Line style"><Select value={appearance.line_style??"solid"} onValueChange={value=>set("line_style",value as DashboardWidgetAppearance["line_style"])}><SelectTrigger aria-label="Line style"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="solid">Solid</SelectItem><SelectItem value="dashed">Dashed</SelectItem><SelectItem value="dotted">Dotted</SelectItem></SelectContent></Select></Field><NumberField label="Line width" value={appearance.line_width??2} min={.5} max={12} step={.5} onValue={value=>set("line_width",value)}/><PointControls appearance={appearance} set={set}/></div>}
      {draft.type==="scatterplot"&&<div className="grid gap-3 sm:grid-cols-2"><PointControls appearance={appearance} set={set}/></div>}
      <div className="grid gap-3 lg:grid-cols-2"><AxisEditor axis="X" value={appearance.x_axis} logDisabled={draft.type!=="scatterplot"&&draft.x_axis!=="step"} onChange={value=>set("x_axis",value)}/><AxisEditor axis="Y" value={appearance.y_axis} onChange={value=>set("y_axis",value)}/></div>
      {sources.length>0&&<details className="rounded-md border"><summary className="cursor-pointer px-3 py-2 text-sm font-medium">Series labels, units and colors</summary><div className="space-y-2 border-t p-3">{sources.map(source=><SeriesEditor key={source.key} source={source} value={appearance.series?.[source.key]} onChange={value=>set("series",replaceSeries(appearance.series,source.key,value))}/>)}</div></details>}
    </div>}
  </fieldset>;
}

function AxisEditor({axis,value,onChange,logDisabled=false}:{axis:"X"|"Y";value?:DashboardAxisAppearance;onChange:(value:DashboardAxisAppearance)=>void;logDisabled?:boolean}){const current=value??{},manual=current.range==="manual",epsilon=current.scale==="log"?.000001:Number.EPSILON;const update=<K extends keyof DashboardAxisAppearance>(key:K,next:DashboardAxisAppearance[K])=>onChange({...current,[key]:next});const scale=(next:"linear"|"log")=>onChange(next==="log"&&manual?{...current,scale:next,min:Math.max(epsilon,current.min??epsilon),max:Math.max(1,current.max??1)}:{...current,scale:next});return <fieldset className="grid gap-3 rounded-md border p-3 sm:grid-cols-2"><legend className="px-1 text-xs font-medium text-muted-foreground">{axis} axis</legend><Field label="Label"><Input aria-label={`${axis} axis label`} maxLength={80} value={current.label??""} onChange={event=>update("label",event.target.value||undefined)} placeholder="Automatic"/></Field><Field label="Unit"><Input aria-label={`${axis} axis unit`} maxLength={64} value={current.unit??""} onChange={event=>update("unit",event.target.value||undefined)} placeholder="Source unit"/></Field><Field label="Scale"><Select value={current.scale??"linear"} onValueChange={next=>scale(next as "linear"|"log")}><SelectTrigger aria-label={`${axis} axis scale`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="linear">Linear</SelectItem><SelectItem value="log" disabled={logDisabled}>Logarithmic</SelectItem></SelectContent></Select></Field><Field label="Range"><Select value={current.range??"auto"} onValueChange={next=>onChange(next==="manual"?{...current,range:"manual",min:current.min??(current.scale==="log"?.01:0),max:current.max??1}:{...current,range:"auto",min:undefined,max:undefined})}><SelectTrigger aria-label={`${axis} axis range`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="auto">Automatic</SelectItem><SelectItem value="manual">Manual</SelectItem></SelectContent></Select></Field>{manual&&<><NumberField label="Minimum" ariaLabel={`${axis} axis minimum`} value={current.min??0} step="any" onValue={next=>onChange({...current,min:current.scale==="log"?Math.max(epsilon,next):next,max:Math.max(current.max??next+1,next+epsilon)})}/><NumberField label="Maximum" ariaLabel={`${axis} axis maximum`} value={current.max??1} step="any" onValue={next=>{const maximum=current.scale==="log"?Math.max(epsilon*2,next):next;onChange({...current,min:Math.min(current.min??maximum-1,maximum-epsilon),max:maximum})}}/></>}</fieldset>}
function SeriesEditor({source,value,onChange}:{source:AppearanceSourceOption;value?:DashboardSeriesAppearance;onChange:(value?:DashboardSeriesAppearance)=>void}){const update=<K extends keyof DashboardSeriesAppearance>(key:K,next:DashboardSeriesAppearance[K])=>{const result={...value,[key]:next};onChange(Object.values(result).some(Boolean)?result:undefined)};return <div className="grid items-end gap-2 rounded-md bg-muted/35 p-2 sm:grid-cols-[minmax(8rem,1fr)_minmax(7rem,1fr)_minmax(6rem,.7fr)_2.5rem]"><div className="min-w-0"><p className="truncate text-xs font-medium">{source.label}</p><p className="truncate text-[10px] text-muted-foreground">{source.key}</p></div><Field label="Label"><Input aria-label={`${source.label} display label`} maxLength={120} value={value?.label??""} onChange={event=>update("label",event.target.value||undefined)} placeholder={source.label}/></Field><Field label="Unit"><Input aria-label={`${source.label} display unit`} maxLength={64} value={value?.unit??""} onChange={event=>update("unit",event.target.value||undefined)} placeholder={source.unit||"Unit"}/></Field><label className="grid gap-1 text-[11px] text-muted-foreground">Color<input aria-label={`${source.label} color`} type="color" value={value?.color??source.color??"#3b82f6"} onChange={event=>update("color",event.target.value)} className="h-9 w-10 cursor-pointer rounded border bg-background p-1"/></label></div>}
function PointControls({appearance,set}:{appearance:DashboardWidgetAppearance;set:<K extends keyof DashboardWidgetAppearance>(key:K,value:DashboardWidgetAppearance[K])=>void}){return <><label className="flex items-center gap-2 self-end rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={appearance.show_points??false} onChange={event=>set("show_points",event.target.checked)}/>Show points</label><NumberField label="Marker size" value={appearance.point_size??(appearance.show_points?3:4)} min={1} max={16} step={1} onValue={value=>set("point_size",value)}/></>}
function NumberField({label,ariaLabel=label,value,min,max,step,onValue}:{label:string;ariaLabel?:string;value:number;min?:number;max?:number;step:number|"any";onValue:(value:number)=>void}){return <Field label={label}><Input aria-label={ariaLabel} type="number" value={value} min={min} max={max} step={step} onChange={event=>{const next=Number(event.target.value);if(Number.isFinite(next))onValue(next)}}/></Field>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1 text-xs text-muted-foreground">{label}{children}</label>}
function replaceSeries(series:Record<string,DashboardSeriesAppearance>|undefined,key:string,value?:DashboardSeriesAppearance){const next={...series};if(value)next[key]=value;else delete next[key];return Object.keys(next).length?next:undefined}
function titleCase(value:string){return value[0].toUpperCase()+value.slice(1)}
